/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiDataAirportGet200ResponseInner,
  ApiDataFixGet200ResponseInner,
  ApiDataNavaidGet200ResponseInner,
  ErrorJSON,
  ErrorXML,
  StationInfoGeoJSON,
  StationInfoJSONInner,
  StationInfoXML,
} from '../models/index';
import {
    ApiDataAirportGet200ResponseInnerFromJSON,
    ApiDataAirportGet200ResponseInnerToJSON,
    ApiDataFixGet200ResponseInnerFromJSON,
    ApiDataFixGet200ResponseInnerToJSON,
    ApiDataNavaidGet200ResponseInnerFromJSON,
    ApiDataNavaidGet200ResponseInnerToJSON,
    ErrorJSONFromJSON,
    ErrorJSONToJSON,
    ErrorXMLFromJSON,
    ErrorXMLToJSON,
    StationInfoGeoJSONFromJSON,
    StationInfoGeoJSONToJSON,
    StationInfoJSONInnerFromJSON,
    StationInfoJSONInnerToJSON,
    StationInfoXMLFromJSON,
    StationInfoXMLToJSON,
} from '../models/index';

export interface ApiDataAirportGetRequest {
    ids?: string;
    bbox?: string;
    format?: ApiDataAirportGetFormatEnum;
}

export interface ApiDataFeatureGetRequest {
    bbox?: string;
    format?: ApiDataFeatureGetFormatEnum;
}

export interface ApiDataFixGetRequest {
    ids?: string;
    bbox?: string;
    format?: ApiDataFixGetFormatEnum;
}

export interface ApiDataNavaidGetRequest {
    ids?: string;
    bbox?: string;
    format?: ApiDataNavaidGetFormatEnum;
}

export interface ApiDataObstacleGetRequest {
    bbox?: string;
    format?: ApiDataObstacleGetFormatEnum;
}

export interface ApiDataStationinfoGetRequest {
    ids?: string;
    bbox?: string;
    format?: ApiDataStationinfoGetFormatEnum;
}

/**
 * NavigationalDataApi - interface
 * 
 * @export
 * @interface NavigationalDataApiInterface
 */
export interface NavigationalDataApiInterface {
    /**
     * Information about airports
     * @summary Airport info
     * @param {string} [ids] Station ID(s)
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'decoded' | 'json' | 'geojson'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NavigationalDataApiInterface
     */
    apiDataAirportGetRaw(requestParameters: ApiDataAirportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDataAirportGet200ResponseInner>>>;

    /**
     * Information about airports
     * Airport info
     */
    apiDataAirportGet(requestParameters: ApiDataAirportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDataAirportGet200ResponseInner>>;

    /**
     * Additional geographic features
     * @summary Feature info
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'json' | 'geojson'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NavigationalDataApiInterface
     */
    apiDataFeatureGetRaw(requestParameters: ApiDataFeatureGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Additional geographic features
     * Feature info
     */
    apiDataFeatureGet(requestParameters: ApiDataFeatureGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Navigational fix data
     * @summary Navigational fix/waypoint info
     * @param {string} [ids] 5 letter Fix ID(s)
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'json' | 'geojson'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NavigationalDataApiInterface
     */
    apiDataFixGetRaw(requestParameters: ApiDataFixGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDataFixGet200ResponseInner>>>;

    /**
     * Navigational fix data
     * Navigational fix/waypoint info
     */
    apiDataFixGet(requestParameters: ApiDataFixGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDataFixGet200ResponseInner>>;

    /**
     * Navigational aid data
     * @summary Navigational aid info
     * @param {string} [ids] three character identifier
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'json' | 'geojson'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NavigationalDataApiInterface
     */
    apiDataNavaidGetRaw(requestParameters: ApiDataNavaidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDataNavaidGet200ResponseInner>>>;

    /**
     * Navigational aid data
     * Navigational aid info
     */
    apiDataNavaidGet(requestParameters: ApiDataNavaidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDataNavaidGet200ResponseInner>>;

    /**
     * Aviation obstacle information
     * @summary Obstacle info
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'json' | 'geojson'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NavigationalDataApiInterface
     */
    apiDataObstacleGetRaw(requestParameters: ApiDataObstacleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Aviation obstacle information
     * Obstacle info
     */
    apiDataObstacleGet(requestParameters: ApiDataObstacleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Station observation location information
     * @summary Station info
     * @param {string} [ids] Station ID(s)
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'json' | 'geojson' | 'xml'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NavigationalDataApiInterface
     */
    apiDataStationinfoGetRaw(requestParameters: ApiDataStationinfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StationInfoJSONInner>>>;

    /**
     * Station observation location information
     * Station info
     */
    apiDataStationinfoGet(requestParameters: ApiDataStationinfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StationInfoJSONInner>>;

}

/**
 * 
 */
export class NavigationalDataApi extends runtime.BaseAPI implements NavigationalDataApiInterface {

    /**
     * Information about airports
     * Airport info
     */
    async apiDataAirportGetRaw(requestParameters: ApiDataAirportGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDataAirportGet200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/airport`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiDataAirportGet200ResponseInnerFromJSON));
    }

    /**
     * Information about airports
     * Airport info
     */
    async apiDataAirportGet(requestParameters: ApiDataAirportGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDataAirportGet200ResponseInner>> {
        const response = await this.apiDataAirportGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Additional geographic features
     * Feature info
     */
    async apiDataFeatureGetRaw(requestParameters: ApiDataFeatureGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/feature`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Additional geographic features
     * Feature info
     */
    async apiDataFeatureGet(requestParameters: ApiDataFeatureGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDataFeatureGetRaw(requestParameters, initOverrides);
    }

    /**
     * Navigational fix data
     * Navigational fix/waypoint info
     */
    async apiDataFixGetRaw(requestParameters: ApiDataFixGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDataFixGet200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/fix`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiDataFixGet200ResponseInnerFromJSON));
    }

    /**
     * Navigational fix data
     * Navigational fix/waypoint info
     */
    async apiDataFixGet(requestParameters: ApiDataFixGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDataFixGet200ResponseInner>> {
        const response = await this.apiDataFixGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Navigational aid data
     * Navigational aid info
     */
    async apiDataNavaidGetRaw(requestParameters: ApiDataNavaidGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiDataNavaidGet200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/navaid`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiDataNavaidGet200ResponseInnerFromJSON));
    }

    /**
     * Navigational aid data
     * Navigational aid info
     */
    async apiDataNavaidGet(requestParameters: ApiDataNavaidGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiDataNavaidGet200ResponseInner>> {
        const response = await this.apiDataNavaidGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Aviation obstacle information
     * Obstacle info
     */
    async apiDataObstacleGetRaw(requestParameters: ApiDataObstacleGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/obstacle`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Aviation obstacle information
     * Obstacle info
     */
    async apiDataObstacleGet(requestParameters: ApiDataObstacleGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDataObstacleGetRaw(requestParameters, initOverrides);
    }

    /**
     * Station observation location information
     * Station info
     */
    async apiDataStationinfoGetRaw(requestParameters: ApiDataStationinfoGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<StationInfoJSONInner>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/stationinfo`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(StationInfoJSONInnerFromJSON));
    }

    /**
     * Station observation location information
     * Station info
     */
    async apiDataStationinfoGet(requestParameters: ApiDataStationinfoGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<StationInfoJSONInner>> {
        const response = await this.apiDataStationinfoGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiDataAirportGetFormatEnum = {
    Decoded: 'decoded',
    Json: 'json',
    Geojson: 'geojson'
} as const;
export type ApiDataAirportGetFormatEnum = typeof ApiDataAirportGetFormatEnum[keyof typeof ApiDataAirportGetFormatEnum];
/**
 * @export
 */
export const ApiDataFeatureGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson'
} as const;
export type ApiDataFeatureGetFormatEnum = typeof ApiDataFeatureGetFormatEnum[keyof typeof ApiDataFeatureGetFormatEnum];
/**
 * @export
 */
export const ApiDataFixGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson'
} as const;
export type ApiDataFixGetFormatEnum = typeof ApiDataFixGetFormatEnum[keyof typeof ApiDataFixGetFormatEnum];
/**
 * @export
 */
export const ApiDataNavaidGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson'
} as const;
export type ApiDataNavaidGetFormatEnum = typeof ApiDataNavaidGetFormatEnum[keyof typeof ApiDataNavaidGetFormatEnum];
/**
 * @export
 */
export const ApiDataObstacleGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson'
} as const;
export type ApiDataObstacleGetFormatEnum = typeof ApiDataObstacleGetFormatEnum[keyof typeof ApiDataObstacleGetFormatEnum];
/**
 * @export
 */
export const ApiDataStationinfoGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml'
} as const;
export type ApiDataStationinfoGetFormatEnum = typeof ApiDataStationinfoGetFormatEnum[keyof typeof ApiDataStationinfoGetFormatEnum];
