/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AirSigmetGeoJSON,
  AirSigmetJSONInner,
  CwaGeoJSON,
  CwaJSONInner,
  ErrorJSON,
  ErrorXML,
  GairmetGeoJSON,
  GairmetJSONInner,
  ISigmetGeoJSON,
  ISigmetJSONInner,
  METARGeoJSON,
  METARXML,
  METARproperties,
  PIREPGeoJSON,
  PIREPJSONInner,
  PIREPXML,
  TAFGeoJSON,
  TAFproperties,
  TcfGeoJSON,
} from '../models/index';
import {
    AirSigmetGeoJSONFromJSON,
    AirSigmetGeoJSONToJSON,
    AirSigmetJSONInnerFromJSON,
    AirSigmetJSONInnerToJSON,
    CwaGeoJSONFromJSON,
    CwaGeoJSONToJSON,
    CwaJSONInnerFromJSON,
    CwaJSONInnerToJSON,
    ErrorJSONFromJSON,
    ErrorJSONToJSON,
    ErrorXMLFromJSON,
    ErrorXMLToJSON,
    GairmetGeoJSONFromJSON,
    GairmetGeoJSONToJSON,
    GairmetJSONInnerFromJSON,
    GairmetJSONInnerToJSON,
    ISigmetGeoJSONFromJSON,
    ISigmetGeoJSONToJSON,
    ISigmetJSONInnerFromJSON,
    ISigmetJSONInnerToJSON,
    METARGeoJSONFromJSON,
    METARGeoJSONToJSON,
    METARXMLFromJSON,
    METARXMLToJSON,
    METARpropertiesFromJSON,
    METARpropertiesToJSON,
    PIREPGeoJSONFromJSON,
    PIREPGeoJSONToJSON,
    PIREPJSONInnerFromJSON,
    PIREPJSONInnerToJSON,
    PIREPXMLFromJSON,
    PIREPXMLToJSON,
    TAFGeoJSONFromJSON,
    TAFGeoJSONToJSON,
    TAFpropertiesFromJSON,
    TAFpropertiesToJSON,
    TcfGeoJSONFromJSON,
    TcfGeoJSONToJSON,
} from '../models/index';

export interface ApiDataAirmetGetRequest {
    format?: ApiDataAirmetGetFormatEnum;
    hazard?: ApiDataAirmetGetHazardEnum;
    level?: number;
    date?: string;
}

export interface ApiDataAirsigmetGetRequest {
    format?: ApiDataAirsigmetGetFormatEnum;
    types?: ApiDataAirsigmetGetTypesEnum;
    hazard?: ApiDataAirsigmetGetHazardEnum;
    level?: number;
}

export interface ApiDataAreafcstGetRequest {
    region: ApiDataAreafcstGetRegionEnum;
}

export interface ApiDataCwaGetRequest {
    hazard?: ApiDataCwaGetHazardEnum;
    format?: ApiDataCwaGetFormatEnum;
    date?: string;
}

export interface ApiDataDataserverGetRequest {
    requestType: ApiDataDataserverGetRequestTypeEnum;
    dataSource: ApiDataDataserverGetDataSourceEnum;
    stationString?: string;
    boundingBox?: string;
    startTime?: string;
    endTime?: string;
    hoursBeforeNow?: number;
    format?: ApiDataDataserverGetFormatEnum;
    mostRecentForEachStation?: ApiDataDataserverGetMostRecentForEachStationEnum;
    radialDistance?: string;
}

export interface ApiDataFcstdiscGetRequest {
    cwa?: string;
    type?: ApiDataFcstdiscGetTypeEnum;
}

export interface ApiDataGairmetGetRequest {
    product?: ApiDataGairmetGetProductEnum;
    format?: ApiDataGairmetGetFormatEnum;
    hazard?: ApiDataGairmetGetHazardEnum;
    date?: string;
    fore?: ApiDataGairmetGetForeEnum;
}

export interface ApiDataIsigmetGetRequest {
    format?: ApiDataIsigmetGetFormatEnum;
    hazard?: ApiDataIsigmetGetHazardEnum;
    level?: number;
    date?: string;
}

export interface ApiDataMetarGetRequest {
    ids?: string;
    bbox?: string;
    format?: ApiDataMetarGetFormatEnum;
    taf?: boolean;
    hours?: number;
    date?: string;
}

export interface ApiDataMisGetRequest {
    loc?: string;
    format?: ApiDataMisGetFormatEnum;
}

export interface ApiDataPirepGetRequest {
    id?: string;
    distance?: number;
    bbox?: string;
    format?: ApiDataPirepGetFormatEnum;
    age?: number;
    level?: number;
    inten?: ApiDataPirepGetIntenEnum;
    date?: string;
}

export interface ApiDataTafGetRequest {
    ids?: string;
    bbox?: string;
    format?: ApiDataTafGetFormatEnum;
    metar?: boolean;
    time?: ApiDataTafGetTimeEnum;
    date?: string;
}

export interface ApiDataTcfGetRequest {
    format?: ApiDataTcfGetFormatEnum;
}

export interface ApiDataWindtempGetRequest {
    region?: ApiDataWindtempGetRegionEnum;
    level?: ApiDataWindtempGetLevelEnum;
    fcst?: ApiDataWindtempGetFcstEnum;
}

/**
 * WeatherDataApi - interface
 * 
 * @export
 * @interface WeatherDataApiInterface
 */
export interface WeatherDataApiInterface {
    /**
     * Decoded domestic AIRMETs (Alaska only). See /api/data/gairmet for similar advisories over the contiguous United States.
     * @summary AIRMETs
     * @param {'json' | 'geojson' | 'iwxxm'} [format] Format
     * @param {'turb' | 'ifr' | 'conv' | 'ice'} [hazard] Hazard
     * @param {number} [level] Level +-3000\&#39; to search
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataAirmetGetRaw(requestParameters: ApiDataAirmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Decoded domestic AIRMETs (Alaska only). See /api/data/gairmet for similar advisories over the contiguous United States.
     * AIRMETs
     */
    apiDataAirmetGet(requestParameters: ApiDataAirmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * Domestic SIGMETs for the contiguous United States. Does not include SIGMETs issued by the US in international format.
     * @summary Domestic SIGMETs
     * @param {'raw' | 'json' | 'geojson' | 'xml' | 'iwxxm'} [format] Format
     * @param {'sigmet' | 'airmet'} [types] Product type
     * @param {'conv' | 'turb' | 'ice' | 'ifr'} [hazard] Hazard
     * @param {number} [level] The level +-3000\&#39; to search
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataAirsigmetGetRaw(requestParameters: ApiDataAirsigmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Domestic SIGMETs for the contiguous United States. Does not include SIGMETs issued by the US in international format.
     * Domestic SIGMETs
     */
    apiDataAirsigmetGet(requestParameters: ApiDataAirsigmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Text Area Forecasts for the United States outside the contiguous states (Alaska)
     * @summary US Area Forecasts
     * @param {'aknorth' | 'akcentral' | 'akaleutian' | 'aksouth' | 'aksouthwest' | 'aksoutheast' | 'akpanhandle'} region Date  * &#x60;aknorth&#x60; - Northern half of Alaska  * &#x60;akcentral&#x60; - Interior Alaska  * &#x60;aksouth&#x60; - Southcentral Alaska  * &#x60;aksouthwest&#x60; - Alaska Peninsula  * &#x60;aksoutheast&#x60; - Eastern Gulf of Alaska  * &#x60;akpanhandle&#x60; - Alaska 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataAreafcstGetRaw(requestParameters: ApiDataAreafcstGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Text Area Forecasts for the United States outside the contiguous states (Alaska)
     * US Area Forecasts
     */
    apiDataAreafcstGet(requestParameters: ApiDataAreafcstGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Center Weather Advisories issued by NWS Center Weather Service Units (CWSUs)
     * @summary CWSU Center Advisories
     * @param {'ts' | 'turb' | 'ice' | 'ifr' | 'pcpn' | 'unk'} [hazard] Hazard
     * @param {'raw' | 'json' | 'geojson'} [format] Format
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataCwaGetRaw(requestParameters: ApiDataCwaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Center Weather Advisories issued by NWS Center Weather Service Units (CWSUs)
     * CWSU Center Advisories
     */
    apiDataCwaGet(requestParameters: ApiDataCwaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Compatibility layer with previous Text Data Service. Station identifiers or a bounding box, as well as a time selection, are required.
     * @summary Data Server
     * @param {'retrieve'} requestType 
     * @param {'metars' | 'tafs' | 'aircraftreports' | 'aisigmets' | 'gairmets'} dataSource 
     * @param {string} [stationString] Station ID(s)
     * @param {string} [boundingBox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {string} [startTime] Start time  * &#x60;yyyymmdd_hhmm&#x60;  * &#x60;yyyy-mm-ddThh:mm:ssZ&#x60; 
     * @param {string} [endTime] End time  * &#x60;yyyymmdd_hhmm&#x60;  * &#x60;yyyy-mm-ddThh:mm:ssZ&#x60; 
     * @param {number} [hoursBeforeNow] Number of hours before now to search
     * @param {'xml' | 'csv'} [format] Output format (TAFs not available in CSV format)
     * @param {'constraint' | 'postfilter'} [mostRecentForEachStation] Most recent per station (METARs and TAFs only)
     * @param {string} [radialDistance] Circular bounds defined by latitude, longitude and radial distance in statute miles (PIREPS only)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataDataserverGetRaw(requestParameters: ApiDataDataserverGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Compatibility layer with previous Text Data Service. Station identifiers or a bounding box, as well as a time selection, are required.
     * Data Server
     */
    apiDataDataserverGet(requestParameters: ApiDataDataserverGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Aviation Forecast Discussions issued by NWS Weather Forecast Offices. Returns aviation section or full discussion issued within the past six hours.
     * @summary US Forecast Discussions
     * @param {string} [cwa] County Warning Area (WFO)
     * @param {'afd' | 'af'} [type] Type of output:  * &#x60;afd&#x60; - aviation discussion  * &#x60;af&#x60; - full discussion 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataFcstdiscGetRaw(requestParameters: ApiDataFcstdiscGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Aviation Forecast Discussions issued by NWS Weather Forecast Offices. Returns aviation section or full discussion issued within the past six hours.
     * US Forecast Discussions
     */
    apiDataFcstdiscGet(requestParameters: ApiDataFcstdiscGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Decoded G-AIRMETs for the contiguous United States. See /api/data/airmet for similar advisories over Alaska.
     * @summary US Graphical AIRMETs
     * @param {'sierra' | 'tango' | 'zulu'} [product] Product type
     * @param {'raw' | 'json' | 'geojson' | 'xml'} [format] Format
     * @param {'turb-hi' | 'turb-lo' | 'llws' | 'sfc_wind' | 'ifr' | 'mtn_obs' | 'ice' | 'fzlvl'} [hazard] Hazard
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {0 | 3 | 6 | 9 | 12} [fore] Forecast hour from selected forecast package
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataGairmetGetRaw(requestParameters: ApiDataGairmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Decoded G-AIRMETs for the contiguous United States. See /api/data/airmet for similar advisories over Alaska.
     * US Graphical AIRMETs
     */
    apiDataGairmetGet(requestParameters: ApiDataGairmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Decoded international SIGMETs. This does not include SIGMETs issued by the United States in domestic format (i.e. convective and non-convective domestic SIGMETS).
     * @summary International SIGMETs
     * @param {'raw' | 'json' | 'geojson' | 'xml' | 'iwxxm'} [format] Format
     * @param {'turb' | 'ice'} [hazard] Hazard
     * @param {number} [level] Level +-3000\&#39; to search
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataIsigmetGetRaw(requestParameters: ApiDataIsigmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Decoded international SIGMETs. This does not include SIGMETs issued by the United States in domestic format (i.e. convective and non-convective domestic SIGMETS).
     * International SIGMETs
     */
    apiDataIsigmetGet(requestParameters: ApiDataIsigmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Decoded aviation weather observations. Station identifiers or a bounding box is required.
     * @summary METARs
     * @param {string} [ids] Station ID(s)
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'decoded' | 'json' | 'geojson' | 'xml' | 'iwxxm'} [format] Format
     * @param {boolean} [taf] Include TAF
     * @param {number} [hours] Hours back to search
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataMetarGetRaw(requestParameters: ApiDataMetarGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<METARproperties>>>;

    /**
     * Decoded aviation weather observations. Station identifiers or a bounding box is required.
     * METARs
     */
    apiDataMetarGet(requestParameters: ApiDataMetarGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<METARproperties>>;

    /**
     * Meteorological Information Statements issued by NWS Center Weather Service Units (CWSU)
     * @summary Meteorological Information Statement
     * @param {string} [loc] CWSU
     * @param {'json' | 'text'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataMisGetRaw(requestParameters: ApiDataMisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Meteorological Information Statements issued by NWS Center Weather Service Units (CWSU)
     * Meteorological Information Statement
     */
    apiDataMisGet(requestParameters: ApiDataMisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Pilot reports issued in PIREP or AIREP format. Bounding box, or center point identifier and radial distance, required.
     * @summary Pilot Reports
     * @param {string} [id] Airport ID for center of search
     * @param {number} [distance] Radial distance to search
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'decoded' | 'json' | 'geojson' | 'xml'} [format] Format
     * @param {number} [age] Hours Back
     * @param {number} [level] Level +-3000\&#39; to search
     * @param {'lgt' | 'mod' | 'sev'} [inten] Minimum intensity
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataPirepGetRaw(requestParameters: ApiDataPirepGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PIREPJSONInner>>>;

    /**
     * Pilot reports issued in PIREP or AIREP format. Bounding box, or center point identifier and radial distance, required.
     * Pilot Reports
     */
    apiDataPirepGet(requestParameters: ApiDataPirepGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PIREPJSONInner>>;

    /**
     * Decoded Terminal Aerodrome Forecast products. Station identifiers or a bounding box is required.
     * @summary TAFs
     * @param {string} [ids] Station ID(s)
     * @param {string} [bbox] Geographic bounding box (lat0, lon0, lat1, lon1)
     * @param {'raw' | 'json' | 'geojson' | 'xml' | 'iwxxm'} [format] Format
     * @param {boolean} [metar] Include METAR
     * @param {'valid' | 'issue'} [time] Process time by valid (default) or issuance time
     * @param {string} [date] String (&#x60;yyyymmdd_hhmm&#x60;) or ISO 8601 Date (&#x60;yyyy-mm-ddThh:mm:ssZ&#x60;)
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataTafGetRaw(requestParameters: ApiDataTafGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TAFproperties>>>;

    /**
     * Decoded Terminal Aerodrome Forecast products. Station identifiers or a bounding box is required.
     * TAFs
     */
    apiDataTafGet(requestParameters: ApiDataTafGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TAFproperties>>;

    /**
     * Traffic Flow Management (TFM) Convective Forecast. See https://aviationweather.gov/tcf/ for more information.
     * @summary TFM Convective Forecast (TCF)
     * @param {'raw' | 'geojson'} [format] Format
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataTcfGetRaw(requestParameters: ApiDataTcfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Traffic Flow Management (TFM) Convective Forecast. See https://aviationweather.gov/tcf/ for more information.
     * TFM Convective Forecast (TCF)
     */
    apiDataTcfGet(requestParameters: ApiDataTcfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

    /**
     * Wind and temperature information from the legacy FD winds
     * @summary Wind/Temp Point Data
     * @param {'us' | 'bos' | 'mia' | 'chi' | 'dfw' | 'slc' | 'sfo' | 'alaska' | 'hawaii' | 'other_pac'} [region] Region:  * &#x60;us&#x60; - All contiguous US sites  * &#x60;bos&#x60; - Northeast  * &#x60;mia&#x60; - Southeast  * &#x60;chi&#x60; - North central  * &#x60;dfw&#x60; - South central  * &#x60;slc&#x60; - Rocky Mountain  * &#x60;sfo&#x60; - Pacific Coast  * &#x60;alaska&#x60; - Alaska  * &#x60;hawaii&#x60; - Hawaii  * &#x60;other_pac&#x60; - Western Pacific 
     * @param {'low' | 'high'} [level] Level
     * @param {'06' | '12' | '24'} [fcst] Forecast cycle
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WeatherDataApiInterface
     */
    apiDataWindtempGetRaw(requestParameters: ApiDataWindtempGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>>;

    /**
     * Wind and temperature information from the legacy FD winds
     * Wind/Temp Point Data
     */
    apiDataWindtempGet(requestParameters: ApiDataWindtempGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string>;

}

/**
 * 
 */
export class WeatherDataApi extends runtime.BaseAPI implements WeatherDataApiInterface {

    /**
     * Decoded domestic AIRMETs (Alaska only). See /api/data/gairmet for similar advisories over the contiguous United States.
     * AIRMETs
     */
    async apiDataAirmetGetRaw(requestParameters: ApiDataAirmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['hazard'] != null) {
            queryParameters['hazard'] = requestParameters['hazard'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/airmet`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Decoded domestic AIRMETs (Alaska only). See /api/data/gairmet for similar advisories over the contiguous United States.
     * AIRMETs
     */
    async apiDataAirmetGet(requestParameters: ApiDataAirmetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.apiDataAirmetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Domestic SIGMETs for the contiguous United States. Does not include SIGMETs issued by the US in international format.
     * Domestic SIGMETs
     */
    async apiDataAirsigmetGetRaw(requestParameters: ApiDataAirsigmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['types'] != null) {
            queryParameters['types'] = requestParameters['types'];
        }

        if (requestParameters['hazard'] != null) {
            queryParameters['hazard'] = requestParameters['hazard'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/airsigmet`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Domestic SIGMETs for the contiguous United States. Does not include SIGMETs issued by the US in international format.
     * Domestic SIGMETs
     */
    async apiDataAirsigmetGet(requestParameters: ApiDataAirsigmetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataAirsigmetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Text Area Forecasts for the United States outside the contiguous states (Alaska)
     * US Area Forecasts
     */
    async apiDataAreafcstGetRaw(requestParameters: ApiDataAreafcstGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        if (requestParameters['region'] == null) {
            throw new runtime.RequiredError(
                'region',
                'Required parameter "region" was null or undefined when calling apiDataAreafcstGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/areafcst`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Text Area Forecasts for the United States outside the contiguous states (Alaska)
     * US Area Forecasts
     */
    async apiDataAreafcstGet(requestParameters: ApiDataAreafcstGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataAreafcstGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Center Weather Advisories issued by NWS Center Weather Service Units (CWSUs)
     * CWSU Center Advisories
     */
    async apiDataCwaGetRaw(requestParameters: ApiDataCwaGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['hazard'] != null) {
            queryParameters['hazard'] = requestParameters['hazard'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/cwa`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Center Weather Advisories issued by NWS Center Weather Service Units (CWSUs)
     * CWSU Center Advisories
     */
    async apiDataCwaGet(requestParameters: ApiDataCwaGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataCwaGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Compatibility layer with previous Text Data Service. Station identifiers or a bounding box, as well as a time selection, are required.
     * Data Server
     */
    async apiDataDataserverGetRaw(requestParameters: ApiDataDataserverGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['requestType'] == null) {
            throw new runtime.RequiredError(
                'requestType',
                'Required parameter "requestType" was null or undefined when calling apiDataDataserverGet().'
            );
        }

        if (requestParameters['dataSource'] == null) {
            throw new runtime.RequiredError(
                'dataSource',
                'Required parameter "dataSource" was null or undefined when calling apiDataDataserverGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['requestType'] != null) {
            queryParameters['requestType'] = requestParameters['requestType'];
        }

        if (requestParameters['dataSource'] != null) {
            queryParameters['dataSource'] = requestParameters['dataSource'];
        }

        if (requestParameters['stationString'] != null) {
            queryParameters['stationString'] = requestParameters['stationString'];
        }

        if (requestParameters['boundingBox'] != null) {
            queryParameters['boundingBox'] = requestParameters['boundingBox'];
        }

        if (requestParameters['startTime'] != null) {
            queryParameters['startTime'] = requestParameters['startTime'];
        }

        if (requestParameters['endTime'] != null) {
            queryParameters['endTime'] = requestParameters['endTime'];
        }

        if (requestParameters['hoursBeforeNow'] != null) {
            queryParameters['hoursBeforeNow'] = requestParameters['hoursBeforeNow'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['mostRecentForEachStation'] != null) {
            queryParameters['mostRecentForEachStation'] = requestParameters['mostRecentForEachStation'];
        }

        if (requestParameters['radialDistance'] != null) {
            queryParameters['radialDistance'] = requestParameters['radialDistance'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/dataserver`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Compatibility layer with previous Text Data Service. Station identifiers or a bounding box, as well as a time selection, are required.
     * Data Server
     */
    async apiDataDataserverGet(requestParameters: ApiDataDataserverGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiDataDataserverGetRaw(requestParameters, initOverrides);
    }

    /**
     * Aviation Forecast Discussions issued by NWS Weather Forecast Offices. Returns aviation section or full discussion issued within the past six hours.
     * US Forecast Discussions
     */
    async apiDataFcstdiscGetRaw(requestParameters: ApiDataFcstdiscGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['cwa'] != null) {
            queryParameters['cwa'] = requestParameters['cwa'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/fcstdisc`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Aviation Forecast Discussions issued by NWS Weather Forecast Offices. Returns aviation section or full discussion issued within the past six hours.
     * US Forecast Discussions
     */
    async apiDataFcstdiscGet(requestParameters: ApiDataFcstdiscGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataFcstdiscGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Decoded G-AIRMETs for the contiguous United States. See /api/data/airmet for similar advisories over Alaska.
     * US Graphical AIRMETs
     */
    async apiDataGairmetGetRaw(requestParameters: ApiDataGairmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['product'] != null) {
            queryParameters['product'] = requestParameters['product'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['hazard'] != null) {
            queryParameters['hazard'] = requestParameters['hazard'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        if (requestParameters['fore'] != null) {
            queryParameters['fore'] = requestParameters['fore'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/gairmet`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Decoded G-AIRMETs for the contiguous United States. See /api/data/airmet for similar advisories over Alaska.
     * US Graphical AIRMETs
     */
    async apiDataGairmetGet(requestParameters: ApiDataGairmetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataGairmetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Decoded international SIGMETs. This does not include SIGMETs issued by the United States in domestic format (i.e. convective and non-convective domestic SIGMETS).
     * International SIGMETs
     */
    async apiDataIsigmetGetRaw(requestParameters: ApiDataIsigmetGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['hazard'] != null) {
            queryParameters['hazard'] = requestParameters['hazard'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/isigmet`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Decoded international SIGMETs. This does not include SIGMETs issued by the United States in domestic format (i.e. convective and non-convective domestic SIGMETS).
     * International SIGMETs
     */
    async apiDataIsigmetGet(requestParameters: ApiDataIsigmetGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataIsigmetGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Decoded aviation weather observations. Station identifiers or a bounding box is required.
     * METARs
     */
    async apiDataMetarGetRaw(requestParameters: ApiDataMetarGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<METARproperties>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['taf'] != null) {
            queryParameters['taf'] = requestParameters['taf'];
        }

        if (requestParameters['hours'] != null) {
            queryParameters['hours'] = requestParameters['hours'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/metar`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(METARpropertiesFromJSON));
    }

    /**
     * Decoded aviation weather observations. Station identifiers or a bounding box is required.
     * METARs
     */
    async apiDataMetarGet(requestParameters: ApiDataMetarGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<METARproperties>> {
        const response = await this.apiDataMetarGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Meteorological Information Statements issued by NWS Center Weather Service Units (CWSU)
     * Meteorological Information Statement
     */
    async apiDataMisGetRaw(requestParameters: ApiDataMisGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['loc'] != null) {
            queryParameters['loc'] = requestParameters['loc'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/mis`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Meteorological Information Statements issued by NWS Center Weather Service Units (CWSU)
     * Meteorological Information Statement
     */
    async apiDataMisGet(requestParameters: ApiDataMisGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataMisGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Pilot reports issued in PIREP or AIREP format. Bounding box, or center point identifier and radial distance, required.
     * Pilot Reports
     */
    async apiDataPirepGetRaw(requestParameters: ApiDataPirepGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PIREPJSONInner>>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        if (requestParameters['distance'] != null) {
            queryParameters['distance'] = requestParameters['distance'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['age'] != null) {
            queryParameters['age'] = requestParameters['age'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['inten'] != null) {
            queryParameters['inten'] = requestParameters['inten'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/pirep`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PIREPJSONInnerFromJSON));
    }

    /**
     * Pilot reports issued in PIREP or AIREP format. Bounding box, or center point identifier and radial distance, required.
     * Pilot Reports
     */
    async apiDataPirepGet(requestParameters: ApiDataPirepGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PIREPJSONInner>> {
        const response = await this.apiDataPirepGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Decoded Terminal Aerodrome Forecast products. Station identifiers or a bounding box is required.
     * TAFs
     */
    async apiDataTafGetRaw(requestParameters: ApiDataTafGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<TAFproperties>>> {
        const queryParameters: any = {};

        if (requestParameters['ids'] != null) {
            queryParameters['ids'] = requestParameters['ids'];
        }

        if (requestParameters['bbox'] != null) {
            queryParameters['bbox'] = requestParameters['bbox'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['metar'] != null) {
            queryParameters['metar'] = requestParameters['metar'];
        }

        if (requestParameters['time'] != null) {
            queryParameters['time'] = requestParameters['time'];
        }

        if (requestParameters['date'] != null) {
            queryParameters['date'] = requestParameters['date'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/taf`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(TAFpropertiesFromJSON));
    }

    /**
     * Decoded Terminal Aerodrome Forecast products. Station identifiers or a bounding box is required.
     * TAFs
     */
    async apiDataTafGet(requestParameters: ApiDataTafGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<TAFproperties>> {
        const response = await this.apiDataTafGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Traffic Flow Management (TFM) Convective Forecast. See https://aviationweather.gov/tcf/ for more information.
     * TFM Convective Forecast (TCF)
     */
    async apiDataTcfGetRaw(requestParameters: ApiDataTcfGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/tcf`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Traffic Flow Management (TFM) Convective Forecast. See https://aviationweather.gov/tcf/ for more information.
     * TFM Convective Forecast (TCF)
     */
    async apiDataTcfGet(requestParameters: ApiDataTcfGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataTcfGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Wind and temperature information from the legacy FD winds
     * Wind/Temp Point Data
     */
    async apiDataWindtempGetRaw(requestParameters: ApiDataWindtempGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['level'] != null) {
            queryParameters['level'] = requestParameters['level'];
        }

        if (requestParameters['fcst'] != null) {
            queryParameters['fcst'] = requestParameters['fcst'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/data/windtemp`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Wind and temperature information from the legacy FD winds
     * Wind/Temp Point Data
     */
    async apiDataWindtempGet(requestParameters: ApiDataWindtempGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiDataWindtempGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ApiDataAirmetGetFormatEnum = {
    Json: 'json',
    Geojson: 'geojson',
    Iwxxm: 'iwxxm'
} as const;
export type ApiDataAirmetGetFormatEnum = typeof ApiDataAirmetGetFormatEnum[keyof typeof ApiDataAirmetGetFormatEnum];
/**
 * @export
 */
export const ApiDataAirmetGetHazardEnum = {
    Turb: 'turb',
    Ifr: 'ifr',
    Conv: 'conv',
    Ice: 'ice'
} as const;
export type ApiDataAirmetGetHazardEnum = typeof ApiDataAirmetGetHazardEnum[keyof typeof ApiDataAirmetGetHazardEnum];
/**
 * @export
 */
export const ApiDataAirsigmetGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml',
    Iwxxm: 'iwxxm'
} as const;
export type ApiDataAirsigmetGetFormatEnum = typeof ApiDataAirsigmetGetFormatEnum[keyof typeof ApiDataAirsigmetGetFormatEnum];
/**
 * @export
 */
export const ApiDataAirsigmetGetTypesEnum = {
    Sigmet: 'sigmet',
    Airmet: 'airmet'
} as const;
export type ApiDataAirsigmetGetTypesEnum = typeof ApiDataAirsigmetGetTypesEnum[keyof typeof ApiDataAirsigmetGetTypesEnum];
/**
 * @export
 */
export const ApiDataAirsigmetGetHazardEnum = {
    Conv: 'conv',
    Turb: 'turb',
    Ice: 'ice',
    Ifr: 'ifr'
} as const;
export type ApiDataAirsigmetGetHazardEnum = typeof ApiDataAirsigmetGetHazardEnum[keyof typeof ApiDataAirsigmetGetHazardEnum];
/**
 * @export
 */
export const ApiDataAreafcstGetRegionEnum = {
    Aknorth: 'aknorth',
    Akcentral: 'akcentral',
    Akaleutian: 'akaleutian',
    Aksouth: 'aksouth',
    Aksouthwest: 'aksouthwest',
    Aksoutheast: 'aksoutheast',
    Akpanhandle: 'akpanhandle'
} as const;
export type ApiDataAreafcstGetRegionEnum = typeof ApiDataAreafcstGetRegionEnum[keyof typeof ApiDataAreafcstGetRegionEnum];
/**
 * @export
 */
export const ApiDataCwaGetHazardEnum = {
    Ts: 'ts',
    Turb: 'turb',
    Ice: 'ice',
    Ifr: 'ifr',
    Pcpn: 'pcpn',
    Unk: 'unk'
} as const;
export type ApiDataCwaGetHazardEnum = typeof ApiDataCwaGetHazardEnum[keyof typeof ApiDataCwaGetHazardEnum];
/**
 * @export
 */
export const ApiDataCwaGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson'
} as const;
export type ApiDataCwaGetFormatEnum = typeof ApiDataCwaGetFormatEnum[keyof typeof ApiDataCwaGetFormatEnum];
/**
 * @export
 */
export const ApiDataDataserverGetRequestTypeEnum = {
    Retrieve: 'retrieve'
} as const;
export type ApiDataDataserverGetRequestTypeEnum = typeof ApiDataDataserverGetRequestTypeEnum[keyof typeof ApiDataDataserverGetRequestTypeEnum];
/**
 * @export
 */
export const ApiDataDataserverGetDataSourceEnum = {
    Metars: 'metars',
    Tafs: 'tafs',
    Aircraftreports: 'aircraftreports',
    Aisigmets: 'aisigmets',
    Gairmets: 'gairmets'
} as const;
export type ApiDataDataserverGetDataSourceEnum = typeof ApiDataDataserverGetDataSourceEnum[keyof typeof ApiDataDataserverGetDataSourceEnum];
/**
 * @export
 */
export const ApiDataDataserverGetFormatEnum = {
    Xml: 'xml',
    Csv: 'csv'
} as const;
export type ApiDataDataserverGetFormatEnum = typeof ApiDataDataserverGetFormatEnum[keyof typeof ApiDataDataserverGetFormatEnum];
/**
 * @export
 */
export const ApiDataDataserverGetMostRecentForEachStationEnum = {
    Constraint: 'constraint',
    Postfilter: 'postfilter'
} as const;
export type ApiDataDataserverGetMostRecentForEachStationEnum = typeof ApiDataDataserverGetMostRecentForEachStationEnum[keyof typeof ApiDataDataserverGetMostRecentForEachStationEnum];
/**
 * @export
 */
export const ApiDataFcstdiscGetTypeEnum = {
    Afd: 'afd',
    Af: 'af'
} as const;
export type ApiDataFcstdiscGetTypeEnum = typeof ApiDataFcstdiscGetTypeEnum[keyof typeof ApiDataFcstdiscGetTypeEnum];
/**
 * @export
 */
export const ApiDataGairmetGetProductEnum = {
    Sierra: 'sierra',
    Tango: 'tango',
    Zulu: 'zulu'
} as const;
export type ApiDataGairmetGetProductEnum = typeof ApiDataGairmetGetProductEnum[keyof typeof ApiDataGairmetGetProductEnum];
/**
 * @export
 */
export const ApiDataGairmetGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml'
} as const;
export type ApiDataGairmetGetFormatEnum = typeof ApiDataGairmetGetFormatEnum[keyof typeof ApiDataGairmetGetFormatEnum];
/**
 * @export
 */
export const ApiDataGairmetGetHazardEnum = {
    TurbHi: 'turb-hi',
    TurbLo: 'turb-lo',
    Llws: 'llws',
    SfcWind: 'sfc_wind',
    Ifr: 'ifr',
    MtnObs: 'mtn_obs',
    Ice: 'ice',
    Fzlvl: 'fzlvl'
} as const;
export type ApiDataGairmetGetHazardEnum = typeof ApiDataGairmetGetHazardEnum[keyof typeof ApiDataGairmetGetHazardEnum];
/**
 * @export
 */
export const ApiDataGairmetGetForeEnum = {
    NUMBER_0: 0,
    NUMBER_3: 3,
    NUMBER_6: 6,
    NUMBER_9: 9,
    NUMBER_12: 12
} as const;
export type ApiDataGairmetGetForeEnum = typeof ApiDataGairmetGetForeEnum[keyof typeof ApiDataGairmetGetForeEnum];
/**
 * @export
 */
export const ApiDataIsigmetGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml',
    Iwxxm: 'iwxxm'
} as const;
export type ApiDataIsigmetGetFormatEnum = typeof ApiDataIsigmetGetFormatEnum[keyof typeof ApiDataIsigmetGetFormatEnum];
/**
 * @export
 */
export const ApiDataIsigmetGetHazardEnum = {
    Turb: 'turb',
    Ice: 'ice'
} as const;
export type ApiDataIsigmetGetHazardEnum = typeof ApiDataIsigmetGetHazardEnum[keyof typeof ApiDataIsigmetGetHazardEnum];
/**
 * @export
 */
export const ApiDataMetarGetFormatEnum = {
    Raw: 'raw',
    Decoded: 'decoded',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml',
    Iwxxm: 'iwxxm'
} as const;
export type ApiDataMetarGetFormatEnum = typeof ApiDataMetarGetFormatEnum[keyof typeof ApiDataMetarGetFormatEnum];
/**
 * @export
 */
export const ApiDataMisGetFormatEnum = {
    Json: 'json',
    Text: 'text'
} as const;
export type ApiDataMisGetFormatEnum = typeof ApiDataMisGetFormatEnum[keyof typeof ApiDataMisGetFormatEnum];
/**
 * @export
 */
export const ApiDataPirepGetFormatEnum = {
    Raw: 'raw',
    Decoded: 'decoded',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml'
} as const;
export type ApiDataPirepGetFormatEnum = typeof ApiDataPirepGetFormatEnum[keyof typeof ApiDataPirepGetFormatEnum];
/**
 * @export
 */
export const ApiDataPirepGetIntenEnum = {
    Lgt: 'lgt',
    Mod: 'mod',
    Sev: 'sev'
} as const;
export type ApiDataPirepGetIntenEnum = typeof ApiDataPirepGetIntenEnum[keyof typeof ApiDataPirepGetIntenEnum];
/**
 * @export
 */
export const ApiDataTafGetFormatEnum = {
    Raw: 'raw',
    Json: 'json',
    Geojson: 'geojson',
    Xml: 'xml',
    Iwxxm: 'iwxxm'
} as const;
export type ApiDataTafGetFormatEnum = typeof ApiDataTafGetFormatEnum[keyof typeof ApiDataTafGetFormatEnum];
/**
 * @export
 */
export const ApiDataTafGetTimeEnum = {
    Valid: 'valid',
    Issue: 'issue'
} as const;
export type ApiDataTafGetTimeEnum = typeof ApiDataTafGetTimeEnum[keyof typeof ApiDataTafGetTimeEnum];
/**
 * @export
 */
export const ApiDataTcfGetFormatEnum = {
    Raw: 'raw',
    Geojson: 'geojson'
} as const;
export type ApiDataTcfGetFormatEnum = typeof ApiDataTcfGetFormatEnum[keyof typeof ApiDataTcfGetFormatEnum];
/**
 * @export
 */
export const ApiDataWindtempGetRegionEnum = {
    Us: 'us',
    Bos: 'bos',
    Mia: 'mia',
    Chi: 'chi',
    Dfw: 'dfw',
    Slc: 'slc',
    Sfo: 'sfo',
    Alaska: 'alaska',
    Hawaii: 'hawaii',
    OtherPac: 'other_pac'
} as const;
export type ApiDataWindtempGetRegionEnum = typeof ApiDataWindtempGetRegionEnum[keyof typeof ApiDataWindtempGetRegionEnum];
/**
 * @export
 */
export const ApiDataWindtempGetLevelEnum = {
    Low: 'low',
    High: 'high'
} as const;
export type ApiDataWindtempGetLevelEnum = typeof ApiDataWindtempGetLevelEnum[keyof typeof ApiDataWindtempGetLevelEnum];
/**
 * @export
 */
export const ApiDataWindtempGetFcstEnum = {
    _06: '06',
    _12: '12',
    _24: '24'
} as const;
export type ApiDataWindtempGetFcstEnum = typeof ApiDataWindtempGetFcstEnum[keyof typeof ApiDataWindtempGetFcstEnum];
