/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirSigmetGeoJSONFeaturesInnerGeometry } from './air-sigmet-geo-json-features-inner-geometry';
import {
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './air-sigmet-geo-json-features-inner-geometry';
import type { AirSigmetGeoJSONFeaturesInnerProperties } from './air-sigmet-geo-json-features-inner-properties';
import {
    AirSigmetGeoJSONFeaturesInnerPropertiesFromJSON,
    AirSigmetGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerPropertiesToJSON,
    AirSigmetGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './air-sigmet-geo-json-features-inner-properties';

/**
 * 
 * @export
 * @interface AirSigmetGeoJSONFeaturesInner
 */
export interface AirSigmetGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInner
     */
    type?: AirSigmetGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerProperties}
     * @memberof AirSigmetGeoJSONFeaturesInner
     */
    properties?: AirSigmetGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerGeometry}
     * @memberof AirSigmetGeoJSONFeaturesInner
     */
    geometry?: AirSigmetGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const AirSigmetGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type AirSigmetGeoJSONFeaturesInnerTypeEnum = typeof AirSigmetGeoJSONFeaturesInnerTypeEnum[keyof typeof AirSigmetGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the AirSigmetGeoJSONFeaturesInner interface.
 */
export function instanceOfAirSigmetGeoJSONFeaturesInner(value: object): value is AirSigmetGeoJSONFeaturesInner {
    return true;
}

export function AirSigmetGeoJSONFeaturesInnerFromJSON(json: any): AirSigmetGeoJSONFeaturesInner {
    return AirSigmetGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function AirSigmetGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirSigmetGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function AirSigmetGeoJSONFeaturesInnerToJSON(json: any): AirSigmetGeoJSONFeaturesInner {
    return AirSigmetGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function AirSigmetGeoJSONFeaturesInnerToJSONTyped(value?: AirSigmetGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': AirSigmetGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': AirSigmetGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

