/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirSigmetJSONInner
 */
export interface AirSigmetJSONInner {
    /**
     * 
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    icaoId?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    alphaChar?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    seriesId?: string;
    /**
     * Time received by AWC
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    receiptTime?: string;
    /**
     * Issuance time
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    creationTime?: string;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    validTimeFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    validTimeTo?: number;
    /**
     * Product type (always SIGMET)
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    airSigmetType?: AirSigmetJSONInnerAirSigmetTypeEnum;
    /**
     * Hazard type
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    hazard?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    qualifier?: string;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    altitudeHi1?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    altitudeHi2?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    altitudeLo1?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    altitudeLo2?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    movementDir?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    movementSpd?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    postProcessFlag?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetJSONInner
     */
    severity?: number;
    /**
     * Raw product
     * @type {string}
     * @memberof AirSigmetJSONInner
     */
    rawAirSigmet?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof AirSigmetJSONInner
     */
    coords?: Array<object>;
}


/**
 * @export
 */
export const AirSigmetJSONInnerAirSigmetTypeEnum = {
    Sigmet: 'SIGMET'
} as const;
export type AirSigmetJSONInnerAirSigmetTypeEnum = typeof AirSigmetJSONInnerAirSigmetTypeEnum[keyof typeof AirSigmetJSONInnerAirSigmetTypeEnum];


/**
 * Check if a given object implements the AirSigmetJSONInner interface.
 */
export function instanceOfAirSigmetJSONInner(value: object): value is AirSigmetJSONInner {
    return true;
}

export function AirSigmetJSONInnerFromJSON(json: any): AirSigmetJSONInner {
    return AirSigmetJSONInnerFromJSONTyped(json, false);
}

export function AirSigmetJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirSigmetJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'alphaChar': json['alphaChar'] == null ? undefined : json['alphaChar'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'creationTime': json['creationTime'] == null ? undefined : json['creationTime'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'airSigmetType': json['airSigmetType'] == null ? undefined : json['airSigmetType'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'qualifier': json['qualifier'] == null ? undefined : json['qualifier'],
        'altitudeHi1': json['altitudeHi1'] == null ? undefined : json['altitudeHi1'],
        'altitudeHi2': json['altitudeHi2'] == null ? undefined : json['altitudeHi2'],
        'altitudeLo1': json['altitudeLo1'] == null ? undefined : json['altitudeLo1'],
        'altitudeLo2': json['altitudeLo2'] == null ? undefined : json['altitudeLo2'],
        'movementDir': json['movementDir'] == null ? undefined : json['movementDir'],
        'movementSpd': json['movementSpd'] == null ? undefined : json['movementSpd'],
        'postProcessFlag': json['postProcessFlag'] == null ? undefined : json['postProcessFlag'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'rawAirSigmet': json['rawAirSigmet'] == null ? undefined : json['rawAirSigmet'],
        'coords': json['coords'] == null ? undefined : json['coords'],
    };
}

export function AirSigmetJSONInnerToJSON(json: any): AirSigmetJSONInner {
    return AirSigmetJSONInnerToJSONTyped(json, false);
}

export function AirSigmetJSONInnerToJSONTyped(value?: AirSigmetJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'alphaChar': value['alphaChar'],
        'seriesId': value['seriesId'],
        'receiptTime': value['receiptTime'],
        'creationTime': value['creationTime'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'airSigmetType': value['airSigmetType'],
        'hazard': value['hazard'],
        'qualifier': value['qualifier'],
        'altitudeHi1': value['altitudeHi1'],
        'altitudeHi2': value['altitudeHi2'],
        'altitudeLo1': value['altitudeLo1'],
        'altitudeLo2': value['altitudeLo2'],
        'movementDir': value['movementDir'],
        'movementSpd': value['movementSpd'],
        'postProcessFlag': value['postProcessFlag'],
        'severity': value['severity'],
        'rawAirSigmet': value['rawAirSigmet'],
        'coords': value['coords'],
    };
}

