/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirSigmetGeoJSONFeaturesInnerGeometry
 */
export interface AirSigmetGeoJSONFeaturesInnerGeometry {
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerGeometry
     */
    type?: AirSigmetGeoJSONFeaturesInnerGeometryTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof AirSigmetGeoJSONFeaturesInnerGeometry
     */
    coordinates?: Array<number>;
}


/**
 * @export
 */
export const AirSigmetGeoJSONFeaturesInnerGeometryTypeEnum = {
    Polygon: 'Polygon'
} as const;
export type AirSigmetGeoJSONFeaturesInnerGeometryTypeEnum = typeof AirSigmetGeoJSONFeaturesInnerGeometryTypeEnum[keyof typeof AirSigmetGeoJSONFeaturesInnerGeometryTypeEnum];


/**
 * Check if a given object implements the AirSigmetGeoJSONFeaturesInnerGeometry interface.
 */
export function instanceOfAirSigmetGeoJSONFeaturesInnerGeometry(value: object): value is AirSigmetGeoJSONFeaturesInnerGeometry {
    return true;
}

export function AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json: any): AirSigmetGeoJSONFeaturesInnerGeometry {
    return AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped(json, false);
}

export function AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirSigmetGeoJSONFeaturesInnerGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
    };
}

export function AirSigmetGeoJSONFeaturesInnerGeometryToJSON(json: any): AirSigmetGeoJSONFeaturesInnerGeometry {
    return AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped(json, false);
}

export function AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped(value?: AirSigmetGeoJSONFeaturesInnerGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

