/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirSigmetGeoJSONFeaturesInner } from './air-sigmet-geo-json-features-inner';
import {
    AirSigmetGeoJSONFeaturesInnerFromJSON,
    AirSigmetGeoJSONFeaturesInnerFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerToJSON,
    AirSigmetGeoJSONFeaturesInnerToJSONTyped,
} from './air-sigmet-geo-json-features-inner';

/**
 * 
 * @export
 * @interface AirSigmetGeoJSON
 */
export interface AirSigmetGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSON
     */
    type?: AirSigmetGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<AirSigmetGeoJSONFeaturesInner>}
     * @memberof AirSigmetGeoJSON
     */
    features?: Array<AirSigmetGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const AirSigmetGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type AirSigmetGeoJSONTypeEnum = typeof AirSigmetGeoJSONTypeEnum[keyof typeof AirSigmetGeoJSONTypeEnum];


/**
 * Check if a given object implements the AirSigmetGeoJSON interface.
 */
export function instanceOfAirSigmetGeoJSON(value: object): value is AirSigmetGeoJSON {
    return true;
}

export function AirSigmetGeoJSONFromJSON(json: any): AirSigmetGeoJSON {
    return AirSigmetGeoJSONFromJSONTyped(json, false);
}

export function AirSigmetGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirSigmetGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(AirSigmetGeoJSONFeaturesInnerFromJSON)),
    };
}

export function AirSigmetGeoJSONToJSON(json: any): AirSigmetGeoJSON {
    return AirSigmetGeoJSONToJSONTyped(json, false);
}

export function AirSigmetGeoJSONToJSONTyped(value?: AirSigmetGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(AirSigmetGeoJSONFeaturesInnerToJSON)),
    };
}

