/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirSigmetGeoJSONFeaturesInnerProperties
 */
export interface AirSigmetGeoJSONFeaturesInnerProperties {
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    icaoId?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    alphaChar?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    seriesId?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    validTimeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    validTimeTo?: string;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    airSigmetType?: AirSigmetGeoJSONFeaturesInnerPropertiesAirSigmetTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    hazard?: string;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    altitudeHi1?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    altitudeHi2?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    altitudeLo1?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    altitudeLo2?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    movementDir?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    movementSpd?: number;
    /**
     * 
     * @type {number}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    severity?: number;
    /**
     * 
     * @type {string}
     * @memberof AirSigmetGeoJSONFeaturesInnerProperties
     */
    rawAirSigmet?: string;
}


/**
 * @export
 */
export const AirSigmetGeoJSONFeaturesInnerPropertiesAirSigmetTypeEnum = {
    Sigmet: 'SIGMET'
} as const;
export type AirSigmetGeoJSONFeaturesInnerPropertiesAirSigmetTypeEnum = typeof AirSigmetGeoJSONFeaturesInnerPropertiesAirSigmetTypeEnum[keyof typeof AirSigmetGeoJSONFeaturesInnerPropertiesAirSigmetTypeEnum];


/**
 * Check if a given object implements the AirSigmetGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfAirSigmetGeoJSONFeaturesInnerProperties(value: object): value is AirSigmetGeoJSONFeaturesInnerProperties {
    return true;
}

export function AirSigmetGeoJSONFeaturesInnerPropertiesFromJSON(json: any): AirSigmetGeoJSONFeaturesInnerProperties {
    return AirSigmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function AirSigmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirSigmetGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'alphaChar': json['alphaChar'] == null ? undefined : json['alphaChar'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'airSigmetType': json['airSigmetType'] == null ? undefined : json['airSigmetType'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'altitudeHi1': json['altitudeHi1'] == null ? undefined : json['altitudeHi1'],
        'altitudeHi2': json['altitudeHi2'] == null ? undefined : json['altitudeHi2'],
        'altitudeLo1': json['altitudeLo1'] == null ? undefined : json['altitudeLo1'],
        'altitudeLo2': json['altitudeLo2'] == null ? undefined : json['altitudeLo2'],
        'movementDir': json['movementDir'] == null ? undefined : json['movementDir'],
        'movementSpd': json['movementSpd'] == null ? undefined : json['movementSpd'],
        'severity': json['severity'] == null ? undefined : json['severity'],
        'rawAirSigmet': json['rawAirSigmet'] == null ? undefined : json['rawAirSigmet'],
    };
}

export function AirSigmetGeoJSONFeaturesInnerPropertiesToJSON(json: any): AirSigmetGeoJSONFeaturesInnerProperties {
    return AirSigmetGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function AirSigmetGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: AirSigmetGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'alphaChar': value['alphaChar'],
        'seriesId': value['seriesId'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'airSigmetType': value['airSigmetType'],
        'hazard': value['hazard'],
        'altitudeHi1': value['altitudeHi1'],
        'altitudeHi2': value['altitudeHi2'],
        'altitudeLo1': value['altitudeLo1'],
        'altitudeLo2': value['altitudeLo2'],
        'movementDir': value['movementDir'],
        'movementSpd': value['movementSpd'],
        'severity': value['severity'],
        'rawAirSigmet': value['rawAirSigmet'],
    };
}

