/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirmetGeoJSONFeaturesInnerProperties
 */
export interface AirmetGeoJSONFeaturesInnerProperties {
    /**
     * Forecast zone identifier
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInnerProperties
     */
    region?: string;
    /**
     * Forecast zone name
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInnerProperties
     */
    zone?: string;
    /**
     * 
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInnerProperties
     */
    receiptTime?: string;
    /**
     * 
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInnerProperties
     */
    validTimeFrom?: string;
    /**
     * 
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInnerProperties
     */
    validTimeTo?: string;
    /**
     * Hazard type
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInnerProperties
     */
    hazard?: string;
}

/**
 * Check if a given object implements the AirmetGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfAirmetGeoJSONFeaturesInnerProperties(value: object): value is AirmetGeoJSONFeaturesInnerProperties {
    return true;
}

export function AirmetGeoJSONFeaturesInnerPropertiesFromJSON(json: any): AirmetGeoJSONFeaturesInnerProperties {
    return AirmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function AirmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirmetGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'region': json['region'] == null ? undefined : json['region'],
        'zone': json['zone'] == null ? undefined : json['zone'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
    };
}

export function AirmetGeoJSONFeaturesInnerPropertiesToJSON(json: any): AirmetGeoJSONFeaturesInnerProperties {
    return AirmetGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function AirmetGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: AirmetGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'region': value['region'],
        'zone': value['zone'],
        'receiptTime': value['receiptTime'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'hazard': value['hazard'],
    };
}

