/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirSigmetGeoJSONFeaturesInnerGeometry } from './air-sigmet-geo-json-features-inner-geometry';
import {
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './air-sigmet-geo-json-features-inner-geometry';
import type { AirmetGeoJSONFeaturesInnerProperties } from './airmet-geo-json-features-inner-properties';
import {
    AirmetGeoJSONFeaturesInnerPropertiesFromJSON,
    AirmetGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    AirmetGeoJSONFeaturesInnerPropertiesToJSON,
    AirmetGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './airmet-geo-json-features-inner-properties';

/**
 * 
 * @export
 * @interface AirmetGeoJSONFeaturesInner
 */
export interface AirmetGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof AirmetGeoJSONFeaturesInner
     */
    type?: AirmetGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AirmetGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {AirmetGeoJSONFeaturesInnerProperties}
     * @memberof AirmetGeoJSONFeaturesInner
     */
    properties?: AirmetGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerGeometry}
     * @memberof AirmetGeoJSONFeaturesInner
     */
    geometry?: AirSigmetGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const AirmetGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type AirmetGeoJSONFeaturesInnerTypeEnum = typeof AirmetGeoJSONFeaturesInnerTypeEnum[keyof typeof AirmetGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the AirmetGeoJSONFeaturesInner interface.
 */
export function instanceOfAirmetGeoJSONFeaturesInner(value: object): value is AirmetGeoJSONFeaturesInner {
    return true;
}

export function AirmetGeoJSONFeaturesInnerFromJSON(json: any): AirmetGeoJSONFeaturesInner {
    return AirmetGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function AirmetGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirmetGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : AirmetGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function AirmetGeoJSONFeaturesInnerToJSON(json: any): AirmetGeoJSONFeaturesInner {
    return AirmetGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function AirmetGeoJSONFeaturesInnerToJSONTyped(value?: AirmetGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': AirmetGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': AirSigmetGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

