/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AirmetJSONInner
 */
export interface AirmetJSONInner {
    /**
     * Forecast zone identifier
     * @type {string}
     * @memberof AirmetJSONInner
     */
    region?: string;
    /**
     * 
     * @type {string}
     * @memberof AirmetJSONInner
     */
    receiptTime?: string;
    /**
     * 
     * @type {number}
     * @memberof AirmetJSONInner
     */
    validTimeFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof AirmetJSONInner
     */
    validTimeTo?: number;
    /**
     * Hazard type
     * @type {string}
     * @memberof AirmetJSONInner
     */
    hazard?: string;
}

/**
 * Check if a given object implements the AirmetJSONInner interface.
 */
export function instanceOfAirmetJSONInner(value: object): value is AirmetJSONInner {
    return true;
}

export function AirmetJSONInnerFromJSON(json: any): AirmetJSONInner {
    return AirmetJSONInnerFromJSONTyped(json, false);
}

export function AirmetJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirmetJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'region': json['region'] == null ? undefined : json['region'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
    };
}

export function AirmetJSONInnerToJSON(json: any): AirmetJSONInner {
    return AirmetJSONInnerToJSONTyped(json, false);
}

export function AirmetJSONInnerToJSONTyped(value?: AirmetJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'region': value['region'],
        'receiptTime': value['receiptTime'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'hazard': value['hazard'],
    };
}

