/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirmetGeoJSONFeaturesInner } from './airmet-geo-json-features-inner';
import {
    AirmetGeoJSONFeaturesInnerFromJSON,
    AirmetGeoJSONFeaturesInnerFromJSONTyped,
    AirmetGeoJSONFeaturesInnerToJSON,
    AirmetGeoJSONFeaturesInnerToJSONTyped,
} from './airmet-geo-json-features-inner';

/**
 * 
 * @export
 * @interface AirmetGeoJSON
 */
export interface AirmetGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof AirmetGeoJSON
     */
    type?: AirmetGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<AirmetGeoJSONFeaturesInner>}
     * @memberof AirmetGeoJSON
     */
    features?: Array<AirmetGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const AirmetGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type AirmetGeoJSONTypeEnum = typeof AirmetGeoJSONTypeEnum[keyof typeof AirmetGeoJSONTypeEnum];


/**
 * Check if a given object implements the AirmetGeoJSON interface.
 */
export function instanceOfAirmetGeoJSON(value: object): value is AirmetGeoJSON {
    return true;
}

export function AirmetGeoJSONFromJSON(json: any): AirmetGeoJSON {
    return AirmetGeoJSONFromJSONTyped(json, false);
}

export function AirmetGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): AirmetGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(AirmetGeoJSONFeaturesInnerFromJSON)),
    };
}

export function AirmetGeoJSONToJSON(json: any): AirmetGeoJSON {
    return AirmetGeoJSONToJSONTyped(json, false);
}

export function AirmetGeoJSONToJSONTyped(value?: AirmetGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(AirmetGeoJSONFeaturesInnerToJSON)),
    };
}

