/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDataFixGet200ResponseInner
 */
export interface ApiDataFixGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiDataFixGet200ResponseInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataFixGet200ResponseInner
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiDataFixGet200ResponseInner
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDataFixGet200ResponseInner
     */
    lon?: number;
}

/**
 * Check if a given object implements the ApiDataFixGet200ResponseInner interface.
 */
export function instanceOfApiDataFixGet200ResponseInner(value: object): value is ApiDataFixGet200ResponseInner {
    return true;
}

export function ApiDataFixGet200ResponseInnerFromJSON(json: any): ApiDataFixGet200ResponseInner {
    return ApiDataFixGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiDataFixGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDataFixGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
    };
}

export function ApiDataFixGet200ResponseInnerToJSON(json: any): ApiDataFixGet200ResponseInner {
    return ApiDataFixGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiDataFixGet200ResponseInnerToJSONTyped(value?: ApiDataFixGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'lat': value['lat'],
        'lon': value['lon'],
    };
}

