/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDataNavaidGet200ResponseInner
 */
export interface ApiDataNavaidGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    country?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    lon?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    elev?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    freq?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiDataNavaidGet200ResponseInner
     */
    magDec?: string;
}

/**
 * Check if a given object implements the ApiDataNavaidGet200ResponseInner interface.
 */
export function instanceOfApiDataNavaidGet200ResponseInner(value: object): value is ApiDataNavaidGet200ResponseInner {
    return true;
}

export function ApiDataNavaidGet200ResponseInnerFromJSON(json: any): ApiDataNavaidGet200ResponseInner {
    return ApiDataNavaidGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiDataNavaidGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDataNavaidGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'name': json['name'] == null ? undefined : json['name'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'elev': json['elev'] == null ? undefined : json['elev'],
        'freq': json['freq'] == null ? undefined : json['freq'],
        'magDec': json['mag_dec'] == null ? undefined : json['mag_dec'],
    };
}

export function ApiDataNavaidGet200ResponseInnerToJSON(json: any): ApiDataNavaidGet200ResponseInner {
    return ApiDataNavaidGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiDataNavaidGet200ResponseInnerToJSONTyped(value?: ApiDataNavaidGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'name': value['name'],
        'state': value['state'],
        'country': value['country'],
        'lat': value['lat'],
        'lon': value['lon'],
        'elev': value['elev'],
        'freq': value['freq'],
        'mag_dec': value['magDec'],
    };
}

