/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiDataAirportGet200ResponseInner
 */
export interface ApiDataAirportGet200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    icaoId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    iataId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    faaId?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    lat?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    lon?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    elev?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    magdec?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    owner?: string;
    /**
     * 
     * @type {Array<any>}
     * @memberof ApiDataAirportGet200ResponseInner
     */
    runways?: Array<any>;
}

/**
 * Check if a given object implements the ApiDataAirportGet200ResponseInner interface.
 */
export function instanceOfApiDataAirportGet200ResponseInner(value: object): value is ApiDataAirportGet200ResponseInner {
    return true;
}

export function ApiDataAirportGet200ResponseInnerFromJSON(json: any): ApiDataAirportGet200ResponseInner {
    return ApiDataAirportGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiDataAirportGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiDataAirportGet200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'iataId': json['iataId'] == null ? undefined : json['iataId'],
        'faaId': json['faaId'] == null ? undefined : json['faaId'],
        'name': json['name'] == null ? undefined : json['name'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        'source': json['source'] == null ? undefined : json['source'],
        'type': json['type'] == null ? undefined : json['type'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'elev': json['elev'] == null ? undefined : json['elev'],
        'magdec': json['magdec'] == null ? undefined : json['magdec'],
        'owner': json['owner'] == null ? undefined : json['owner'],
        'runways': json['runways'] == null ? undefined : json['runways'],
    };
}

export function ApiDataAirportGet200ResponseInnerToJSON(json: any): ApiDataAirportGet200ResponseInner {
    return ApiDataAirportGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiDataAirportGet200ResponseInnerToJSONTyped(value?: ApiDataAirportGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'iataId': value['iataId'],
        'faaId': value['faaId'],
        'name': value['name'],
        'state': value['state'],
        'country': value['country'],
        'source': value['source'],
        'type': value['type'],
        'lat': value['lat'],
        'lon': value['lon'],
        'elev': value['elev'],
        'magdec': value['magdec'],
        'owner': value['owner'],
        'runways': value['runways'],
    };
}

