/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Cloud layer
 * @export
 * @interface CloudInfoInner
 */
export interface CloudInfoInner {
    /**
     * Cover coverage
     * @type {string}
     * @memberof CloudInfoInner
     */
    cover: CloudInfoInnerCoverEnum;
    /**
     * Cloud base in feet
     * @type {number}
     * @memberof CloudInfoInner
     */
    base: number;
    /**
     * Cloud top in feet
     * @type {number}
     * @memberof CloudInfoInner
     */
    top?: number;
}


/**
 * @export
 */
export const CloudInfoInnerCoverEnum = {
    Clr: 'CLR',
    Cavok: 'CAVOK',
    Few: 'FEW',
    Sct: 'SCT',
    Bkn: 'BKN',
    Ovc: 'OVC',
    Ovx: 'OVX'
} as const;
export type CloudInfoInnerCoverEnum = typeof CloudInfoInnerCoverEnum[keyof typeof CloudInfoInnerCoverEnum];


/**
 * Check if a given object implements the CloudInfoInner interface.
 */
export function instanceOfCloudInfoInner(value: object): value is CloudInfoInner {
    if (!('cover' in value) || value['cover'] === undefined) return false;
    if (!('base' in value) || value['base'] === undefined) return false;
    return true;
}

export function CloudInfoInnerFromJSON(json: any): CloudInfoInner {
    return CloudInfoInnerFromJSONTyped(json, false);
}

export function CloudInfoInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CloudInfoInner {
    if (json == null) {
        return json;
    }
    return {
        
        'cover': json['cover'],
        'base': json['base'],
        'top': json['top'] == null ? undefined : json['top'],
    };
}

export function CloudInfoInnerToJSON(json: any): CloudInfoInner {
    return CloudInfoInnerToJSONTyped(json, false);
}

export function CloudInfoInnerToJSONTyped(value?: CloudInfoInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cover': value['cover'],
        'base': value['base'],
        'top': value['top'],
    };
}

