/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CwaGeoJSONFeaturesInner } from './cwa-geo-json-features-inner';
import {
    CwaGeoJSONFeaturesInnerFromJSON,
    CwaGeoJSONFeaturesInnerFromJSONTyped,
    CwaGeoJSONFeaturesInnerToJSON,
    CwaGeoJSONFeaturesInnerToJSONTyped,
} from './cwa-geo-json-features-inner';

/**
 * 
 * @export
 * @interface CwaGeoJSON
 */
export interface CwaGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof CwaGeoJSON
     */
    type?: CwaGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<CwaGeoJSONFeaturesInner>}
     * @memberof CwaGeoJSON
     */
    features?: Array<CwaGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const CwaGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type CwaGeoJSONTypeEnum = typeof CwaGeoJSONTypeEnum[keyof typeof CwaGeoJSONTypeEnum];


/**
 * Check if a given object implements the CwaGeoJSON interface.
 */
export function instanceOfCwaGeoJSON(value: object): value is CwaGeoJSON {
    return true;
}

export function CwaGeoJSONFromJSON(json: any): CwaGeoJSON {
    return CwaGeoJSONFromJSONTyped(json, false);
}

export function CwaGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): CwaGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(CwaGeoJSONFeaturesInnerFromJSON)),
    };
}

export function CwaGeoJSONToJSON(json: any): CwaGeoJSON {
    return CwaGeoJSONToJSONTyped(json, false);
}

export function CwaGeoJSONToJSONTyped(value?: CwaGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(CwaGeoJSONFeaturesInnerToJSON)),
    };
}

