/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CwaJSONInner
 */
export interface CwaJSONInner {
    /**
     * Issuing CWSU identifier
     * @type {string}
     * @memberof CwaJSONInner
     */
    cwsu?: string;
    /**
     * Issuing CWSU name
     * @type {string}
     * @memberof CwaJSONInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CwaJSONInner
     */
    receiptTime?: string;
    /**
     * 
     * @type {number}
     * @memberof CwaJSONInner
     */
    validTimeFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof CwaJSONInner
     */
    validTimeTo?: number;
    /**
     * Hazard type
     * @type {string}
     * @memberof CwaJSONInner
     */
    hazard?: string;
    /**
     * 
     * @type {number}
     * @memberof CwaJSONInner
     */
    seriesId?: number;
    /**
     * 
     * @type {string}
     * @memberof CwaJSONInner
     */
    qualifier?: string;
    /**
     * 
     * @type {number}
     * @memberof CwaJSONInner
     */
    base?: number;
    /**
     * 
     * @type {number}
     * @memberof CwaJSONInner
     */
    top?: number;
    /**
     * 
     * @type {string}
     * @memberof CwaJSONInner
     */
    geom?: CwaJSONInnerGeomEnum;
    /**
     * 
     * @type {Array<object>}
     * @memberof CwaJSONInner
     */
    coords?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof CwaJSONInner
     */
    rawText?: string;
}


/**
 * @export
 */
export const CwaJSONInnerGeomEnum = {
    Area: 'AREA',
    Line: 'LINE'
} as const;
export type CwaJSONInnerGeomEnum = typeof CwaJSONInnerGeomEnum[keyof typeof CwaJSONInnerGeomEnum];


/**
 * Check if a given object implements the CwaJSONInner interface.
 */
export function instanceOfCwaJSONInner(value: object): value is CwaJSONInner {
    return true;
}

export function CwaJSONInnerFromJSON(json: any): CwaJSONInner {
    return CwaJSONInnerFromJSONTyped(json, false);
}

export function CwaJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CwaJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'cwsu': json['cwsu'] == null ? undefined : json['cwsu'],
        'name': json['name'] == null ? undefined : json['name'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'qualifier': json['qualifier'] == null ? undefined : json['qualifier'],
        'base': json['base'] == null ? undefined : json['base'],
        'top': json['top'] == null ? undefined : json['top'],
        'geom': json['geom'] == null ? undefined : json['geom'],
        'coords': json['coords'] == null ? undefined : json['coords'],
        'rawText': json['rawText'] == null ? undefined : json['rawText'],
    };
}

export function CwaJSONInnerToJSON(json: any): CwaJSONInner {
    return CwaJSONInnerToJSONTyped(json, false);
}

export function CwaJSONInnerToJSONTyped(value?: CwaJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cwsu': value['cwsu'],
        'name': value['name'],
        'receiptTime': value['receiptTime'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'hazard': value['hazard'],
        'seriesId': value['seriesId'],
        'qualifier': value['qualifier'],
        'base': value['base'],
        'top': value['top'],
        'geom': value['geom'],
        'coords': value['coords'],
        'rawText': value['rawText'],
    };
}

