/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirSigmetGeoJSONFeaturesInnerGeometry } from './air-sigmet-geo-json-features-inner-geometry';
import {
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './air-sigmet-geo-json-features-inner-geometry';
import type { CwaGeoJSONFeaturesInnerProperties } from './cwa-geo-json-features-inner-properties';
import {
    CwaGeoJSONFeaturesInnerPropertiesFromJSON,
    CwaGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    CwaGeoJSONFeaturesInnerPropertiesToJSON,
    CwaGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './cwa-geo-json-features-inner-properties';

/**
 * 
 * @export
 * @interface CwaGeoJSONFeaturesInner
 */
export interface CwaGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof CwaGeoJSONFeaturesInner
     */
    type?: CwaGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof CwaGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {CwaGeoJSONFeaturesInnerProperties}
     * @memberof CwaGeoJSONFeaturesInner
     */
    properties?: CwaGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerGeometry}
     * @memberof CwaGeoJSONFeaturesInner
     */
    geometry?: AirSigmetGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const CwaGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type CwaGeoJSONFeaturesInnerTypeEnum = typeof CwaGeoJSONFeaturesInnerTypeEnum[keyof typeof CwaGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the CwaGeoJSONFeaturesInner interface.
 */
export function instanceOfCwaGeoJSONFeaturesInner(value: object): value is CwaGeoJSONFeaturesInner {
    return true;
}

export function CwaGeoJSONFeaturesInnerFromJSON(json: any): CwaGeoJSONFeaturesInner {
    return CwaGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function CwaGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): CwaGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : CwaGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function CwaGeoJSONFeaturesInnerToJSON(json: any): CwaGeoJSONFeaturesInner {
    return CwaGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function CwaGeoJSONFeaturesInnerToJSONTyped(value?: CwaGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': CwaGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': AirSigmetGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

