/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CwaGeoJSONFeaturesInnerProperties
 */
export interface CwaGeoJSONFeaturesInnerProperties {
    /**
     * Issuing CWSU identifier
     * @type {string}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    cwsu?: string;
    /**
     * Issuing CWSU name
     * @type {string}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    validTimeFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    validTimeTo?: number;
    /**
     * Hazard type
     * @type {string}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    hazard?: string;
    /**
     * 
     * @type {number}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    seriesId?: number;
    /**
     * 
     * @type {string}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    qualifier?: string;
    /**
     * 
     * @type {number}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    base?: number;
    /**
     * 
     * @type {number}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    top?: number;
    /**
     * 
     * @type {string}
     * @memberof CwaGeoJSONFeaturesInnerProperties
     */
    cwaText?: string;
}

/**
 * Check if a given object implements the CwaGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfCwaGeoJSONFeaturesInnerProperties(value: object): value is CwaGeoJSONFeaturesInnerProperties {
    return true;
}

export function CwaGeoJSONFeaturesInnerPropertiesFromJSON(json: any): CwaGeoJSONFeaturesInnerProperties {
    return CwaGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function CwaGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): CwaGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'cwsu': json['cwsu'] == null ? undefined : json['cwsu'],
        'name': json['name'] == null ? undefined : json['name'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'qualifier': json['qualifier'] == null ? undefined : json['qualifier'],
        'base': json['base'] == null ? undefined : json['base'],
        'top': json['top'] == null ? undefined : json['top'],
        'cwaText': json['cwaText'] == null ? undefined : json['cwaText'],
    };
}

export function CwaGeoJSONFeaturesInnerPropertiesToJSON(json: any): CwaGeoJSONFeaturesInnerProperties {
    return CwaGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function CwaGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: CwaGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cwsu': value['cwsu'],
        'name': value['name'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'hazard': value['hazard'],
        'seriesId': value['seriesId'],
        'qualifier': value['qualifier'],
        'base': value['base'],
        'top': value['top'],
        'cwaText': value['cwaText'],
    };
}

