/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorJSON
 */
export interface ErrorJSON {
    /**
     * 
     * @type {string}
     * @memberof ErrorJSON
     */
    status?: ErrorJSONStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof ErrorJSON
     */
    error?: string;
}


/**
 * @export
 */
export const ErrorJSONStatusEnum = {
    Error: 'error'
} as const;
export type ErrorJSONStatusEnum = typeof ErrorJSONStatusEnum[keyof typeof ErrorJSONStatusEnum];


/**
 * Check if a given object implements the ErrorJSON interface.
 */
export function instanceOfErrorJSON(value: object): value is ErrorJSON {
    return true;
}

export function ErrorJSONFromJSON(json: any): ErrorJSON {
    return ErrorJSONFromJSONTyped(json, false);
}

export function ErrorJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function ErrorJSONToJSON(json: any): ErrorJSON {
    return ErrorJSONToJSONTyped(json, false);
}

export function ErrorJSONToJSONTyped(value?: ErrorJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'error': value['error'],
    };
}

