/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorXMLRequest
 */
export interface ErrorXMLRequest {
    /**
     * 
     * @type {string}
     * @memberof ErrorXMLRequest
     */
    type?: string;
}

/**
 * Check if a given object implements the ErrorXMLRequest interface.
 */
export function instanceOfErrorXMLRequest(value: object): value is ErrorXMLRequest {
    return true;
}

export function ErrorXMLRequestFromJSON(json: any): ErrorXMLRequest {
    return ErrorXMLRequestFromJSONTyped(json, false);
}

export function ErrorXMLRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorXMLRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function ErrorXMLRequestToJSON(json: any): ErrorXMLRequest {
    return ErrorXMLRequestToJSONTyped(json, false);
}

export function ErrorXMLRequestToJSONTyped(value?: ErrorXMLRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

