/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorXMLRequest } from './error-xml-request';
import {
    ErrorXMLRequestFromJSON,
    ErrorXMLRequestFromJSONTyped,
    ErrorXMLRequestToJSON,
    ErrorXMLRequestToJSONTyped,
} from './error-xml-request';

/**
 * 
 * @export
 * @interface ErrorXML
 */
export interface ErrorXML {
    /**
     * 
     * @type {number}
     * @memberof ErrorXML
     */
    requestIndex?: number;
    /**
     * 
     * @type {number}
     * @memberof ErrorXML
     */
    dataSource?: number;
    /**
     * 
     * @type {ErrorXMLRequest}
     * @memberof ErrorXML
     */
    request?: ErrorXMLRequest;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorXML
     */
    errors?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ErrorXML
     */
    warnings?: Array<string>;
}

/**
 * Check if a given object implements the ErrorXML interface.
 */
export function instanceOfErrorXML(value: object): value is ErrorXML {
    return true;
}

export function ErrorXMLFromJSON(json: any): ErrorXML {
    return ErrorXMLFromJSONTyped(json, false);
}

export function ErrorXMLFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorXML {
    if (json == null) {
        return json;
    }
    return {
        
        'requestIndex': json['request_index'] == null ? undefined : json['request_index'],
        'dataSource': json['data_source'] == null ? undefined : json['data_source'],
        'request': json['request'] == null ? undefined : ErrorXMLRequestFromJSON(json['request']),
        'errors': json['errors'] == null ? undefined : json['errors'],
        'warnings': json['warnings'] == null ? undefined : json['warnings'],
    };
}

export function ErrorXMLToJSON(json: any): ErrorXML {
    return ErrorXMLToJSONTyped(json, false);
}

export function ErrorXMLToJSONTyped(value?: ErrorXML | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_index': value['requestIndex'],
        'data_source': value['dataSource'],
        'request': ErrorXMLRequestToJSON(value['request']),
        'errors': value['errors'],
        'warnings': value['warnings'],
    };
}

