/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GairmetGeoJSONFeaturesInnerProperties
 */
export interface GairmetGeoJSONFeaturesInnerProperties {
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    tag?: string;
    /**
     * 
     * @type {number}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    forecastHour?: number;
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    receiptTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    issueTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    validTime?: string;
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    hazard?: string;
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    dueTo?: string;
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInnerProperties
     */
    product?: GairmetGeoJSONFeaturesInnerPropertiesProductEnum;
}


/**
 * @export
 */
export const GairmetGeoJSONFeaturesInnerPropertiesProductEnum = {
    Sierra: 'SIERRA',
    Tango: 'TANGO',
    Zulu: 'ZULU'
} as const;
export type GairmetGeoJSONFeaturesInnerPropertiesProductEnum = typeof GairmetGeoJSONFeaturesInnerPropertiesProductEnum[keyof typeof GairmetGeoJSONFeaturesInnerPropertiesProductEnum];


/**
 * Check if a given object implements the GairmetGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfGairmetGeoJSONFeaturesInnerProperties(value: object): value is GairmetGeoJSONFeaturesInnerProperties {
    return true;
}

export function GairmetGeoJSONFeaturesInnerPropertiesFromJSON(json: any): GairmetGeoJSONFeaturesInnerProperties {
    return GairmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function GairmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): GairmetGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : json['tag'],
        'forecastHour': json['forecastHour'] == null ? undefined : json['forecastHour'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'issueTime': json['issueTime'] == null ? undefined : json['issueTime'],
        'validTime': json['validTime'] == null ? undefined : json['validTime'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'dueTo': json['due_to'] == null ? undefined : json['due_to'],
        'product': json['product'] == null ? undefined : json['product'],
    };
}

export function GairmetGeoJSONFeaturesInnerPropertiesToJSON(json: any): GairmetGeoJSONFeaturesInnerProperties {
    return GairmetGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function GairmetGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: GairmetGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'forecastHour': value['forecastHour'],
        'receiptTime': value['receiptTime'],
        'issueTime': value['issueTime'],
        'validTime': value['validTime'],
        'hazard': value['hazard'],
        'due_to': value['dueTo'],
        'product': value['product'],
    };
}

