/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirSigmetGeoJSONFeaturesInnerGeometry } from './air-sigmet-geo-json-features-inner-geometry';
import {
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './air-sigmet-geo-json-features-inner-geometry';
import type { GairmetGeoJSONFeaturesInnerProperties } from './gairmet-geo-json-features-inner-properties';
import {
    GairmetGeoJSONFeaturesInnerPropertiesFromJSON,
    GairmetGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    GairmetGeoJSONFeaturesInnerPropertiesToJSON,
    GairmetGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './gairmet-geo-json-features-inner-properties';

/**
 * 
 * @export
 * @interface GairmetGeoJSONFeaturesInner
 */
export interface GairmetGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSONFeaturesInner
     */
    type?: GairmetGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof GairmetGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {GairmetGeoJSONFeaturesInnerProperties}
     * @memberof GairmetGeoJSONFeaturesInner
     */
    properties?: GairmetGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerGeometry}
     * @memberof GairmetGeoJSONFeaturesInner
     */
    geometry?: AirSigmetGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const GairmetGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type GairmetGeoJSONFeaturesInnerTypeEnum = typeof GairmetGeoJSONFeaturesInnerTypeEnum[keyof typeof GairmetGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the GairmetGeoJSONFeaturesInner interface.
 */
export function instanceOfGairmetGeoJSONFeaturesInner(value: object): value is GairmetGeoJSONFeaturesInner {
    return true;
}

export function GairmetGeoJSONFeaturesInnerFromJSON(json: any): GairmetGeoJSONFeaturesInner {
    return GairmetGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function GairmetGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GairmetGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : GairmetGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function GairmetGeoJSONFeaturesInnerToJSON(json: any): GairmetGeoJSONFeaturesInner {
    return GairmetGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function GairmetGeoJSONFeaturesInnerToJSONTyped(value?: GairmetGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': GairmetGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': AirSigmetGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

