/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GairmetGeoJSONFeaturesInner } from './gairmet-geo-json-features-inner';
import {
    GairmetGeoJSONFeaturesInnerFromJSON,
    GairmetGeoJSONFeaturesInnerFromJSONTyped,
    GairmetGeoJSONFeaturesInnerToJSON,
    GairmetGeoJSONFeaturesInnerToJSONTyped,
} from './gairmet-geo-json-features-inner';

/**
 * 
 * @export
 * @interface GairmetGeoJSON
 */
export interface GairmetGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof GairmetGeoJSON
     */
    type?: GairmetGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<GairmetGeoJSONFeaturesInner>}
     * @memberof GairmetGeoJSON
     */
    features?: Array<GairmetGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const GairmetGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type GairmetGeoJSONTypeEnum = typeof GairmetGeoJSONTypeEnum[keyof typeof GairmetGeoJSONTypeEnum];


/**
 * Check if a given object implements the GairmetGeoJSON interface.
 */
export function instanceOfGairmetGeoJSON(value: object): value is GairmetGeoJSON {
    return true;
}

export function GairmetGeoJSONFromJSON(json: any): GairmetGeoJSON {
    return GairmetGeoJSONFromJSONTyped(json, false);
}

export function GairmetGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): GairmetGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(GairmetGeoJSONFeaturesInnerFromJSON)),
    };
}

export function GairmetGeoJSONToJSON(json: any): GairmetGeoJSON {
    return GairmetGeoJSONToJSONTyped(json, false);
}

export function GairmetGeoJSONToJSONTyped(value?: GairmetGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(GairmetGeoJSONFeaturesInnerToJSON)),
    };
}

