/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GairmetJSONInner
 */
export interface GairmetJSONInner {
    /**
     * Forecast component tag
     * @type {string}
     * @memberof GairmetJSONInner
     */
    tag?: string;
    /**
     * 
     * @type {number}
     * @memberof GairmetJSONInner
     */
    forecastHour?: number;
    /**
     * 
     * @type {string}
     * @memberof GairmetJSONInner
     */
    validTime?: string;
    /**
     * Hazard type
     * @type {string}
     * @memberof GairmetJSONInner
     */
    hazard?: string;
    /**
     * 
     * @type {string}
     * @memberof GairmetJSONInner
     */
    geometryType?: GairmetJSONInnerGeometryTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof GairmetJSONInner
     */
    latlonpairs?: number;
    /**
     * 
     * @type {string}
     * @memberof GairmetJSONInner
     */
    dueTo?: string;
    /**
     * 
     * @type {number}
     * @memberof GairmetJSONInner
     */
    receiptTime?: number;
    /**
     * 
     * @type {number}
     * @memberof GairmetJSONInner
     */
    issueTime?: number;
    /**
     * 
     * @type {number}
     * @memberof GairmetJSONInner
     */
    expireTime?: number;
    /**
     * 
     * @type {string}
     * @memberof GairmetJSONInner
     */
    product?: GairmetJSONInnerProductEnum;
    /**
     * 
     * @type {Array<object>}
     * @memberof GairmetJSONInner
     */
    coords?: Array<object>;
}


/**
 * @export
 */
export const GairmetJSONInnerGeometryTypeEnum = {
    Area: 'AREA',
    Line: 'LINE'
} as const;
export type GairmetJSONInnerGeometryTypeEnum = typeof GairmetJSONInnerGeometryTypeEnum[keyof typeof GairmetJSONInnerGeometryTypeEnum];

/**
 * @export
 */
export const GairmetJSONInnerProductEnum = {
    Sierra: 'SIERRA',
    Tango: 'TANGO',
    Zulu: 'ZULU'
} as const;
export type GairmetJSONInnerProductEnum = typeof GairmetJSONInnerProductEnum[keyof typeof GairmetJSONInnerProductEnum];


/**
 * Check if a given object implements the GairmetJSONInner interface.
 */
export function instanceOfGairmetJSONInner(value: object): value is GairmetJSONInner {
    return true;
}

export function GairmetJSONInnerFromJSON(json: any): GairmetJSONInner {
    return GairmetJSONInnerFromJSONTyped(json, false);
}

export function GairmetJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GairmetJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'tag': json['tag'] == null ? undefined : json['tag'],
        'forecastHour': json['forecastHour'] == null ? undefined : json['forecastHour'],
        'validTime': json['validTime'] == null ? undefined : json['validTime'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'geometryType': json['geometryType'] == null ? undefined : json['geometryType'],
        'latlonpairs': json['latlonpairs'] == null ? undefined : json['latlonpairs'],
        'dueTo': json['due_to'] == null ? undefined : json['due_to'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'issueTime': json['issueTime'] == null ? undefined : json['issueTime'],
        'expireTime': json['expireTime'] == null ? undefined : json['expireTime'],
        'product': json['product'] == null ? undefined : json['product'],
        'coords': json['coords'] == null ? undefined : json['coords'],
    };
}

export function GairmetJSONInnerToJSON(json: any): GairmetJSONInner {
    return GairmetJSONInnerToJSONTyped(json, false);
}

export function GairmetJSONInnerToJSONTyped(value?: GairmetJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tag': value['tag'],
        'forecastHour': value['forecastHour'],
        'validTime': value['validTime'],
        'hazard': value['hazard'],
        'geometryType': value['geometryType'],
        'latlonpairs': value['latlonpairs'],
        'due_to': value['dueTo'],
        'receiptTime': value['receiptTime'],
        'issueTime': value['issueTime'],
        'expireTime': value['expireTime'],
        'product': value['product'],
        'coords': value['coords'],
    };
}

