/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ISigmetGeoJSONFeaturesInnerProperties
 */
export interface ISigmetGeoJSONFeaturesInnerProperties {
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    icaoId?: string;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    firId?: string;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    firName?: string;
    /**
     * 
     * @type {number}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    validTimeFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    validTimeTo?: number;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    seriesId?: string;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    hazard?: string;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    qualifier?: string;
    /**
     * 
     * @type {number}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    base?: number;
    /**
     * 
     * @type {number}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    top?: number;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    dir?: string;
    /**
     * 
     * @type {number}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    spd?: number;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    chng?: string;
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInnerProperties
     */
    rawSigmet?: string;
}

/**
 * Check if a given object implements the ISigmetGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfISigmetGeoJSONFeaturesInnerProperties(value: object): value is ISigmetGeoJSONFeaturesInnerProperties {
    return true;
}

export function ISigmetGeoJSONFeaturesInnerPropertiesFromJSON(json: any): ISigmetGeoJSONFeaturesInnerProperties {
    return ISigmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function ISigmetGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISigmetGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'firId': json['firId'] == null ? undefined : json['firId'],
        'firName': json['firName'] == null ? undefined : json['firName'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'qualifier': json['qualifier'] == null ? undefined : json['qualifier'],
        'base': json['base'] == null ? undefined : json['base'],
        'top': json['top'] == null ? undefined : json['top'],
        'dir': json['dir'] == null ? undefined : json['dir'],
        'spd': json['spd'] == null ? undefined : json['spd'],
        'chng': json['chng'] == null ? undefined : json['chng'],
        'rawSigmet': json['rawSigmet'] == null ? undefined : json['rawSigmet'],
    };
}

export function ISigmetGeoJSONFeaturesInnerPropertiesToJSON(json: any): ISigmetGeoJSONFeaturesInnerProperties {
    return ISigmetGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function ISigmetGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: ISigmetGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'firId': value['firId'],
        'firName': value['firName'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'seriesId': value['seriesId'],
        'hazard': value['hazard'],
        'qualifier': value['qualifier'],
        'base': value['base'],
        'top': value['top'],
        'dir': value['dir'],
        'spd': value['spd'],
        'chng': value['chng'],
        'rawSigmet': value['rawSigmet'],
    };
}

