/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ISigmetJSONInner
 */
export interface ISigmetJSONInner {
    /**
     * Issuing office identifier
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    icaoId?: string;
    /**
     * Flight Information Region identifier
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    firId?: string;
    /**
     * Flight Information Region name
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    firName?: string;
    /**
     * Time received by AWC
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    receiptTime?: string;
    /**
     * 
     * @type {number}
     * @memberof ISigmetJSONInner
     */
    validTimeFrom?: number;
    /**
     * 
     * @type {number}
     * @memberof ISigmetJSONInner
     */
    validTimeTo?: number;
    /**
     * 
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    seriesId?: string;
    /**
     * Hazard type
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    hazard?: string;
    /**
     * 
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    qualifier?: string;
    /**
     * 
     * @type {number}
     * @memberof ISigmetJSONInner
     */
    base?: number;
    /**
     * 
     * @type {number}
     * @memberof ISigmetJSONInner
     */
    top?: number;
    /**
     * Geometry type
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    geom?: ISigmetJSONInnerGeomEnum;
    /**
     * 
     * @type {Array<object>}
     * @memberof ISigmetJSONInner
     */
    coords?: Array<object>;
    /**
     * 
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    dir?: string;
    /**
     * 
     * @type {number}
     * @memberof ISigmetJSONInner
     */
    spd?: number;
    /**
     * 
     * @type {string}
     * @memberof ISigmetJSONInner
     */
    chng?: string;
}


/**
 * @export
 */
export const ISigmetJSONInnerGeomEnum = {
    Area: 'AREA',
    Line: 'LINE'
} as const;
export type ISigmetJSONInnerGeomEnum = typeof ISigmetJSONInnerGeomEnum[keyof typeof ISigmetJSONInnerGeomEnum];


/**
 * Check if a given object implements the ISigmetJSONInner interface.
 */
export function instanceOfISigmetJSONInner(value: object): value is ISigmetJSONInner {
    return true;
}

export function ISigmetJSONInnerFromJSON(json: any): ISigmetJSONInner {
    return ISigmetJSONInnerFromJSONTyped(json, false);
}

export function ISigmetJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISigmetJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'firId': json['firId'] == null ? undefined : json['firId'],
        'firName': json['firName'] == null ? undefined : json['firName'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'seriesId': json['seriesId'] == null ? undefined : json['seriesId'],
        'hazard': json['hazard'] == null ? undefined : json['hazard'],
        'qualifier': json['qualifier'] == null ? undefined : json['qualifier'],
        'base': json['base'] == null ? undefined : json['base'],
        'top': json['top'] == null ? undefined : json['top'],
        'geom': json['geom'] == null ? undefined : json['geom'],
        'coords': json['coords'] == null ? undefined : json['coords'],
        'dir': json['dir'] == null ? undefined : json['dir'],
        'spd': json['spd'] == null ? undefined : json['spd'],
        'chng': json['chng'] == null ? undefined : json['chng'],
    };
}

export function ISigmetJSONInnerToJSON(json: any): ISigmetJSONInner {
    return ISigmetJSONInnerToJSONTyped(json, false);
}

export function ISigmetJSONInnerToJSONTyped(value?: ISigmetJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'firId': value['firId'],
        'firName': value['firName'],
        'receiptTime': value['receiptTime'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'seriesId': value['seriesId'],
        'hazard': value['hazard'],
        'qualifier': value['qualifier'],
        'base': value['base'],
        'top': value['top'],
        'geom': value['geom'],
        'coords': value['coords'],
        'dir': value['dir'],
        'spd': value['spd'],
        'chng': value['chng'],
    };
}

