/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ISigmetGeoJSONFeaturesInner } from './i-sigmet-geo-json-features-inner';
import {
    ISigmetGeoJSONFeaturesInnerFromJSON,
    ISigmetGeoJSONFeaturesInnerFromJSONTyped,
    ISigmetGeoJSONFeaturesInnerToJSON,
    ISigmetGeoJSONFeaturesInnerToJSONTyped,
} from './i-sigmet-geo-json-features-inner';

/**
 * 
 * @export
 * @interface ISigmetGeoJSON
 */
export interface ISigmetGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSON
     */
    type?: ISigmetGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<ISigmetGeoJSONFeaturesInner>}
     * @memberof ISigmetGeoJSON
     */
    features?: Array<ISigmetGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const ISigmetGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type ISigmetGeoJSONTypeEnum = typeof ISigmetGeoJSONTypeEnum[keyof typeof ISigmetGeoJSONTypeEnum];


/**
 * Check if a given object implements the ISigmetGeoJSON interface.
 */
export function instanceOfISigmetGeoJSON(value: object): value is ISigmetGeoJSON {
    return true;
}

export function ISigmetGeoJSONFromJSON(json: any): ISigmetGeoJSON {
    return ISigmetGeoJSONFromJSONTyped(json, false);
}

export function ISigmetGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISigmetGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(ISigmetGeoJSONFeaturesInnerFromJSON)),
    };
}

export function ISigmetGeoJSONToJSON(json: any): ISigmetGeoJSON {
    return ISigmetGeoJSONToJSONTyped(json, false);
}

export function ISigmetGeoJSONToJSONTyped(value?: ISigmetGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(ISigmetGeoJSONFeaturesInnerToJSON)),
    };
}

