/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AirSigmetGeoJSONFeaturesInnerGeometry } from './air-sigmet-geo-json-features-inner-geometry';
import {
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './air-sigmet-geo-json-features-inner-geometry';
import type { ISigmetGeoJSONFeaturesInnerProperties } from './i-sigmet-geo-json-features-inner-properties';
import {
    ISigmetGeoJSONFeaturesInnerPropertiesFromJSON,
    ISigmetGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    ISigmetGeoJSONFeaturesInnerPropertiesToJSON,
    ISigmetGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './i-sigmet-geo-json-features-inner-properties';

/**
 * 
 * @export
 * @interface ISigmetGeoJSONFeaturesInner
 */
export interface ISigmetGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof ISigmetGeoJSONFeaturesInner
     */
    type?: ISigmetGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof ISigmetGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {ISigmetGeoJSONFeaturesInnerProperties}
     * @memberof ISigmetGeoJSONFeaturesInner
     */
    properties?: ISigmetGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerGeometry}
     * @memberof ISigmetGeoJSONFeaturesInner
     */
    geometry?: AirSigmetGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const ISigmetGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type ISigmetGeoJSONFeaturesInnerTypeEnum = typeof ISigmetGeoJSONFeaturesInnerTypeEnum[keyof typeof ISigmetGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the ISigmetGeoJSONFeaturesInner interface.
 */
export function instanceOfISigmetGeoJSONFeaturesInner(value: object): value is ISigmetGeoJSONFeaturesInner {
    return true;
}

export function ISigmetGeoJSONFeaturesInnerFromJSON(json: any): ISigmetGeoJSONFeaturesInner {
    return ISigmetGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function ISigmetGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ISigmetGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : ISigmetGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function ISigmetGeoJSONFeaturesInnerToJSON(json: any): ISigmetGeoJSONFeaturesInner {
    return ISigmetGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function ISigmetGeoJSONFeaturesInnerToJSONTyped(value?: ISigmetGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': ISigmetGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': AirSigmetGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

