/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * 
     * @type {string}
     * @memberof InlineObject
     */
    status?: InlineObjectStatusEnum;
}


/**
 * @export
 */
export const InlineObjectStatusEnum = {
    Success: 'success'
} as const;
export type InlineObjectStatusEnum = typeof InlineObjectStatusEnum[keyof typeof InlineObjectStatusEnum];


/**
 * Check if a given object implements the InlineObject interface.
 */
export function instanceOfInlineObject(value: object): value is InlineObject {
    return true;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function InlineObjectToJSON(json: any): InlineObject {
    return InlineObjectToJSONTyped(json, false);
}

export function InlineObjectToJSONTyped(value?: InlineObject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

