/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARpropertiesVisib } from './meta-rproperties-visib';
import {
    METARpropertiesVisibFromJSON,
    METARpropertiesVisibFromJSONTyped,
    METARpropertiesVisibToJSON,
    METARpropertiesVisibToJSONTyped,
} from './meta-rproperties-visib';
import type { METARpropertiesWdir } from './meta-rproperties-wdir';
import {
    METARpropertiesWdirFromJSON,
    METARpropertiesWdirFromJSONTyped,
    METARpropertiesWdirToJSON,
    METARpropertiesWdirToJSONTyped,
} from './meta-rproperties-wdir';
import type { CloudInfoInner } from './cloud-info-inner';
import {
    CloudInfoInnerFromJSON,
    CloudInfoInnerFromJSONTyped,
    CloudInfoInnerToJSON,
    CloudInfoInnerToJSONTyped,
} from './cloud-info-inner';

/**
 * 
 * @export
 * @interface METARproperties
 */
export interface METARproperties {
    /**
     * ICAO identifier
     * @type {string}
     * @memberof METARproperties
     */
    icaoId?: string;
    /**
     * The time the observation was received (yyyy-mm-dd hh:mm:ss.sssZ)
     * @type {string}
     * @memberof METARproperties
     */
    receiptTime?: string;
    /**
     * The observation time (UNIX timestamp)
     * @type {number}
     * @memberof METARproperties
     */
    obsTime?: number;
    /**
     * The time of the report (yyyy-mm-dd hh:mm:ss.sssZ)
     * @type {string}
     * @memberof METARproperties
     */
    reportTime?: string;
    /**
     * Temperature in Celsius
     * @type {number}
     * @memberof METARproperties
     */
    temp?: number;
    /**
     * Dewpoint temperature in Celsius
     * @type {number}
     * @memberof METARproperties
     */
    dewp?: number;
    /**
     * 
     * @type {METARpropertiesWdir}
     * @memberof METARproperties
     */
    wdir?: METARpropertiesWdir;
    /**
     * Wind speed in knots
     * @type {number}
     * @memberof METARproperties
     */
    wspd?: number;
    /**
     * Wind gusts in knots
     * @type {number}
     * @memberof METARproperties
     */
    wgst?: number;
    /**
     * 
     * @type {METARpropertiesVisib}
     * @memberof METARproperties
     */
    visib?: METARpropertiesVisib;
    /**
     * Altimeter setting in hectopascals
     * @type {number}
     * @memberof METARproperties
     */
    altim?: number;
    /**
     * Sea level pressure in hectopascals
     * @type {number}
     * @memberof METARproperties
     */
    slp?: number;
    /**
     * Encoded present weather string
     * @type {string}
     * @memberof METARproperties
     */
    wxString?: string;
    /**
     * Pressure tendency over last 3 hours in hectopascals
     * @type {number}
     * @memberof METARproperties
     */
    presTend?: number;
    /**
     * Maximum temperature over last 6 hours in Celsius
     * @type {number}
     * @memberof METARproperties
     */
    maxT?: number;
    /**
     * Minimum temperature over last 6 hours in Celsius
     * @type {number}
     * @memberof METARproperties
     */
    minT?: number;
    /**
     * Maximum temperature over last 24 hours in Celsius
     * @type {number}
     * @memberof METARproperties
     */
    maxT24?: number;
    /**
     * Minimum temperature over last 24 hours in Celsius
     * @type {number}
     * @memberof METARproperties
     */
    minT24?: number;
    /**
     * Precipitation over last hour in inches
     * @type {number}
     * @memberof METARproperties
     */
    precip?: number;
    /**
     * Precipitation over last 3 hours in inches
     * @type {number}
     * @memberof METARproperties
     */
    pcp3hr?: number;
    /**
     * Precipitation over last 6 hours in inches
     * @type {number}
     * @memberof METARproperties
     */
    pcp6hr?: number;
    /**
     * Precipitation over last 24 hours in inches
     * @type {number}
     * @memberof METARproperties
     */
    pcp24hr?: number;
    /**
     * Snow depth in inches
     * @type {number}
     * @memberof METARproperties
     */
    snow?: number;
    /**
     * Vertical visibility in feet
     * @type {number}
     * @memberof METARproperties
     */
    vertVis?: number;
    /**
     * Type of encoding
     * @type {string}
     * @memberof METARproperties
     */
    metarType?: METARpropertiesMetarTypeEnum;
    /**
     * Raw text of observation
     * @type {string}
     * @memberof METARproperties
     */
    rawOb?: string;
    /**
     * Latitude of site in degrees
     * @type {number}
     * @memberof METARproperties
     */
    lat?: number;
    /**
     * Longitude of site in degrees
     * @type {number}
     * @memberof METARproperties
     */
    lon?: number;
    /**
     * Elevation of site in meters
     * @type {number}
     * @memberof METARproperties
     */
    elev?: number;
    /**
     * Full name of the site
     * @type {string}
     * @memberof METARproperties
     */
    name?: string;
    /**
     * Clouds
     * @type {Array<CloudInfoInner>}
     * @memberof METARproperties
     */
    clouds?: Array<CloudInfoInner>;
    /**
     * Flight category restriction
     * @type {string}
     * @memberof METARproperties
     */
    fltCat?: string;
}


/**
 * @export
 */
export const METARpropertiesMetarTypeEnum = {
    Metar: 'METAR',
    Speci: 'SPECI',
    Synop: 'SYNOP',
    Buoy: 'BUOY',
    Cman: 'CMAN'
} as const;
export type METARpropertiesMetarTypeEnum = typeof METARpropertiesMetarTypeEnum[keyof typeof METARpropertiesMetarTypeEnum];


/**
 * Check if a given object implements the METARproperties interface.
 */
export function instanceOfMETARproperties(value: object): value is METARproperties {
    return true;
}

export function METARpropertiesFromJSON(json: any): METARproperties {
    return METARpropertiesFromJSONTyped(json, false);
}

export function METARpropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARproperties {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'obsTime': json['obsTime'] == null ? undefined : json['obsTime'],
        'reportTime': json['reportTime'] == null ? undefined : json['reportTime'],
        'temp': json['temp'] == null ? undefined : json['temp'],
        'dewp': json['dewp'] == null ? undefined : json['dewp'],
        'wdir': json['wdir'] == null ? undefined : METARpropertiesWdirFromJSON(json['wdir']),
        'wspd': json['wspd'] == null ? undefined : json['wspd'],
        'wgst': json['wgst'] == null ? undefined : json['wgst'],
        'visib': json['visib'] == null ? undefined : METARpropertiesVisibFromJSON(json['visib']),
        'altim': json['altim'] == null ? undefined : json['altim'],
        'slp': json['slp'] == null ? undefined : json['slp'],
        'wxString': json['wxString'] == null ? undefined : json['wxString'],
        'presTend': json['presTend'] == null ? undefined : json['presTend'],
        'maxT': json['maxT'] == null ? undefined : json['maxT'],
        'minT': json['minT'] == null ? undefined : json['minT'],
        'maxT24': json['maxT24'] == null ? undefined : json['maxT24'],
        'minT24': json['minT24'] == null ? undefined : json['minT24'],
        'precip': json['precip'] == null ? undefined : json['precip'],
        'pcp3hr': json['pcp3hr'] == null ? undefined : json['pcp3hr'],
        'pcp6hr': json['pcp6hr'] == null ? undefined : json['pcp6hr'],
        'pcp24hr': json['pcp24hr'] == null ? undefined : json['pcp24hr'],
        'snow': json['snow'] == null ? undefined : json['snow'],
        'vertVis': json['vertVis'] == null ? undefined : json['vertVis'],
        'metarType': json['metarType'] == null ? undefined : json['metarType'],
        'rawOb': json['rawOb'] == null ? undefined : json['rawOb'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'elev': json['elev'] == null ? undefined : json['elev'],
        'name': json['name'] == null ? undefined : json['name'],
        'clouds': json['clouds'] == null ? undefined : ((json['clouds'] as Array<any>).map(CloudInfoInnerFromJSON)),
        'fltCat': json['fltCat'] == null ? undefined : json['fltCat'],
    };
}

export function METARpropertiesToJSON(json: any): METARproperties {
    return METARpropertiesToJSONTyped(json, false);
}

export function METARpropertiesToJSONTyped(value?: METARproperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'receiptTime': value['receiptTime'],
        'obsTime': value['obsTime'],
        'reportTime': value['reportTime'],
        'temp': value['temp'],
        'dewp': value['dewp'],
        'wdir': METARpropertiesWdirToJSON(value['wdir']),
        'wspd': value['wspd'],
        'wgst': value['wgst'],
        'visib': METARpropertiesVisibToJSON(value['visib']),
        'altim': value['altim'],
        'slp': value['slp'],
        'wxString': value['wxString'],
        'presTend': value['presTend'],
        'maxT': value['maxT'],
        'minT': value['minT'],
        'maxT24': value['maxT24'],
        'minT24': value['minT24'],
        'precip': value['precip'],
        'pcp3hr': value['pcp3hr'],
        'pcp6hr': value['pcp6hr'],
        'pcp24hr': value['pcp24hr'],
        'snow': value['snow'],
        'vertVis': value['vertVis'],
        'metarType': value['metarType'],
        'rawOb': value['rawOb'],
        'lat': value['lat'],
        'lon': value['lon'],
        'elev': value['elev'],
        'name': value['name'],
        'clouds': value['clouds'] == null ? undefined : ((value['clouds'] as Array<any>).map(CloudInfoInnerToJSON)),
        'fltCat': value['fltCat'],
    };
}

