/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface METARXMLRequest
 */
export interface METARXMLRequest {
    /**
     * 
     * @type {string}
     * @memberof METARXMLRequest
     */
    type?: METARXMLRequestTypeEnum;
}


/**
 * @export
 */
export const METARXMLRequestTypeEnum = {
    Retrieve: 'retrieve'
} as const;
export type METARXMLRequestTypeEnum = typeof METARXMLRequestTypeEnum[keyof typeof METARXMLRequestTypeEnum];


/**
 * Check if a given object implements the METARXMLRequest interface.
 */
export function instanceOfMETARXMLRequest(value: object): value is METARXMLRequest {
    return true;
}

export function METARXMLRequestFromJSON(json: any): METARXMLRequest {
    return METARXMLRequestFromJSONTyped(json, false);
}

export function METARXMLRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARXMLRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function METARXMLRequestToJSON(json: any): METARXMLRequest {
    return METARXMLRequestToJSONTyped(json, false);
}

export function METARXMLRequestToJSONTyped(value?: METARXMLRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

