/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface METARXMLDataInnerQualityControlFlags
 */
export interface METARXMLDataInnerQualityControlFlags {
    /**
     * 
     * @type {boolean}
     * @memberof METARXMLDataInnerQualityControlFlags
     */
    autoStation?: boolean;
}

/**
 * Check if a given object implements the METARXMLDataInnerQualityControlFlags interface.
 */
export function instanceOfMETARXMLDataInnerQualityControlFlags(value: object): value is METARXMLDataInnerQualityControlFlags {
    return true;
}

export function METARXMLDataInnerQualityControlFlagsFromJSON(json: any): METARXMLDataInnerQualityControlFlags {
    return METARXMLDataInnerQualityControlFlagsFromJSONTyped(json, false);
}

export function METARXMLDataInnerQualityControlFlagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARXMLDataInnerQualityControlFlags {
    if (json == null) {
        return json;
    }
    return {
        
        'autoStation': json['auto_station'] == null ? undefined : json['auto_station'],
    };
}

export function METARXMLDataInnerQualityControlFlagsToJSON(json: any): METARXMLDataInnerQualityControlFlags {
    return METARXMLDataInnerQualityControlFlagsToJSONTyped(json, false);
}

export function METARXMLDataInnerQualityControlFlagsToJSONTyped(value?: METARXMLDataInnerQualityControlFlags | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'auto_station': value['autoStation'],
    };
}

