/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Wind direction in degrees or VRB for variable winds
 * @export
 * @interface METARpropertiesWdir
 */
export interface METARpropertiesWdir {
}

/**
 * Check if a given object implements the METARpropertiesWdir interface.
 */
export function instanceOfMETARpropertiesWdir(value: object): value is METARpropertiesWdir {
    return true;
}

export function METARpropertiesWdirFromJSON(json: any): METARpropertiesWdir {
    return METARpropertiesWdirFromJSONTyped(json, false);
}

export function METARpropertiesWdirFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARpropertiesWdir {
    return json;
}

export function METARpropertiesWdirToJSON(json: any): METARpropertiesWdir {
    return METARpropertiesWdirToJSONTyped(json, false);
}

export function METARpropertiesWdirToJSONTyped(value?: METARpropertiesWdir | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

