/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Visibility in statute miles, 10+ is greater than 10 sm
 * @export
 * @interface METARpropertiesVisib
 */
export interface METARpropertiesVisib {
}

/**
 * Check if a given object implements the METARpropertiesVisib interface.
 */
export function instanceOfMETARpropertiesVisib(value: object): value is METARpropertiesVisib {
    return true;
}

export function METARpropertiesVisibFromJSON(json: any): METARpropertiesVisib {
    return METARpropertiesVisibFromJSONTyped(json, false);
}

export function METARpropertiesVisibFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARpropertiesVisib {
    return json;
}

export function METARpropertiesVisibToJSON(json: any): METARpropertiesVisib {
    return METARpropertiesVisibToJSONTyped(json, false);
}

export function METARpropertiesVisibToJSONTyped(value?: METARpropertiesVisib | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

