/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARGeoJSONFeaturesInnerGeometry } from './metar-geo-json-features-inner-geometry';
import {
    METARGeoJSONFeaturesInnerGeometryFromJSON,
    METARGeoJSONFeaturesInnerGeometryFromJSONTyped,
    METARGeoJSONFeaturesInnerGeometryToJSON,
    METARGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './metar-geo-json-features-inner-geometry';
import type { METARproperties } from './meta-rproperties';
import {
    METARpropertiesFromJSON,
    METARpropertiesFromJSONTyped,
    METARpropertiesToJSON,
    METARpropertiesToJSONTyped,
} from './meta-rproperties';

/**
 * 
 * @export
 * @interface METARGeoJSONFeaturesInner
 */
export interface METARGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof METARGeoJSONFeaturesInner
     */
    type?: METARGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof METARGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {METARproperties}
     * @memberof METARGeoJSONFeaturesInner
     */
    properties?: METARproperties;
    /**
     * 
     * @type {METARGeoJSONFeaturesInnerGeometry}
     * @memberof METARGeoJSONFeaturesInner
     */
    geometry?: METARGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const METARGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type METARGeoJSONFeaturesInnerTypeEnum = typeof METARGeoJSONFeaturesInnerTypeEnum[keyof typeof METARGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the METARGeoJSONFeaturesInner interface.
 */
export function instanceOfMETARGeoJSONFeaturesInner(value: object): value is METARGeoJSONFeaturesInner {
    return true;
}

export function METARGeoJSONFeaturesInnerFromJSON(json: any): METARGeoJSONFeaturesInner {
    return METARGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function METARGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : METARpropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : METARGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function METARGeoJSONFeaturesInnerToJSON(json: any): METARGeoJSONFeaturesInner {
    return METARGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function METARGeoJSONFeaturesInnerToJSONTyped(value?: METARGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': METARpropertiesToJSON(value['properties']),
        'geometry': METARGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

