/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARpropertiesVisib } from './meta-rproperties-visib';
import {
    METARpropertiesVisibFromJSON,
    METARpropertiesVisibFromJSONTyped,
    METARpropertiesVisibToJSON,
    METARpropertiesVisibToJSONTyped,
} from './meta-rproperties-visib';
import type { METARpropertiesWdir } from './meta-rproperties-wdir';
import {
    METARpropertiesWdirFromJSON,
    METARpropertiesWdirFromJSONTyped,
    METARpropertiesWdirToJSON,
    METARpropertiesWdirToJSONTyped,
} from './meta-rproperties-wdir';
import type { METARXMLDataInnerQualityControlFlags } from './metarxml-data-inner-quality-control-flags';
import {
    METARXMLDataInnerQualityControlFlagsFromJSON,
    METARXMLDataInnerQualityControlFlagsFromJSONTyped,
    METARXMLDataInnerQualityControlFlagsToJSON,
    METARXMLDataInnerQualityControlFlagsToJSONTyped,
} from './metarxml-data-inner-quality-control-flags';

/**
 * 
 * @export
 * @interface METARXMLDataInner
 */
export interface METARXMLDataInner {
    /**
     * 
     * @type {string}
     * @memberof METARXMLDataInner
     */
    rawText?: string;
    /**
     * Station identifier
     * @type {string}
     * @memberof METARXMLDataInner
     */
    stationId?: string;
    /**
     * The observation time
     * @type {string}
     * @memberof METARXMLDataInner
     */
    observationTime?: string;
    /**
     * Latitude of site in degrees
     * @type {number}
     * @memberof METARXMLDataInner
     */
    latitude?: number;
    /**
     * Longitude of site in degrees
     * @type {number}
     * @memberof METARXMLDataInner
     */
    longitude?: number;
    /**
     * Temperature in Celsius
     * @type {number}
     * @memberof METARXMLDataInner
     */
    tempC?: number;
    /**
     * Dewpoint temperature in Celsius
     * @type {number}
     * @memberof METARXMLDataInner
     */
    dewpointC?: number;
    /**
     * 
     * @type {METARpropertiesWdir}
     * @memberof METARXMLDataInner
     */
    windDirDegrees?: METARpropertiesWdir;
    /**
     * Wind speed in knots
     * @type {number}
     * @memberof METARXMLDataInner
     */
    windSpeedKt?: number;
    /**
     * 
     * @type {METARpropertiesVisib}
     * @memberof METARXMLDataInner
     */
    visibilityStatuteMi?: METARpropertiesVisib;
    /**
     * Altimeter setting in inches of mercury
     * @type {number}
     * @memberof METARXMLDataInner
     */
    altimInHg?: number;
    /**
     * Mean sea level pressure in mb (hPa)
     * @type {number}
     * @memberof METARXMLDataInner
     */
    seaLevelPressureMb?: number;
    /**
     * 
     * @type {METARXMLDataInnerQualityControlFlags}
     * @memberof METARXMLDataInner
     */
    qualityControlFlags?: METARXMLDataInnerQualityControlFlags;
    /**
     * 
     * @type {string}
     * @memberof METARXMLDataInner
     */
    flightCategory?: string;
    /**
     * 
     * @type {string}
     * @memberof METARXMLDataInner
     */
    metarType?: string;
    /**
     * 
     * @type {number}
     * @memberof METARXMLDataInner
     */
    elevationM?: number;
}

/**
 * Check if a given object implements the METARXMLDataInner interface.
 */
export function instanceOfMETARXMLDataInner(value: object): value is METARXMLDataInner {
    return true;
}

export function METARXMLDataInnerFromJSON(json: any): METARXMLDataInner {
    return METARXMLDataInnerFromJSONTyped(json, false);
}

export function METARXMLDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARXMLDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'rawText': json['raw_text'] == null ? undefined : json['raw_text'],
        'stationId': json['station_id'] == null ? undefined : json['station_id'],
        'observationTime': json['observation_time'] == null ? undefined : json['observation_time'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'tempC': json['temp_c'] == null ? undefined : json['temp_c'],
        'dewpointC': json['dewpoint_c'] == null ? undefined : json['dewpoint_c'],
        'windDirDegrees': json['wind_dir_degrees'] == null ? undefined : METARpropertiesWdirFromJSON(json['wind_dir_degrees']),
        'windSpeedKt': json['wind_speed_kt'] == null ? undefined : json['wind_speed_kt'],
        'visibilityStatuteMi': json['visibility_statute_mi'] == null ? undefined : METARpropertiesVisibFromJSON(json['visibility_statute_mi']),
        'altimInHg': json['altim_in_hg'] == null ? undefined : json['altim_in_hg'],
        'seaLevelPressureMb': json['sea_level_pressure_mb'] == null ? undefined : json['sea_level_pressure_mb'],
        'qualityControlFlags': json['quality_control_flags'] == null ? undefined : METARXMLDataInnerQualityControlFlagsFromJSON(json['quality_control_flags']),
        'flightCategory': json['flight_category'] == null ? undefined : json['flight_category'],
        'metarType': json['metar_type'] == null ? undefined : json['metar_type'],
        'elevationM': json['elevation_m'] == null ? undefined : json['elevation_m'],
    };
}

export function METARXMLDataInnerToJSON(json: any): METARXMLDataInner {
    return METARXMLDataInnerToJSONTyped(json, false);
}

export function METARXMLDataInnerToJSONTyped(value?: METARXMLDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'raw_text': value['rawText'],
        'station_id': value['stationId'],
        'observation_time': value['observationTime'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'temp_c': value['tempC'],
        'dewpoint_c': value['dewpointC'],
        'wind_dir_degrees': METARpropertiesWdirToJSON(value['windDirDegrees']),
        'wind_speed_kt': value['windSpeedKt'],
        'visibility_statute_mi': METARpropertiesVisibToJSON(value['visibilityStatuteMi']),
        'altim_in_hg': value['altimInHg'],
        'sea_level_pressure_mb': value['seaLevelPressureMb'],
        'quality_control_flags': METARXMLDataInnerQualityControlFlagsToJSON(value['qualityControlFlags']),
        'flight_category': value['flightCategory'],
        'metar_type': value['metarType'],
        'elevation_m': value['elevationM'],
    };
}

