/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface METARXMLDataSource
 */
export interface METARXMLDataSource {
    /**
     * 
     * @type {string}
     * @memberof METARXMLDataSource
     */
    name?: METARXMLDataSourceNameEnum;
}


/**
 * @export
 */
export const METARXMLDataSourceNameEnum = {
    Metar: 'metar'
} as const;
export type METARXMLDataSourceNameEnum = typeof METARXMLDataSourceNameEnum[keyof typeof METARXMLDataSourceNameEnum];


/**
 * Check if a given object implements the METARXMLDataSource interface.
 */
export function instanceOfMETARXMLDataSource(value: object): value is METARXMLDataSource {
    return true;
}

export function METARXMLDataSourceFromJSON(json: any): METARXMLDataSource {
    return METARXMLDataSourceFromJSONTyped(json, false);
}

export function METARXMLDataSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARXMLDataSource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function METARXMLDataSourceToJSON(json: any): METARXMLDataSource {
    return METARXMLDataSourceToJSONTyped(json, false);
}

export function METARXMLDataSourceToJSONTyped(value?: METARXMLDataSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

