/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARGeoJSONFeaturesInner } from './metar-geo-json-features-inner';
import {
    METARGeoJSONFeaturesInnerFromJSON,
    METARGeoJSONFeaturesInnerFromJSONTyped,
    METARGeoJSONFeaturesInnerToJSON,
    METARGeoJSONFeaturesInnerToJSONTyped,
} from './metar-geo-json-features-inner';

/**
 * 
 * @export
 * @interface METARGeoJSON
 */
export interface METARGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof METARGeoJSON
     */
    type?: METARGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<METARGeoJSONFeaturesInner>}
     * @memberof METARGeoJSON
     */
    features?: Array<METARGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const METARGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type METARGeoJSONTypeEnum = typeof METARGeoJSONTypeEnum[keyof typeof METARGeoJSONTypeEnum];


/**
 * Check if a given object implements the METARGeoJSON interface.
 */
export function instanceOfMETARGeoJSON(value: object): value is METARGeoJSON {
    return true;
}

export function METARGeoJSONFromJSON(json: any): METARGeoJSON {
    return METARGeoJSONFromJSONTyped(json, false);
}

export function METARGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(METARGeoJSONFeaturesInnerFromJSON)),
    };
}

export function METARGeoJSONToJSON(json: any): METARGeoJSON {
    return METARGeoJSONToJSONTyped(json, false);
}

export function METARGeoJSONToJSONTyped(value?: METARGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(METARGeoJSONFeaturesInnerToJSON)),
    };
}

