/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface METARGeoJSONFeaturesInnerGeometry
 */
export interface METARGeoJSONFeaturesInnerGeometry {
    /**
     * 
     * @type {string}
     * @memberof METARGeoJSONFeaturesInnerGeometry
     */
    type?: METARGeoJSONFeaturesInnerGeometryTypeEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof METARGeoJSONFeaturesInnerGeometry
     */
    coordinates?: Array<number>;
}


/**
 * @export
 */
export const METARGeoJSONFeaturesInnerGeometryTypeEnum = {
    Point: 'Point'
} as const;
export type METARGeoJSONFeaturesInnerGeometryTypeEnum = typeof METARGeoJSONFeaturesInnerGeometryTypeEnum[keyof typeof METARGeoJSONFeaturesInnerGeometryTypeEnum];


/**
 * Check if a given object implements the METARGeoJSONFeaturesInnerGeometry interface.
 */
export function instanceOfMETARGeoJSONFeaturesInnerGeometry(value: object): value is METARGeoJSONFeaturesInnerGeometry {
    return true;
}

export function METARGeoJSONFeaturesInnerGeometryFromJSON(json: any): METARGeoJSONFeaturesInnerGeometry {
    return METARGeoJSONFeaturesInnerGeometryFromJSONTyped(json, false);
}

export function METARGeoJSONFeaturesInnerGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARGeoJSONFeaturesInnerGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
    };
}

export function METARGeoJSONFeaturesInnerGeometryToJSON(json: any): METARGeoJSONFeaturesInnerGeometry {
    return METARGeoJSONFeaturesInnerGeometryToJSONTyped(json, false);
}

export function METARGeoJSONFeaturesInnerGeometryToJSONTyped(value?: METARGeoJSONFeaturesInnerGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

