/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARXMLDataSource } from './metarxml-data-source';
import {
    METARXMLDataSourceFromJSON,
    METARXMLDataSourceFromJSONTyped,
    METARXMLDataSourceToJSON,
    METARXMLDataSourceToJSONTyped,
} from './metarxml-data-source';
import type { METARXMLRequest } from './metarxml-request';
import {
    METARXMLRequestFromJSON,
    METARXMLRequestFromJSONTyped,
    METARXMLRequestToJSON,
    METARXMLRequestToJSONTyped,
} from './metarxml-request';
import type { METARXMLDataInner } from './metarxml-data-inner';
import {
    METARXMLDataInnerFromJSON,
    METARXMLDataInnerFromJSONTyped,
    METARXMLDataInnerToJSON,
    METARXMLDataInnerToJSONTyped,
} from './metarxml-data-inner';

/**
 * 
 * @export
 * @interface METARXML
 */
export interface METARXML {
    /**
     * 
     * @type {number}
     * @memberof METARXML
     */
    requestIndex?: number;
    /**
     * 
     * @type {METARXMLDataSource}
     * @memberof METARXML
     */
    dataSource?: METARXMLDataSource;
    /**
     * 
     * @type {METARXMLRequest}
     * @memberof METARXML
     */
    request?: METARXMLRequest;
    /**
     * 
     * @type {number}
     * @memberof METARXML
     */
    timeTakenMs?: number;
    /**
     * 
     * @type {Array<METARXMLDataInner>}
     * @memberof METARXML
     */
    data?: Array<METARXMLDataInner>;
}

/**
 * Check if a given object implements the METARXML interface.
 */
export function instanceOfMETARXML(value: object): value is METARXML {
    return true;
}

export function METARXMLFromJSON(json: any): METARXML {
    return METARXMLFromJSONTyped(json, false);
}

export function METARXMLFromJSONTyped(json: any, ignoreDiscriminator: boolean): METARXML {
    if (json == null) {
        return json;
    }
    return {
        
        'requestIndex': json['request_index'] == null ? undefined : json['request_index'],
        'dataSource': json['data_source'] == null ? undefined : METARXMLDataSourceFromJSON(json['data_source']),
        'request': json['request'] == null ? undefined : METARXMLRequestFromJSON(json['request']),
        'timeTakenMs': json['time_taken_ms'] == null ? undefined : json['time_taken_ms'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(METARXMLDataInnerFromJSON)),
    };
}

export function METARXMLToJSON(json: any): METARXML {
    return METARXMLToJSONTyped(json, false);
}

export function METARXMLToJSONTyped(value?: METARXML | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_index': value['requestIndex'],
        'data_source': METARXMLDataSourceToJSON(value['dataSource']),
        'request': METARXMLRequestToJSON(value['request']),
        'time_taken_ms': value['timeTakenMs'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(METARXMLDataInnerToJSON)),
    };
}

