/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloudInfoInner } from './cloud-info-inner';
import {
    CloudInfoInnerFromJSON,
    CloudInfoInnerFromJSONTyped,
    CloudInfoInnerToJSON,
    CloudInfoInnerToJSONTyped,
} from './cloud-info-inner';

/**
 * 
 * @export
 * @interface PIREPGeoJSONFeaturesInnerProperties
 */
export interface PIREPGeoJSONFeaturesInnerProperties {
    /**
     * Time received by AWC
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    receiptTime?: string;
    /**
     * Observed time (UNIX epoch)
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    obsTime?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    qcField?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icaoId?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    acType?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    lat?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    lon?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    fltLvl?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    fltLvlType?: string;
    /**
     * Clouds
     * @type {Array<CloudInfoInner>}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    clouds?: Array<CloudInfoInner>;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    visib?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    wxString?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    temp?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    wdir?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    wspd?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgBas1?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgTop1?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgInt1?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgType1?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgBas2?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgTop2?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgInt2?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    icgType2?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbBas1?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbTop1?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbInt1?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbType1?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbFreq1?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbBas2?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbTop2?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbInt2?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbType2?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    tbFreq2?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    vertGust?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    brkAction?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    pirepType?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInnerProperties
     */
    rawOb?: string;
}

/**
 * Check if a given object implements the PIREPGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfPIREPGeoJSONFeaturesInnerProperties(value: object): value is PIREPGeoJSONFeaturesInnerProperties {
    return true;
}

export function PIREPGeoJSONFeaturesInnerPropertiesFromJSON(json: any): PIREPGeoJSONFeaturesInnerProperties {
    return PIREPGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function PIREPGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'obsTime': json['obsTime'] == null ? undefined : json['obsTime'],
        'qcField': json['qcField'] == null ? undefined : json['qcField'],
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'acType': json['acType'] == null ? undefined : json['acType'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'fltLvl': json['fltLvl'] == null ? undefined : json['fltLvl'],
        'fltLvlType': json['fltLvlType'] == null ? undefined : json['fltLvlType'],
        'clouds': json['clouds'] == null ? undefined : ((json['clouds'] as Array<any>).map(CloudInfoInnerFromJSON)),
        'visib': json['visib'] == null ? undefined : json['visib'],
        'wxString': json['wxString'] == null ? undefined : json['wxString'],
        'temp': json['temp'] == null ? undefined : json['temp'],
        'wdir': json['wdir'] == null ? undefined : json['wdir'],
        'wspd': json['wspd'] == null ? undefined : json['wspd'],
        'icgBas1': json['icgBas1'] == null ? undefined : json['icgBas1'],
        'icgTop1': json['icgTop1'] == null ? undefined : json['icgTop1'],
        'icgInt1': json['icgInt1'] == null ? undefined : json['icgInt1'],
        'icgType1': json['icgType1'] == null ? undefined : json['icgType1'],
        'icgBas2': json['icgBas2'] == null ? undefined : json['icgBas2'],
        'icgTop2': json['icgTop2'] == null ? undefined : json['icgTop2'],
        'icgInt2': json['icgInt2'] == null ? undefined : json['icgInt2'],
        'icgType2': json['icgType2'] == null ? undefined : json['icgType2'],
        'tbBas1': json['tbBas1'] == null ? undefined : json['tbBas1'],
        'tbTop1': json['tbTop1'] == null ? undefined : json['tbTop1'],
        'tbInt1': json['tbInt1'] == null ? undefined : json['tbInt1'],
        'tbType1': json['tbType1'] == null ? undefined : json['tbType1'],
        'tbFreq1': json['tbFreq1'] == null ? undefined : json['tbFreq1'],
        'tbBas2': json['tbBas2'] == null ? undefined : json['tbBas2'],
        'tbTop2': json['tbTop2'] == null ? undefined : json['tbTop2'],
        'tbInt2': json['tbInt2'] == null ? undefined : json['tbInt2'],
        'tbType2': json['tbType2'] == null ? undefined : json['tbType2'],
        'tbFreq2': json['tbFreq2'] == null ? undefined : json['tbFreq2'],
        'vertGust': json['vertGust'] == null ? undefined : json['vertGust'],
        'brkAction': json['brkAction'] == null ? undefined : json['brkAction'],
        'pirepType': json['pirepType'] == null ? undefined : json['pirepType'],
        'rawOb': json['rawOb'] == null ? undefined : json['rawOb'],
    };
}

export function PIREPGeoJSONFeaturesInnerPropertiesToJSON(json: any): PIREPGeoJSONFeaturesInnerProperties {
    return PIREPGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function PIREPGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: PIREPGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receiptTime': value['receiptTime'],
        'obsTime': value['obsTime'],
        'qcField': value['qcField'],
        'icaoId': value['icaoId'],
        'acType': value['acType'],
        'lat': value['lat'],
        'lon': value['lon'],
        'fltLvl': value['fltLvl'],
        'fltLvlType': value['fltLvlType'],
        'clouds': value['clouds'] == null ? undefined : ((value['clouds'] as Array<any>).map(CloudInfoInnerToJSON)),
        'visib': value['visib'],
        'wxString': value['wxString'],
        'temp': value['temp'],
        'wdir': value['wdir'],
        'wspd': value['wspd'],
        'icgBas1': value['icgBas1'],
        'icgTop1': value['icgTop1'],
        'icgInt1': value['icgInt1'],
        'icgType1': value['icgType1'],
        'icgBas2': value['icgBas2'],
        'icgTop2': value['icgTop2'],
        'icgInt2': value['icgInt2'],
        'icgType2': value['icgType2'],
        'tbBas1': value['tbBas1'],
        'tbTop1': value['tbTop1'],
        'tbInt1': value['tbInt1'],
        'tbType1': value['tbType1'],
        'tbFreq1': value['tbFreq1'],
        'tbBas2': value['tbBas2'],
        'tbTop2': value['tbTop2'],
        'tbInt2': value['tbInt2'],
        'tbType2': value['tbType2'],
        'tbFreq2': value['tbFreq2'],
        'vertGust': value['vertGust'],
        'brkAction': value['brkAction'],
        'pirepType': value['pirepType'],
        'rawOb': value['rawOb'],
    };
}

