/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PIREPXMLDataInnerTurbulenceCondition } from './pirepxml-data-inner-turbulence-condition';
import {
    PIREPXMLDataInnerTurbulenceConditionFromJSON,
    PIREPXMLDataInnerTurbulenceConditionFromJSONTyped,
    PIREPXMLDataInnerTurbulenceConditionToJSON,
    PIREPXMLDataInnerTurbulenceConditionToJSONTyped,
} from './pirepxml-data-inner-turbulence-condition';
import type { PIREPXMLDataInnerWindDirDegrees } from './pirepxml-data-inner-wind-dir-degrees';
import {
    PIREPXMLDataInnerWindDirDegreesFromJSON,
    PIREPXMLDataInnerWindDirDegreesFromJSONTyped,
    PIREPXMLDataInnerWindDirDegreesToJSON,
    PIREPXMLDataInnerWindDirDegreesToJSONTyped,
} from './pirepxml-data-inner-wind-dir-degrees';
import type { PIREPXMLDataInnerIcingCondition } from './pirepxml-data-inner-icing-condition';
import {
    PIREPXMLDataInnerIcingConditionFromJSON,
    PIREPXMLDataInnerIcingConditionFromJSONTyped,
    PIREPXMLDataInnerIcingConditionToJSON,
    PIREPXMLDataInnerIcingConditionToJSONTyped,
} from './pirepxml-data-inner-icing-condition';

/**
 * 
 * @export
 * @interface PIREPXMLDataInner
 */
export interface PIREPXMLDataInner {
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    receiptTime?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    observationTime?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    qualityControlFlags?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    aircraftRef?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    latitude?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    longitude?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    altitudeFtMsl?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    skyCondition?: string;
    /**
     * 
     * @type {PIREPXMLDataInnerTurbulenceCondition}
     * @memberof PIREPXMLDataInner
     */
    turbulenceCondition?: PIREPXMLDataInnerTurbulenceCondition;
    /**
     * 
     * @type {PIREPXMLDataInnerIcingCondition}
     * @memberof PIREPXMLDataInner
     */
    icingCondition?: PIREPXMLDataInnerIcingCondition;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    visibilityStatuteMi?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    wxString?: string;
    /**
     * Temperature in Celsius
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    tempC?: number;
    /**
     * 
     * @type {PIREPXMLDataInnerWindDirDegrees}
     * @memberof PIREPXMLDataInner
     */
    windDirDegrees?: PIREPXMLDataInnerWindDirDegrees;
    /**
     * Wind speed in knots
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    windSpeedKt?: number;
    /**
     * Wind gust in knots
     * @type {number}
     * @memberof PIREPXMLDataInner
     */
    vertGustKt?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    pirepType?: PIREPXMLDataInnerPirepTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInner
     */
    rawText?: string;
}


/**
 * @export
 */
export const PIREPXMLDataInnerPirepTypeEnum = {
    Pirep: 'PIREP',
    UrgentPirep: 'Urgent PIREP',
    Airep: 'AIREP',
    Amdar: 'AMDAR'
} as const;
export type PIREPXMLDataInnerPirepTypeEnum = typeof PIREPXMLDataInnerPirepTypeEnum[keyof typeof PIREPXMLDataInnerPirepTypeEnum];


/**
 * Check if a given object implements the PIREPXMLDataInner interface.
 */
export function instanceOfPIREPXMLDataInner(value: object): value is PIREPXMLDataInner {
    return true;
}

export function PIREPXMLDataInnerFromJSON(json: any): PIREPXMLDataInner {
    return PIREPXMLDataInnerFromJSONTyped(json, false);
}

export function PIREPXMLDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPXMLDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'receiptTime': json['receipt_time'] == null ? undefined : json['receipt_time'],
        'observationTime': json['observation_time'] == null ? undefined : json['observation_time'],
        'qualityControlFlags': json['quality_control_flags'] == null ? undefined : json['quality_control_flags'],
        'aircraftRef': json['aircraft_ref'] == null ? undefined : json['aircraft_ref'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'altitudeFtMsl': json['altitude_ft_msl'] == null ? undefined : json['altitude_ft_msl'],
        'skyCondition': json['sky_condition'] == null ? undefined : json['sky_condition'],
        'turbulenceCondition': json['turbulence_condition'] == null ? undefined : PIREPXMLDataInnerTurbulenceConditionFromJSON(json['turbulence_condition']),
        'icingCondition': json['icing_condition'] == null ? undefined : PIREPXMLDataInnerIcingConditionFromJSON(json['icing_condition']),
        'visibilityStatuteMi': json['visibility_statute_mi'] == null ? undefined : json['visibility_statute_mi'],
        'wxString': json['wx_string'] == null ? undefined : json['wx_string'],
        'tempC': json['temp_c'] == null ? undefined : json['temp_c'],
        'windDirDegrees': json['wind_dir_degrees'] == null ? undefined : PIREPXMLDataInnerWindDirDegreesFromJSON(json['wind_dir_degrees']),
        'windSpeedKt': json['wind_speed_kt'] == null ? undefined : json['wind_speed_kt'],
        'vertGustKt': json['vert_gust_kt'] == null ? undefined : json['vert_gust_kt'],
        'pirepType': json['pirep_type'] == null ? undefined : json['pirep_type'],
        'rawText': json['raw_text'] == null ? undefined : json['raw_text'],
    };
}

export function PIREPXMLDataInnerToJSON(json: any): PIREPXMLDataInner {
    return PIREPXMLDataInnerToJSONTyped(json, false);
}

export function PIREPXMLDataInnerToJSONTyped(value?: PIREPXMLDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receipt_time': value['receiptTime'],
        'observation_time': value['observationTime'],
        'quality_control_flags': value['qualityControlFlags'],
        'aircraft_ref': value['aircraftRef'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'altitude_ft_msl': value['altitudeFtMsl'],
        'sky_condition': value['skyCondition'],
        'turbulence_condition': PIREPXMLDataInnerTurbulenceConditionToJSON(value['turbulenceCondition']),
        'icing_condition': PIREPXMLDataInnerIcingConditionToJSON(value['icingCondition']),
        'visibility_statute_mi': value['visibilityStatuteMi'],
        'wx_string': value['wxString'],
        'temp_c': value['tempC'],
        'wind_dir_degrees': PIREPXMLDataInnerWindDirDegreesToJSON(value['windDirDegrees']),
        'wind_speed_kt': value['windSpeedKt'],
        'vert_gust_kt': value['vertGustKt'],
        'pirep_type': value['pirepType'],
        'raw_text': value['rawText'],
    };
}

