/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARGeoJSONFeaturesInnerGeometry } from './metar-geo-json-features-inner-geometry';
import {
    METARGeoJSONFeaturesInnerGeometryFromJSON,
    METARGeoJSONFeaturesInnerGeometryFromJSONTyped,
    METARGeoJSONFeaturesInnerGeometryToJSON,
    METARGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './metar-geo-json-features-inner-geometry';
import type { PIREPGeoJSONFeaturesInnerProperties } from './pirep-geo-json-features-inner-properties';
import {
    PIREPGeoJSONFeaturesInnerPropertiesFromJSON,
    PIREPGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    PIREPGeoJSONFeaturesInnerPropertiesToJSON,
    PIREPGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './pirep-geo-json-features-inner-properties';

/**
 * 
 * @export
 * @interface PIREPGeoJSONFeaturesInner
 */
export interface PIREPGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSONFeaturesInner
     */
    type?: PIREPGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof PIREPGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {PIREPGeoJSONFeaturesInnerProperties}
     * @memberof PIREPGeoJSONFeaturesInner
     */
    properties?: PIREPGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {METARGeoJSONFeaturesInnerGeometry}
     * @memberof PIREPGeoJSONFeaturesInner
     */
    geometry?: METARGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const PIREPGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type PIREPGeoJSONFeaturesInnerTypeEnum = typeof PIREPGeoJSONFeaturesInnerTypeEnum[keyof typeof PIREPGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the PIREPGeoJSONFeaturesInner interface.
 */
export function instanceOfPIREPGeoJSONFeaturesInner(value: object): value is PIREPGeoJSONFeaturesInner {
    return true;
}

export function PIREPGeoJSONFeaturesInnerFromJSON(json: any): PIREPGeoJSONFeaturesInner {
    return PIREPGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function PIREPGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : PIREPGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : METARGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function PIREPGeoJSONFeaturesInnerToJSON(json: any): PIREPGeoJSONFeaturesInner {
    return PIREPGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function PIREPGeoJSONFeaturesInnerToJSONTyped(value?: PIREPGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': PIREPGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': METARGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

