/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PIREPGeoJSONFeaturesInner } from './pirep-geo-json-features-inner';
import {
    PIREPGeoJSONFeaturesInnerFromJSON,
    PIREPGeoJSONFeaturesInnerFromJSONTyped,
    PIREPGeoJSONFeaturesInnerToJSON,
    PIREPGeoJSONFeaturesInnerToJSONTyped,
} from './pirep-geo-json-features-inner';

/**
 * 
 * @export
 * @interface PIREPGeoJSON
 */
export interface PIREPGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof PIREPGeoJSON
     */
    type?: PIREPGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<PIREPGeoJSONFeaturesInner>}
     * @memberof PIREPGeoJSON
     */
    features?: Array<PIREPGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const PIREPGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type PIREPGeoJSONTypeEnum = typeof PIREPGeoJSONTypeEnum[keyof typeof PIREPGeoJSONTypeEnum];


/**
 * Check if a given object implements the PIREPGeoJSON interface.
 */
export function instanceOfPIREPGeoJSON(value: object): value is PIREPGeoJSON {
    return true;
}

export function PIREPGeoJSONFromJSON(json: any): PIREPGeoJSON {
    return PIREPGeoJSONFromJSONTyped(json, false);
}

export function PIREPGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(PIREPGeoJSONFeaturesInnerFromJSON)),
    };
}

export function PIREPGeoJSONToJSON(json: any): PIREPGeoJSON {
    return PIREPGeoJSONToJSONTyped(json, false);
}

export function PIREPGeoJSONToJSONTyped(value?: PIREPGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(PIREPGeoJSONFeaturesInnerToJSON)),
    };
}

