/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Wind direction in degrees or VRB for variable winds
 * @export
 * @interface PIREPXMLDataInnerWindDirDegrees
 */
export interface PIREPXMLDataInnerWindDirDegrees {
}

/**
 * Check if a given object implements the PIREPXMLDataInnerWindDirDegrees interface.
 */
export function instanceOfPIREPXMLDataInnerWindDirDegrees(value: object): value is PIREPXMLDataInnerWindDirDegrees {
    return true;
}

export function PIREPXMLDataInnerWindDirDegreesFromJSON(json: any): PIREPXMLDataInnerWindDirDegrees {
    return PIREPXMLDataInnerWindDirDegreesFromJSONTyped(json, false);
}

export function PIREPXMLDataInnerWindDirDegreesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPXMLDataInnerWindDirDegrees {
    return json;
}

export function PIREPXMLDataInnerWindDirDegreesToJSON(json: any): PIREPXMLDataInnerWindDirDegrees {
    return PIREPXMLDataInnerWindDirDegreesToJSONTyped(json, false);
}

export function PIREPXMLDataInnerWindDirDegreesToJSONTyped(value?: PIREPXMLDataInnerWindDirDegrees | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

