/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PIREPXMLDataInnerTurbulenceCondition
 */
export interface PIREPXMLDataInnerTurbulenceCondition {
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerTurbulenceCondition
     */
    turbulenceType?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerTurbulenceCondition
     */
    turbulenceIntensity?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerTurbulenceCondition
     */
    turbulenceBaseFtMsl?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerTurbulenceCondition
     */
    turbulenceTopFtMsl?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerTurbulenceCondition
     */
    turbulenceFreq?: string;
}

/**
 * Check if a given object implements the PIREPXMLDataInnerTurbulenceCondition interface.
 */
export function instanceOfPIREPXMLDataInnerTurbulenceCondition(value: object): value is PIREPXMLDataInnerTurbulenceCondition {
    return true;
}

export function PIREPXMLDataInnerTurbulenceConditionFromJSON(json: any): PIREPXMLDataInnerTurbulenceCondition {
    return PIREPXMLDataInnerTurbulenceConditionFromJSONTyped(json, false);
}

export function PIREPXMLDataInnerTurbulenceConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPXMLDataInnerTurbulenceCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'turbulenceType': json['turbulence_type'] == null ? undefined : json['turbulence_type'],
        'turbulenceIntensity': json['turbulence_intensity'] == null ? undefined : json['turbulence_intensity'],
        'turbulenceBaseFtMsl': json['turbulence_base_ft_msl'] == null ? undefined : json['turbulence_base_ft_msl'],
        'turbulenceTopFtMsl': json['turbulence_top_ft_msl'] == null ? undefined : json['turbulence_top_ft_msl'],
        'turbulenceFreq': json['turbulence_freq'] == null ? undefined : json['turbulence_freq'],
    };
}

export function PIREPXMLDataInnerTurbulenceConditionToJSON(json: any): PIREPXMLDataInnerTurbulenceCondition {
    return PIREPXMLDataInnerTurbulenceConditionToJSONTyped(json, false);
}

export function PIREPXMLDataInnerTurbulenceConditionToJSONTyped(value?: PIREPXMLDataInnerTurbulenceCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'turbulence_type': value['turbulenceType'],
        'turbulence_intensity': value['turbulenceIntensity'],
        'turbulence_base_ft_msl': value['turbulenceBaseFtMsl'],
        'turbulence_top_ft_msl': value['turbulenceTopFtMsl'],
        'turbulence_freq': value['turbulenceFreq'],
    };
}

