/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloudInfoInner } from './cloud-info-inner';
import {
    CloudInfoInnerFromJSON,
    CloudInfoInnerFromJSONTyped,
    CloudInfoInnerToJSON,
    CloudInfoInnerToJSONTyped,
} from './cloud-info-inner';

/**
 * 
 * @export
 * @interface PIREPJSONInner
 */
export interface PIREPJSONInner {
    /**
     * Time received by AWC
     * @type {string}
     * @memberof PIREPJSONInner
     */
    receiptTime?: string;
    /**
     * Observed time (UNIX epoch)
     * @type {number}
     * @memberof PIREPJSONInner
     */
    obsTime?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    qcField?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    icaoId?: string;
    /**
     * ICAO aircraft type
     * @type {string}
     * @memberof PIREPJSONInner
     */
    acType?: string;
    /**
     * Latitude
     * @type {number}
     * @memberof PIREPJSONInner
     */
    lat?: number;
    /**
     * Longitude
     * @type {number}
     * @memberof PIREPJSONInner
     */
    lon?: number;
    /**
     * Flight level (hundreds of feet)
     * @type {string}
     * @memberof PIREPJSONInner
     */
    fltLvl?: string;
    /**
     * Phase of flight
     * @type {string}
     * @memberof PIREPJSONInner
     */
    fltLvlType?: PIREPJSONInnerFltLvlTypeEnum;
    /**
     * Clouds
     * @type {Array<CloudInfoInner>}
     * @memberof PIREPJSONInner
     */
    clouds?: Array<CloudInfoInner>;
    /**
     * Visibility
     * @type {string}
     * @memberof PIREPJSONInner
     */
    visib?: string;
    /**
     * Observed weather
     * @type {string}
     * @memberof PIREPJSONInner
     */
    wxString?: string;
    /**
     * Temperature in Celsius
     * @type {number}
     * @memberof PIREPJSONInner
     */
    temp?: number;
    /**
     * Wind direction
     * @type {number}
     * @memberof PIREPJSONInner
     */
    wdir?: number;
    /**
     * Wind speed
     * @type {number}
     * @memberof PIREPJSONInner
     */
    wspd?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    icgBas1?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    icgTop1?: PIREPJSONInnerIcgTop1Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    icgInt1?: PIREPJSONInnerIcgInt1Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    icgType1?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    icgBas2?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    icgTop2?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    icgInt2?: PIREPJSONInnerIcgInt2Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    icgType2?: PIREPJSONInnerIcgType2Enum;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    tbBas1?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    tbTop1?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    tbInt1?: PIREPJSONInnerTbInt1Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    tbType1?: PIREPJSONInnerTbType1Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    tbFreq1?: PIREPJSONInnerTbFreq1Enum;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    tbBas2?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    tbTop2?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    tbInt2?: PIREPJSONInnerTbInt2Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    tbType2?: PIREPJSONInnerTbType2Enum;
    /**
     * 
     * @type {string}
     * @memberof PIREPJSONInner
     */
    tbFreq2?: PIREPJSONInnerTbFreq2Enum;
    /**
     * 
     * @type {number}
     * @memberof PIREPJSONInner
     */
    vertGust?: number;
    /**
     * Breaking action conditions
     * @type {string}
     * @memberof PIREPJSONInner
     */
    brkAction?: PIREPJSONInnerBrkActionEnum;
    /**
     * Aircraft report type
     * @type {string}
     * @memberof PIREPJSONInner
     */
    pirepType?: PIREPJSONInnerPirepTypeEnum;
    /**
     * Raw data
     * @type {string}
     * @memberof PIREPJSONInner
     */
    rawOb?: string;
}


/**
 * @export
 */
export const PIREPJSONInnerFltLvlTypeEnum = {
    Grnd: 'GRND',
    Durc: 'DURC',
    Durd: 'DURD',
    Cruise: 'CRUISE',
    Other: 'OTHER',
    Unkn: 'UNKN'
} as const;
export type PIREPJSONInnerFltLvlTypeEnum = typeof PIREPJSONInnerFltLvlTypeEnum[keyof typeof PIREPJSONInnerFltLvlTypeEnum];

/**
 * @export
 */
export const PIREPJSONInnerIcgTop1Enum = {
    NUMBER_RIME: 'RIME',
    NUMBER_CLEAR: 'CLEAR',
    NUMBER_MIXED: 'MIXED'
} as const;
export type PIREPJSONInnerIcgTop1Enum = typeof PIREPJSONInnerIcgTop1Enum[keyof typeof PIREPJSONInnerIcgTop1Enum];

/**
 * @export
 */
export const PIREPJSONInnerIcgInt1Enum = {
    Neg: 'NEG',
    NeGclr: 'NEGclr',
    Trc: 'TRC',
    TrcLgt: 'TRC-LGT',
    Lgt: 'LGT',
    LgtMod: 'LGT-MOD',
    Mod: 'MOD',
    ModSev: 'MOD-SEV',
    Hvy: 'HVY',
    Sev: 'SEV'
} as const;
export type PIREPJSONInnerIcgInt1Enum = typeof PIREPJSONInnerIcgInt1Enum[keyof typeof PIREPJSONInnerIcgInt1Enum];

/**
 * @export
 */
export const PIREPJSONInnerIcgInt2Enum = {
    Neg: 'NEG',
    NeGclr: 'NEGclr',
    Trc: 'TRC',
    TrcLgt: 'TRC-LGT',
    Lgt: 'LGT',
    LgtMod: 'LGT-MOD',
    Mod: 'MOD',
    ModSev: 'MOD-SEV',
    Hvy: 'HVY',
    Sev: 'SEV'
} as const;
export type PIREPJSONInnerIcgInt2Enum = typeof PIREPJSONInnerIcgInt2Enum[keyof typeof PIREPJSONInnerIcgInt2Enum];

/**
 * @export
 */
export const PIREPJSONInnerIcgType2Enum = {
    Rime: 'RIME',
    Clear: 'CLEAR',
    Mixed: 'MIXED'
} as const;
export type PIREPJSONInnerIcgType2Enum = typeof PIREPJSONInnerIcgType2Enum[keyof typeof PIREPJSONInnerIcgType2Enum];

/**
 * @export
 */
export const PIREPJSONInnerTbInt1Enum = {
    Neg: 'NEG',
    SmthLgt: 'SMTH-LGT',
    Lgt: 'LGT',
    LgtMod: 'LGT-MOD',
    Mod: 'MOD',
    ModSev: 'MOD-SEV',
    Sev: 'SEV',
    ModExtm: 'MOD-EXTM',
    SevExtm: 'SEV-EXTM',
    Extm: 'EXTM'
} as const;
export type PIREPJSONInnerTbInt1Enum = typeof PIREPJSONInnerTbInt1Enum[keyof typeof PIREPJSONInnerTbInt1Enum];

/**
 * @export
 */
export const PIREPJSONInnerTbType1Enum = {
    Cat: 'CAT',
    Chop: 'CHOP',
    Llws: 'LLWS',
    Mwave: 'MWAVE'
} as const;
export type PIREPJSONInnerTbType1Enum = typeof PIREPJSONInnerTbType1Enum[keyof typeof PIREPJSONInnerTbType1Enum];

/**
 * @export
 */
export const PIREPJSONInnerTbFreq1Enum = {
    Isol: 'ISOL',
    Ocnl: 'OCNL',
    Cont: 'CONT'
} as const;
export type PIREPJSONInnerTbFreq1Enum = typeof PIREPJSONInnerTbFreq1Enum[keyof typeof PIREPJSONInnerTbFreq1Enum];

/**
 * @export
 */
export const PIREPJSONInnerTbInt2Enum = {
    Neg: 'NEG',
    SmthLgt: 'SMTH-LGT',
    Lgt: 'LGT',
    LgtMod: 'LGT-MOD',
    Mod: 'MOD',
    ModSev: 'MOD-SEV',
    Sev: 'SEV',
    ModExtm: 'MOD-EXTM',
    SevExtm: 'SEV-EXTM',
    Extm: 'EXTM'
} as const;
export type PIREPJSONInnerTbInt2Enum = typeof PIREPJSONInnerTbInt2Enum[keyof typeof PIREPJSONInnerTbInt2Enum];

/**
 * @export
 */
export const PIREPJSONInnerTbType2Enum = {
    Cat: 'CAT',
    Chop: 'CHOP',
    Llws: 'LLWS',
    Mwave: 'MWAVE'
} as const;
export type PIREPJSONInnerTbType2Enum = typeof PIREPJSONInnerTbType2Enum[keyof typeof PIREPJSONInnerTbType2Enum];

/**
 * @export
 */
export const PIREPJSONInnerTbFreq2Enum = {
    Isol: 'ISOL',
    Ocnl: 'OCNL',
    Cont: 'CONT'
} as const;
export type PIREPJSONInnerTbFreq2Enum = typeof PIREPJSONInnerTbFreq2Enum[keyof typeof PIREPJSONInnerTbFreq2Enum];

/**
 * @export
 */
export const PIREPJSONInnerBrkActionEnum = {
    Good: 'GOOD',
    GoodMed: 'GOOD-MED',
    Med: 'MED',
    MedPoor: 'MED-POOR',
    Poor: 'POOR',
    Nil: 'NIL'
} as const;
export type PIREPJSONInnerBrkActionEnum = typeof PIREPJSONInnerBrkActionEnum[keyof typeof PIREPJSONInnerBrkActionEnum];

/**
 * @export
 */
export const PIREPJSONInnerPirepTypeEnum = {
    Pirep: 'PIREP',
    UrgentPirep: 'Urgent PIREP',
    Airep: 'AIREP',
    Amdar: 'AMDAR'
} as const;
export type PIREPJSONInnerPirepTypeEnum = typeof PIREPJSONInnerPirepTypeEnum[keyof typeof PIREPJSONInnerPirepTypeEnum];


/**
 * Check if a given object implements the PIREPJSONInner interface.
 */
export function instanceOfPIREPJSONInner(value: object): value is PIREPJSONInner {
    return true;
}

export function PIREPJSONInnerFromJSON(json: any): PIREPJSONInner {
    return PIREPJSONInnerFromJSONTyped(json, false);
}

export function PIREPJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'receiptTime': json['receiptTime'] == null ? undefined : json['receiptTime'],
        'obsTime': json['obsTime'] == null ? undefined : json['obsTime'],
        'qcField': json['qcField'] == null ? undefined : json['qcField'],
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'acType': json['acType'] == null ? undefined : json['acType'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'fltLvl': json['fltLvl'] == null ? undefined : json['fltLvl'],
        'fltLvlType': json['fltLvlType'] == null ? undefined : json['fltLvlType'],
        'clouds': json['clouds'] == null ? undefined : ((json['clouds'] as Array<any>).map(CloudInfoInnerFromJSON)),
        'visib': json['visib'] == null ? undefined : json['visib'],
        'wxString': json['wxString'] == null ? undefined : json['wxString'],
        'temp': json['temp'] == null ? undefined : json['temp'],
        'wdir': json['wdir'] == null ? undefined : json['wdir'],
        'wspd': json['wspd'] == null ? undefined : json['wspd'],
        'icgBas1': json['icgBas1'] == null ? undefined : json['icgBas1'],
        'icgTop1': json['icgTop1'] == null ? undefined : json['icgTop1'],
        'icgInt1': json['icgInt1'] == null ? undefined : json['icgInt1'],
        'icgType1': json['icgType1'] == null ? undefined : json['icgType1'],
        'icgBas2': json['icgBas2'] == null ? undefined : json['icgBas2'],
        'icgTop2': json['icgTop2'] == null ? undefined : json['icgTop2'],
        'icgInt2': json['icgInt2'] == null ? undefined : json['icgInt2'],
        'icgType2': json['icgType2'] == null ? undefined : json['icgType2'],
        'tbBas1': json['tbBas1'] == null ? undefined : json['tbBas1'],
        'tbTop1': json['tbTop1'] == null ? undefined : json['tbTop1'],
        'tbInt1': json['tbInt1'] == null ? undefined : json['tbInt1'],
        'tbType1': json['tbType1'] == null ? undefined : json['tbType1'],
        'tbFreq1': json['tbFreq1'] == null ? undefined : json['tbFreq1'],
        'tbBas2': json['tbBas2'] == null ? undefined : json['tbBas2'],
        'tbTop2': json['tbTop2'] == null ? undefined : json['tbTop2'],
        'tbInt2': json['tbInt2'] == null ? undefined : json['tbInt2'],
        'tbType2': json['tbType2'] == null ? undefined : json['tbType2'],
        'tbFreq2': json['tbFreq2'] == null ? undefined : json['tbFreq2'],
        'vertGust': json['vertGust'] == null ? undefined : json['vertGust'],
        'brkAction': json['brkAction'] == null ? undefined : json['brkAction'],
        'pirepType': json['pirepType'] == null ? undefined : json['pirepType'],
        'rawOb': json['rawOb'] == null ? undefined : json['rawOb'],
    };
}

export function PIREPJSONInnerToJSON(json: any): PIREPJSONInner {
    return PIREPJSONInnerToJSONTyped(json, false);
}

export function PIREPJSONInnerToJSONTyped(value?: PIREPJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'receiptTime': value['receiptTime'],
        'obsTime': value['obsTime'],
        'qcField': value['qcField'],
        'icaoId': value['icaoId'],
        'acType': value['acType'],
        'lat': value['lat'],
        'lon': value['lon'],
        'fltLvl': value['fltLvl'],
        'fltLvlType': value['fltLvlType'],
        'clouds': value['clouds'] == null ? undefined : ((value['clouds'] as Array<any>).map(CloudInfoInnerToJSON)),
        'visib': value['visib'],
        'wxString': value['wxString'],
        'temp': value['temp'],
        'wdir': value['wdir'],
        'wspd': value['wspd'],
        'icgBas1': value['icgBas1'],
        'icgTop1': value['icgTop1'],
        'icgInt1': value['icgInt1'],
        'icgType1': value['icgType1'],
        'icgBas2': value['icgBas2'],
        'icgTop2': value['icgTop2'],
        'icgInt2': value['icgInt2'],
        'icgType2': value['icgType2'],
        'tbBas1': value['tbBas1'],
        'tbTop1': value['tbTop1'],
        'tbInt1': value['tbInt1'],
        'tbType1': value['tbType1'],
        'tbFreq1': value['tbFreq1'],
        'tbBas2': value['tbBas2'],
        'tbTop2': value['tbTop2'],
        'tbInt2': value['tbInt2'],
        'tbType2': value['tbType2'],
        'tbFreq2': value['tbFreq2'],
        'vertGust': value['vertGust'],
        'brkAction': value['brkAction'],
        'pirepType': value['pirepType'],
        'rawOb': value['rawOb'],
    };
}

