/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARXMLRequest } from './metarxml-request';
import {
    METARXMLRequestFromJSON,
    METARXMLRequestFromJSONTyped,
    METARXMLRequestToJSON,
    METARXMLRequestToJSONTyped,
} from './metarxml-request';
import type { PIREPXMLDataInner } from './pirepxml-data-inner';
import {
    PIREPXMLDataInnerFromJSON,
    PIREPXMLDataInnerFromJSONTyped,
    PIREPXMLDataInnerToJSON,
    PIREPXMLDataInnerToJSONTyped,
} from './pirepxml-data-inner';
import type { PIREPXMLDataSource } from './pirepxml-data-source';
import {
    PIREPXMLDataSourceFromJSON,
    PIREPXMLDataSourceFromJSONTyped,
    PIREPXMLDataSourceToJSON,
    PIREPXMLDataSourceToJSONTyped,
} from './pirepxml-data-source';

/**
 * 
 * @export
 * @interface PIREPXML
 */
export interface PIREPXML {
    /**
     * 
     * @type {number}
     * @memberof PIREPXML
     */
    requestIndex?: number;
    /**
     * 
     * @type {PIREPXMLDataSource}
     * @memberof PIREPXML
     */
    dataSource?: PIREPXMLDataSource;
    /**
     * 
     * @type {METARXMLRequest}
     * @memberof PIREPXML
     */
    request?: METARXMLRequest;
    /**
     * 
     * @type {number}
     * @memberof PIREPXML
     */
    timeTakenMs?: number;
    /**
     * 
     * @type {Array<PIREPXMLDataInner>}
     * @memberof PIREPXML
     */
    data?: Array<PIREPXMLDataInner>;
}

/**
 * Check if a given object implements the PIREPXML interface.
 */
export function instanceOfPIREPXML(value: object): value is PIREPXML {
    return true;
}

export function PIREPXMLFromJSON(json: any): PIREPXML {
    return PIREPXMLFromJSONTyped(json, false);
}

export function PIREPXMLFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPXML {
    if (json == null) {
        return json;
    }
    return {
        
        'requestIndex': json['request_index'] == null ? undefined : json['request_index'],
        'dataSource': json['data_source'] == null ? undefined : PIREPXMLDataSourceFromJSON(json['data_source']),
        'request': json['request'] == null ? undefined : METARXMLRequestFromJSON(json['request']),
        'timeTakenMs': json['time_taken_ms'] == null ? undefined : json['time_taken_ms'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(PIREPXMLDataInnerFromJSON)),
    };
}

export function PIREPXMLToJSON(json: any): PIREPXML {
    return PIREPXMLToJSONTyped(json, false);
}

export function PIREPXMLToJSONTyped(value?: PIREPXML | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_index': value['requestIndex'],
        'data_source': PIREPXMLDataSourceToJSON(value['dataSource']),
        'request': METARXMLRequestToJSON(value['request']),
        'time_taken_ms': value['timeTakenMs'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(PIREPXMLDataInnerToJSON)),
    };
}

