/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PIREPXMLDataInnerIcingCondition
 */
export interface PIREPXMLDataInnerIcingCondition {
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerIcingCondition
     */
    icingType?: string;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerIcingCondition
     */
    icingIntensity?: string;
    /**
     * 
     * @type {number}
     * @memberof PIREPXMLDataInnerIcingCondition
     */
    icingBaseFtMsl?: number;
    /**
     * 
     * @type {number}
     * @memberof PIREPXMLDataInnerIcingCondition
     */
    icingTopFtMsl?: number;
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataInnerIcingCondition
     */
    turbulenceFreq?: string;
}

/**
 * Check if a given object implements the PIREPXMLDataInnerIcingCondition interface.
 */
export function instanceOfPIREPXMLDataInnerIcingCondition(value: object): value is PIREPXMLDataInnerIcingCondition {
    return true;
}

export function PIREPXMLDataInnerIcingConditionFromJSON(json: any): PIREPXMLDataInnerIcingCondition {
    return PIREPXMLDataInnerIcingConditionFromJSONTyped(json, false);
}

export function PIREPXMLDataInnerIcingConditionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPXMLDataInnerIcingCondition {
    if (json == null) {
        return json;
    }
    return {
        
        'icingType': json['icing_type'] == null ? undefined : json['icing_type'],
        'icingIntensity': json['icing_intensity'] == null ? undefined : json['icing_intensity'],
        'icingBaseFtMsl': json['icing_base_ft_msl'] == null ? undefined : json['icing_base_ft_msl'],
        'icingTopFtMsl': json['icing_top_ft_msl'] == null ? undefined : json['icing_top_ft_msl'],
        'turbulenceFreq': json['turbulence_freq'] == null ? undefined : json['turbulence_freq'],
    };
}

export function PIREPXMLDataInnerIcingConditionToJSON(json: any): PIREPXMLDataInnerIcingCondition {
    return PIREPXMLDataInnerIcingConditionToJSONTyped(json, false);
}

export function PIREPXMLDataInnerIcingConditionToJSONTyped(value?: PIREPXMLDataInnerIcingCondition | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icing_type': value['icingType'],
        'icing_intensity': value['icingIntensity'],
        'icing_base_ft_msl': value['icingBaseFtMsl'],
        'icing_top_ft_msl': value['icingTopFtMsl'],
        'turbulence_freq': value['turbulenceFreq'],
    };
}

