/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PIREPXMLDataSource
 */
export interface PIREPXMLDataSource {
    /**
     * 
     * @type {string}
     * @memberof PIREPXMLDataSource
     */
    name?: PIREPXMLDataSourceNameEnum;
}


/**
 * @export
 */
export const PIREPXMLDataSourceNameEnum = {
    Aircraftreports: 'aircraftreports'
} as const;
export type PIREPXMLDataSourceNameEnum = typeof PIREPXMLDataSourceNameEnum[keyof typeof PIREPXMLDataSourceNameEnum];


/**
 * Check if a given object implements the PIREPXMLDataSource interface.
 */
export function instanceOfPIREPXMLDataSource(value: object): value is PIREPXMLDataSource {
    return true;
}

export function PIREPXMLDataSourceFromJSON(json: any): PIREPXMLDataSource {
    return PIREPXMLDataSourceFromJSONTyped(json, false);
}

export function PIREPXMLDataSourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): PIREPXMLDataSource {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function PIREPXMLDataSourceToJSON(json: any): PIREPXMLDataSource {
    return PIREPXMLDataSourceToJSONTyped(json, false);
}

export function PIREPXMLDataSourceToJSONTyped(value?: PIREPXMLDataSource | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

