/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StationInfoGeoJSONFeaturesInnerProperties } from './station-info-geo-json-features-inner-properties';
import {
    StationInfoGeoJSONFeaturesInnerPropertiesFromJSON,
    StationInfoGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    StationInfoGeoJSONFeaturesInnerPropertiesToJSON,
    StationInfoGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './station-info-geo-json-features-inner-properties';
import type { METARGeoJSONFeaturesInnerGeometry } from './metar-geo-json-features-inner-geometry';
import {
    METARGeoJSONFeaturesInnerGeometryFromJSON,
    METARGeoJSONFeaturesInnerGeometryFromJSONTyped,
    METARGeoJSONFeaturesInnerGeometryToJSON,
    METARGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './metar-geo-json-features-inner-geometry';

/**
 * 
 * @export
 * @interface StationInfoGeoJSONFeaturesInner
 */
export interface StationInfoGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof StationInfoGeoJSONFeaturesInner
     */
    type?: StationInfoGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof StationInfoGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {StationInfoGeoJSONFeaturesInnerProperties}
     * @memberof StationInfoGeoJSONFeaturesInner
     */
    properties?: StationInfoGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {METARGeoJSONFeaturesInnerGeometry}
     * @memberof StationInfoGeoJSONFeaturesInner
     */
    geometry?: METARGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const StationInfoGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type StationInfoGeoJSONFeaturesInnerTypeEnum = typeof StationInfoGeoJSONFeaturesInnerTypeEnum[keyof typeof StationInfoGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the StationInfoGeoJSONFeaturesInner interface.
 */
export function instanceOfStationInfoGeoJSONFeaturesInner(value: object): value is StationInfoGeoJSONFeaturesInner {
    return true;
}

export function StationInfoGeoJSONFeaturesInnerFromJSON(json: any): StationInfoGeoJSONFeaturesInner {
    return StationInfoGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function StationInfoGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationInfoGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : StationInfoGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : METARGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function StationInfoGeoJSONFeaturesInnerToJSON(json: any): StationInfoGeoJSONFeaturesInner {
    return StationInfoGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function StationInfoGeoJSONFeaturesInnerToJSONTyped(value?: StationInfoGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': StationInfoGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': METARGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

