/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { METARXMLRequest } from './metarxml-request';
import {
    METARXMLRequestFromJSON,
    METARXMLRequestFromJSONTyped,
    METARXMLRequestToJSON,
    METARXMLRequestToJSONTyped,
} from './metarxml-request';
import type { PIREPXMLDataSource } from './pirepxml-data-source';
import {
    PIREPXMLDataSourceFromJSON,
    PIREPXMLDataSourceFromJSONTyped,
    PIREPXMLDataSourceToJSON,
    PIREPXMLDataSourceToJSONTyped,
} from './pirepxml-data-source';
import type { StationInfoXMLDataInner } from './station-info-xml-data-inner';
import {
    StationInfoXMLDataInnerFromJSON,
    StationInfoXMLDataInnerFromJSONTyped,
    StationInfoXMLDataInnerToJSON,
    StationInfoXMLDataInnerToJSONTyped,
} from './station-info-xml-data-inner';

/**
 * 
 * @export
 * @interface StationInfoXML
 */
export interface StationInfoXML {
    /**
     * 
     * @type {number}
     * @memberof StationInfoXML
     */
    requestIndex?: number;
    /**
     * 
     * @type {PIREPXMLDataSource}
     * @memberof StationInfoXML
     */
    dataSource?: PIREPXMLDataSource;
    /**
     * 
     * @type {METARXMLRequest}
     * @memberof StationInfoXML
     */
    request?: METARXMLRequest;
    /**
     * 
     * @type {number}
     * @memberof StationInfoXML
     */
    timeTakenMs?: number;
    /**
     * 
     * @type {Array<StationInfoXMLDataInner>}
     * @memberof StationInfoXML
     */
    data?: Array<StationInfoXMLDataInner>;
}

/**
 * Check if a given object implements the StationInfoXML interface.
 */
export function instanceOfStationInfoXML(value: object): value is StationInfoXML {
    return true;
}

export function StationInfoXMLFromJSON(json: any): StationInfoXML {
    return StationInfoXMLFromJSONTyped(json, false);
}

export function StationInfoXMLFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationInfoXML {
    if (json == null) {
        return json;
    }
    return {
        
        'requestIndex': json['request_index'] == null ? undefined : json['request_index'],
        'dataSource': json['data_source'] == null ? undefined : PIREPXMLDataSourceFromJSON(json['data_source']),
        'request': json['request'] == null ? undefined : METARXMLRequestFromJSON(json['request']),
        'timeTakenMs': json['time_taken_ms'] == null ? undefined : json['time_taken_ms'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(StationInfoXMLDataInnerFromJSON)),
    };
}

export function StationInfoXMLToJSON(json: any): StationInfoXML {
    return StationInfoXMLToJSONTyped(json, false);
}

export function StationInfoXMLToJSONTyped(value?: StationInfoXML | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'request_index': value['requestIndex'],
        'data_source': PIREPXMLDataSourceToJSON(value['dataSource']),
        'request': METARXMLRequestToJSON(value['request']),
        'time_taken_ms': value['timeTakenMs'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(StationInfoXMLDataInnerToJSON)),
    };
}

