/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationInfoJSONInner
 */
export interface StationInfoJSONInner {
    /**
     * ICAO station identifier
     * @type {string}
     * @memberof StationInfoJSONInner
     */
    icaoId?: string;
    /**
     * IATA station identifier
     * @type {string}
     * @memberof StationInfoJSONInner
     */
    iataId?: string;
    /**
     * FAA station identifier
     * @type {string}
     * @memberof StationInfoJSONInner
     */
    faaId?: string;
    /**
     * Site name
     * @type {string}
     * @memberof StationInfoJSONInner
     */
    site?: string;
    /**
     * Latitude
     * @type {number}
     * @memberof StationInfoJSONInner
     */
    lat?: number;
    /**
     * Longitude
     * @type {number}
     * @memberof StationInfoJSONInner
     */
    lon?: number;
    /**
     * Elevation
     * @type {number}
     * @memberof StationInfoJSONInner
     */
    elev?: number;
    /**
     * State or region
     * @type {string}
     * @memberof StationInfoJSONInner
     */
    state?: string;
    /**
     * Country
     * @type {string}
     * @memberof StationInfoJSONInner
     */
    country?: string;
    /**
     * Priority display order
     * @type {number}
     * @memberof StationInfoJSONInner
     */
    priority?: number;
    /**
     * METAR and/or TAF availability
     * @type {Array<string>}
     * @memberof StationInfoJSONInner
     */
    siteType?: Array<string>;
}

/**
 * Check if a given object implements the StationInfoJSONInner interface.
 */
export function instanceOfStationInfoJSONInner(value: object): value is StationInfoJSONInner {
    return true;
}

export function StationInfoJSONInnerFromJSON(json: any): StationInfoJSONInner {
    return StationInfoJSONInnerFromJSONTyped(json, false);
}

export function StationInfoJSONInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationInfoJSONInner {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'iataId': json['iataId'] == null ? undefined : json['iataId'],
        'faaId': json['faaId'] == null ? undefined : json['faaId'],
        'site': json['site'] == null ? undefined : json['site'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'elev': json['elev'] == null ? undefined : json['elev'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'siteType': json['siteType'] == null ? undefined : json['siteType'],
    };
}

export function StationInfoJSONInnerToJSON(json: any): StationInfoJSONInner {
    return StationInfoJSONInnerToJSONTyped(json, false);
}

export function StationInfoJSONInnerToJSONTyped(value?: StationInfoJSONInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'iataId': value['iataId'],
        'faaId': value['faaId'],
        'site': value['site'],
        'lat': value['lat'],
        'lon': value['lon'],
        'elev': value['elev'],
        'state': value['state'],
        'country': value['country'],
        'priority': value['priority'],
        'siteType': value['siteType'],
    };
}

