/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StationInfoGeoJSONFeaturesInner } from './station-info-geo-json-features-inner';
import {
    StationInfoGeoJSONFeaturesInnerFromJSON,
    StationInfoGeoJSONFeaturesInnerFromJSONTyped,
    StationInfoGeoJSONFeaturesInnerToJSON,
    StationInfoGeoJSONFeaturesInnerToJSONTyped,
} from './station-info-geo-json-features-inner';

/**
 * 
 * @export
 * @interface StationInfoGeoJSON
 */
export interface StationInfoGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof StationInfoGeoJSON
     */
    type?: StationInfoGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<StationInfoGeoJSONFeaturesInner>}
     * @memberof StationInfoGeoJSON
     */
    features?: Array<StationInfoGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const StationInfoGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type StationInfoGeoJSONTypeEnum = typeof StationInfoGeoJSONTypeEnum[keyof typeof StationInfoGeoJSONTypeEnum];


/**
 * Check if a given object implements the StationInfoGeoJSON interface.
 */
export function instanceOfStationInfoGeoJSON(value: object): value is StationInfoGeoJSON {
    return true;
}

export function StationInfoGeoJSONFromJSON(json: any): StationInfoGeoJSON {
    return StationInfoGeoJSONFromJSONTyped(json, false);
}

export function StationInfoGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationInfoGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(StationInfoGeoJSONFeaturesInnerFromJSON)),
    };
}

export function StationInfoGeoJSONToJSON(json: any): StationInfoGeoJSON {
    return StationInfoGeoJSONToJSONTyped(json, false);
}

export function StationInfoGeoJSONToJSONTyped(value?: StationInfoGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(StationInfoGeoJSONFeaturesInnerToJSON)),
    };
}

