/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StationInfoXMLDataInner
 */
export interface StationInfoXMLDataInner {
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    stationId?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    iataId?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    wmoId?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    faaId?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    latitude?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    longitude?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    elevationM?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    site?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof StationInfoXMLDataInner
     */
    country?: string;
    /**
     * 
     * @type {object}
     * @memberof StationInfoXMLDataInner
     */
    siteType?: object;
}

/**
 * Check if a given object implements the StationInfoXMLDataInner interface.
 */
export function instanceOfStationInfoXMLDataInner(value: object): value is StationInfoXMLDataInner {
    return true;
}

export function StationInfoXMLDataInnerFromJSON(json: any): StationInfoXMLDataInner {
    return StationInfoXMLDataInnerFromJSONTyped(json, false);
}

export function StationInfoXMLDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StationInfoXMLDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'stationId': json['station_id'] == null ? undefined : json['station_id'],
        'iataId': json['iata_id'] == null ? undefined : json['iata_id'],
        'wmoId': json['wmo_id'] == null ? undefined : json['wmo_id'],
        'faaId': json['faa_id'] == null ? undefined : json['faa_id'],
        'latitude': json['latitude'] == null ? undefined : json['latitude'],
        'longitude': json['longitude'] == null ? undefined : json['longitude'],
        'elevationM': json['elevation_m'] == null ? undefined : json['elevation_m'],
        'site': json['site'] == null ? undefined : json['site'],
        'state': json['state'] == null ? undefined : json['state'],
        'country': json['country'] == null ? undefined : json['country'],
        'siteType': json['site_type'] == null ? undefined : json['site_type'],
    };
}

export function StationInfoXMLDataInnerToJSON(json: any): StationInfoXMLDataInner {
    return StationInfoXMLDataInnerToJSONTyped(json, false);
}

export function StationInfoXMLDataInnerToJSONTyped(value?: StationInfoXMLDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'station_id': value['stationId'],
        'iata_id': value['iataId'],
        'wmo_id': value['wmoId'],
        'faa_id': value['faaId'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'elevation_m': value['elevationM'],
        'site': value['site'],
        'state': value['state'],
        'country': value['country'],
        'site_type': value['siteType'],
    };
}

