/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Wind direction in degrees of VRB for variable winds
 * @export
 * @interface TAFpropertiesFcstsInnerWdir
 */
export interface TAFpropertiesFcstsInnerWdir {
}

/**
 * Check if a given object implements the TAFpropertiesFcstsInnerWdir interface.
 */
export function instanceOfTAFpropertiesFcstsInnerWdir(value: object): value is TAFpropertiesFcstsInnerWdir {
    return true;
}

export function TAFpropertiesFcstsInnerWdirFromJSON(json: any): TAFpropertiesFcstsInnerWdir {
    return TAFpropertiesFcstsInnerWdirFromJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerWdirFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFpropertiesFcstsInnerWdir {
    return json;
}

export function TAFpropertiesFcstsInnerWdirToJSON(json: any): TAFpropertiesFcstsInnerWdir {
    return TAFpropertiesFcstsInnerWdirToJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerWdirToJSONTyped(value?: TAFpropertiesFcstsInnerWdir | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

