/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TAFpropertiesFcstsInner } from './ta-fproperties-fcsts-inner';
import {
    TAFpropertiesFcstsInnerFromJSON,
    TAFpropertiesFcstsInnerFromJSONTyped,
    TAFpropertiesFcstsInnerToJSON,
    TAFpropertiesFcstsInnerToJSONTyped,
} from './ta-fproperties-fcsts-inner';

/**
 * TAFs
 * @export
 * @interface TAFproperties
 */
export interface TAFproperties {
    /**
     * ICAO identifier
     * @type {string}
     * @memberof TAFproperties
     */
    icaoId?: string;
    /**
     * The time the product was received (yyyy-mm-dd hh:mm:ss.sssZ)
     * @type {string}
     * @memberof TAFproperties
     */
    dbPopTime?: string;
    /**
     * The official time of the bulletin (yyyy-mm-dd hh:mm:ss.sssZ)
     * @type {string}
     * @memberof TAFproperties
     */
    bulletinTime?: string;
    /**
     * The time the product was issued (yyyy-mm-dd hh:mm:ss.sssZ)
     * @type {string}
     * @memberof TAFproperties
     */
    issueTime?: string;
    /**
     * The time the period of validity starts (unix timestamp)
     * @type {number}
     * @memberof TAFproperties
     */
    validTimeFrom?: number;
    /**
     * The time the period of validity ends (unix timestamp)
     * @type {number}
     * @memberof TAFproperties
     */
    validTimeTo?: number;
    /**
     * The raw text of the TAF
     * @type {string}
     * @memberof TAFproperties
     */
    rawTAF?: string;
    /**
     * Most recent flag (1=most recent, 0=not)
     * @type {number}
     * @memberof TAFproperties
     */
    mostRecent?: number;
    /**
     * Any additional remarks for TAF
     * @type {string}
     * @memberof TAFproperties
     */
    remarks?: string;
    /**
     * Latitude of site in degrees
     * @type {number}
     * @memberof TAFproperties
     */
    lat?: number;
    /**
     * Longitude of site in degrees
     * @type {number}
     * @memberof TAFproperties
     */
    lon?: number;
    /**
     * Elevation of site in meters
     * @type {number}
     * @memberof TAFproperties
     */
    elev?: number;
    /**
     * Priority of site for progressive disclosure (0-9)
     * @type {number}
     * @memberof TAFproperties
     */
    prior?: number;
    /**
     * Full name of the site
     * @type {string}
     * @memberof TAFproperties
     */
    name?: string;
    /**
     * Each forecast within the TAF
     * @type {Array<TAFpropertiesFcstsInner>}
     * @memberof TAFproperties
     */
    fcsts?: Array<TAFpropertiesFcstsInner>;
}

/**
 * Check if a given object implements the TAFproperties interface.
 */
export function instanceOfTAFproperties(value: object): value is TAFproperties {
    return true;
}

export function TAFpropertiesFromJSON(json: any): TAFproperties {
    return TAFpropertiesFromJSONTyped(json, false);
}

export function TAFpropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFproperties {
    if (json == null) {
        return json;
    }
    return {
        
        'icaoId': json['icaoId'] == null ? undefined : json['icaoId'],
        'dbPopTime': json['dbPopTime'] == null ? undefined : json['dbPopTime'],
        'bulletinTime': json['bulletinTime'] == null ? undefined : json['bulletinTime'],
        'issueTime': json['issueTime'] == null ? undefined : json['issueTime'],
        'validTimeFrom': json['validTimeFrom'] == null ? undefined : json['validTimeFrom'],
        'validTimeTo': json['validTimeTo'] == null ? undefined : json['validTimeTo'],
        'rawTAF': json['rawTAF'] == null ? undefined : json['rawTAF'],
        'mostRecent': json['mostRecent'] == null ? undefined : json['mostRecent'],
        'remarks': json['remarks'] == null ? undefined : json['remarks'],
        'lat': json['lat'] == null ? undefined : json['lat'],
        'lon': json['lon'] == null ? undefined : json['lon'],
        'elev': json['elev'] == null ? undefined : json['elev'],
        'prior': json['prior'] == null ? undefined : json['prior'],
        'name': json['name'] == null ? undefined : json['name'],
        'fcsts': json['fcsts'] == null ? undefined : ((json['fcsts'] as Array<any>).map(TAFpropertiesFcstsInnerFromJSON)),
    };
}

export function TAFpropertiesToJSON(json: any): TAFproperties {
    return TAFpropertiesToJSONTyped(json, false);
}

export function TAFpropertiesToJSONTyped(value?: TAFproperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'icaoId': value['icaoId'],
        'dbPopTime': value['dbPopTime'],
        'bulletinTime': value['bulletinTime'],
        'issueTime': value['issueTime'],
        'validTimeFrom': value['validTimeFrom'],
        'validTimeTo': value['validTimeTo'],
        'rawTAF': value['rawTAF'],
        'mostRecent': value['mostRecent'],
        'remarks': value['remarks'],
        'lat': value['lat'],
        'lon': value['lon'],
        'elev': value['elev'],
        'prior': value['prior'],
        'name': value['name'],
        'fcsts': value['fcsts'] == null ? undefined : ((value['fcsts'] as Array<any>).map(TAFpropertiesFcstsInnerToJSON)),
    };
}

