/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Icing or turbulence data
 * @export
 * @interface TAFpropertiesFcstsInnerIcgTurbInner
 */
export interface TAFpropertiesFcstsInnerIcgTurbInner {
    /**
     * Variable - ice or turb
     * @type {string}
     * @memberof TAFpropertiesFcstsInnerIcgTurbInner
     */
    _var: TAFpropertiesFcstsInnerIcgTurbInnerVarEnum;
    /**
     * Intensity setting (0-9, see TAF implementation table)
     * @type {number}
     * @memberof TAFpropertiesFcstsInnerIcgTurbInner
     */
    intensity: number;
    /**
     * Minimum altitude in feet
     * @type {number}
     * @memberof TAFpropertiesFcstsInnerIcgTurbInner
     */
    minAlt: number;
    /**
     * Maximum altitude in feet
     * @type {number}
     * @memberof TAFpropertiesFcstsInnerIcgTurbInner
     */
    maxAlt: number;
}


/**
 * @export
 */
export const TAFpropertiesFcstsInnerIcgTurbInnerVarEnum = {
    Ice: 'ICE',
    Turb: 'TURB'
} as const;
export type TAFpropertiesFcstsInnerIcgTurbInnerVarEnum = typeof TAFpropertiesFcstsInnerIcgTurbInnerVarEnum[keyof typeof TAFpropertiesFcstsInnerIcgTurbInnerVarEnum];


/**
 * Check if a given object implements the TAFpropertiesFcstsInnerIcgTurbInner interface.
 */
export function instanceOfTAFpropertiesFcstsInnerIcgTurbInner(value: object): value is TAFpropertiesFcstsInnerIcgTurbInner {
    if (!('_var' in value) || value['_var'] === undefined) return false;
    if (!('intensity' in value) || value['intensity'] === undefined) return false;
    if (!('minAlt' in value) || value['minAlt'] === undefined) return false;
    if (!('maxAlt' in value) || value['maxAlt'] === undefined) return false;
    return true;
}

export function TAFpropertiesFcstsInnerIcgTurbInnerFromJSON(json: any): TAFpropertiesFcstsInnerIcgTurbInner {
    return TAFpropertiesFcstsInnerIcgTurbInnerFromJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerIcgTurbInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFpropertiesFcstsInnerIcgTurbInner {
    if (json == null) {
        return json;
    }
    return {
        
        '_var': json['var'],
        'intensity': json['intensity'],
        'minAlt': json['minAlt'],
        'maxAlt': json['maxAlt'],
    };
}

export function TAFpropertiesFcstsInnerIcgTurbInnerToJSON(json: any): TAFpropertiesFcstsInnerIcgTurbInner {
    return TAFpropertiesFcstsInnerIcgTurbInnerToJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerIcgTurbInnerToJSONTyped(value?: TAFpropertiesFcstsInnerIcgTurbInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'var': value['_var'],
        'intensity': value['intensity'],
        'minAlt': value['minAlt'],
        'maxAlt': value['maxAlt'],
    };
}

