/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A Schema
 * @export
 * @interface TAFpropertiesFcstsInnerTempInner
 */
export interface TAFpropertiesFcstsInnerTempInner {
    /**
     * Valid time for max/min temperature (unix timestamp)
     * @type {number}
     * @memberof TAFpropertiesFcstsInnerTempInner
     */
    validTime: number;
    /**
     * Surface tmperature in Celsius
     * @type {number}
     * @memberof TAFpropertiesFcstsInnerTempInner
     */
    sfcTemp: number;
    /**
     * Is the value a max or min
     * @type {string}
     * @memberof TAFpropertiesFcstsInnerTempInner
     */
    maxOrMin: TAFpropertiesFcstsInnerTempInnerMaxOrMinEnum;
}


/**
 * @export
 */
export const TAFpropertiesFcstsInnerTempInnerMaxOrMinEnum = {
    Max: 'MAX',
    Min: 'MIN'
} as const;
export type TAFpropertiesFcstsInnerTempInnerMaxOrMinEnum = typeof TAFpropertiesFcstsInnerTempInnerMaxOrMinEnum[keyof typeof TAFpropertiesFcstsInnerTempInnerMaxOrMinEnum];


/**
 * Check if a given object implements the TAFpropertiesFcstsInnerTempInner interface.
 */
export function instanceOfTAFpropertiesFcstsInnerTempInner(value: object): value is TAFpropertiesFcstsInnerTempInner {
    if (!('validTime' in value) || value['validTime'] === undefined) return false;
    if (!('sfcTemp' in value) || value['sfcTemp'] === undefined) return false;
    if (!('maxOrMin' in value) || value['maxOrMin'] === undefined) return false;
    return true;
}

export function TAFpropertiesFcstsInnerTempInnerFromJSON(json: any): TAFpropertiesFcstsInnerTempInner {
    return TAFpropertiesFcstsInnerTempInnerFromJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerTempInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFpropertiesFcstsInnerTempInner {
    if (json == null) {
        return json;
    }
    return {
        
        'validTime': json['validTime'],
        'sfcTemp': json['sfcTemp'],
        'maxOrMin': json['maxOrMin'],
    };
}

export function TAFpropertiesFcstsInnerTempInnerToJSON(json: any): TAFpropertiesFcstsInnerTempInner {
    return TAFpropertiesFcstsInnerTempInnerToJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerTempInnerToJSONTyped(value?: TAFpropertiesFcstsInnerTempInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validTime': value['validTime'],
        'sfcTemp': value['sfcTemp'],
        'maxOrMin': value['maxOrMin'],
    };
}

