/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CloudInfoInner } from './cloud-info-inner';
import {
    CloudInfoInnerFromJSON,
    CloudInfoInnerFromJSONTyped,
    CloudInfoInnerToJSON,
    CloudInfoInnerToJSONTyped,
} from './cloud-info-inner';
import type { TAFpropertiesFcstsInnerVisib } from './ta-fproperties-fcsts-inner-visib';
import {
    TAFpropertiesFcstsInnerVisibFromJSON,
    TAFpropertiesFcstsInnerVisibFromJSONTyped,
    TAFpropertiesFcstsInnerVisibToJSON,
    TAFpropertiesFcstsInnerVisibToJSONTyped,
} from './ta-fproperties-fcsts-inner-visib';
import type { TAFpropertiesFcstsInnerIcgTurbInner } from './ta-fproperties-fcsts-inner-icg-turb-inner';
import {
    TAFpropertiesFcstsInnerIcgTurbInnerFromJSON,
    TAFpropertiesFcstsInnerIcgTurbInnerFromJSONTyped,
    TAFpropertiesFcstsInnerIcgTurbInnerToJSON,
    TAFpropertiesFcstsInnerIcgTurbInnerToJSONTyped,
} from './ta-fproperties-fcsts-inner-icg-turb-inner';
import type { TAFpropertiesFcstsInnerTempInner } from './ta-fproperties-fcsts-inner-temp-inner';
import {
    TAFpropertiesFcstsInnerTempInnerFromJSON,
    TAFpropertiesFcstsInnerTempInnerFromJSONTyped,
    TAFpropertiesFcstsInnerTempInnerToJSON,
    TAFpropertiesFcstsInnerTempInnerToJSONTyped,
} from './ta-fproperties-fcsts-inner-temp-inner';
import type { TAFpropertiesFcstsInnerWdir } from './ta-fproperties-fcsts-inner-wdir';
import {
    TAFpropertiesFcstsInnerWdirFromJSON,
    TAFpropertiesFcstsInnerWdirFromJSONTyped,
    TAFpropertiesFcstsInnerWdirToJSON,
    TAFpropertiesFcstsInnerWdirToJSONTyped,
} from './ta-fproperties-fcsts-inner-wdir';

/**
 * 
 * @export
 * @interface TAFpropertiesFcstsInner
 */
export interface TAFpropertiesFcstsInner {
    /**
     * The time the forecast validity starts (UNIX timestamp)
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    timeFrom: number;
    /**
     * The time the forecast validity ends (UNIX timestamp)
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    timeTo: number;
    /**
     * The time the forecast transition ends BECMG 0501/0503 - last time in sequence (UNIX timestamp)
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    timeBec: number;
    /**
     * Change type for each forecast
     * @type {string}
     * @memberof TAFpropertiesFcstsInner
     */
    fcstChange: TAFpropertiesFcstsInnerFcstChangeEnum;
    /**
     * The probability of occurrence from PROB30 change group
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    probability: number;
    /**
     * 
     * @type {TAFpropertiesFcstsInnerWdir}
     * @memberof TAFpropertiesFcstsInner
     */
    wdir: TAFpropertiesFcstsInnerWdir;
    /**
     * Wind speed in knots
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    wspd: number;
    /**
     * Wind gusts in knots
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    wgst: number;
    /**
     * Wind shear layer top in feet
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    wshearHgt: number;
    /**
     * Wind direction at top of wind shear layer in degrees
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    wshearDir: number;
    /**
     * Wind speed at top of wind shear layer in knots
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    wshearSpd: number;
    /**
     * 
     * @type {TAFpropertiesFcstsInnerVisib}
     * @memberof TAFpropertiesFcstsInner
     */
    visib: TAFpropertiesFcstsInnerVisib;
    /**
     * Altimeter setting in hectoPascal
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    altim: number;
    /**
     * Vertical visibility in feet
     * @type {number}
     * @memberof TAFpropertiesFcstsInner
     */
    vertVis: number;
    /**
     * Encoded present weather string
     * @type {string}
     * @memberof TAFpropertiesFcstsInner
     */
    wxString: string;
    /**
     * Any text that wasn't decoded
     * @type {string}
     * @memberof TAFpropertiesFcstsInner
     */
    notDecoded: string;
    /**
     * Clouds
     * @type {Array<CloudInfoInner>}
     * @memberof TAFpropertiesFcstsInner
     */
    clouds: Array<CloudInfoInner>;
    /**
     * Icing and turbulence forecasts
     * @type {Array<TAFpropertiesFcstsInnerIcgTurbInner>}
     * @memberof TAFpropertiesFcstsInner
     */
    icgTurb: Array<TAFpropertiesFcstsInnerIcgTurbInner>;
    /**
     * The temp Schema
     * @type {Array<TAFpropertiesFcstsInnerTempInner>}
     * @memberof TAFpropertiesFcstsInner
     */
    temp: Array<TAFpropertiesFcstsInnerTempInner>;
}


/**
 * @export
 */
export const TAFpropertiesFcstsInnerFcstChangeEnum = {
    Tempo: 'TEMPO',
    Fm: 'FM',
    Becmg: 'BECMG',
    Prob: 'PROB'
} as const;
export type TAFpropertiesFcstsInnerFcstChangeEnum = typeof TAFpropertiesFcstsInnerFcstChangeEnum[keyof typeof TAFpropertiesFcstsInnerFcstChangeEnum];


/**
 * Check if a given object implements the TAFpropertiesFcstsInner interface.
 */
export function instanceOfTAFpropertiesFcstsInner(value: object): value is TAFpropertiesFcstsInner {
    if (!('timeFrom' in value) || value['timeFrom'] === undefined) return false;
    if (!('timeTo' in value) || value['timeTo'] === undefined) return false;
    if (!('timeBec' in value) || value['timeBec'] === undefined) return false;
    if (!('fcstChange' in value) || value['fcstChange'] === undefined) return false;
    if (!('probability' in value) || value['probability'] === undefined) return false;
    if (!('wdir' in value) || value['wdir'] === undefined) return false;
    if (!('wspd' in value) || value['wspd'] === undefined) return false;
    if (!('wgst' in value) || value['wgst'] === undefined) return false;
    if (!('wshearHgt' in value) || value['wshearHgt'] === undefined) return false;
    if (!('wshearDir' in value) || value['wshearDir'] === undefined) return false;
    if (!('wshearSpd' in value) || value['wshearSpd'] === undefined) return false;
    if (!('visib' in value) || value['visib'] === undefined) return false;
    if (!('altim' in value) || value['altim'] === undefined) return false;
    if (!('vertVis' in value) || value['vertVis'] === undefined) return false;
    if (!('wxString' in value) || value['wxString'] === undefined) return false;
    if (!('notDecoded' in value) || value['notDecoded'] === undefined) return false;
    if (!('clouds' in value) || value['clouds'] === undefined) return false;
    if (!('icgTurb' in value) || value['icgTurb'] === undefined) return false;
    if (!('temp' in value) || value['temp'] === undefined) return false;
    return true;
}

export function TAFpropertiesFcstsInnerFromJSON(json: any): TAFpropertiesFcstsInner {
    return TAFpropertiesFcstsInnerFromJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFpropertiesFcstsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'timeFrom': json['timeFrom'],
        'timeTo': json['timeTo'],
        'timeBec': json['timeBec'],
        'fcstChange': json['fcstChange'],
        'probability': json['probability'],
        'wdir': TAFpropertiesFcstsInnerWdirFromJSON(json['wdir']),
        'wspd': json['wspd'],
        'wgst': json['wgst'],
        'wshearHgt': json['wshearHgt'],
        'wshearDir': json['wshearDir'],
        'wshearSpd': json['wshearSpd'],
        'visib': TAFpropertiesFcstsInnerVisibFromJSON(json['visib']),
        'altim': json['altim'],
        'vertVis': json['vertVis'],
        'wxString': json['wxString'],
        'notDecoded': json['notDecoded'],
        'clouds': ((json['clouds'] as Array<any>).map(CloudInfoInnerFromJSON)),
        'icgTurb': ((json['icgTurb'] as Array<any>).map(TAFpropertiesFcstsInnerIcgTurbInnerFromJSON)),
        'temp': ((json['temp'] as Array<any>).map(TAFpropertiesFcstsInnerTempInnerFromJSON)),
    };
}

export function TAFpropertiesFcstsInnerToJSON(json: any): TAFpropertiesFcstsInner {
    return TAFpropertiesFcstsInnerToJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerToJSONTyped(value?: TAFpropertiesFcstsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'timeFrom': value['timeFrom'],
        'timeTo': value['timeTo'],
        'timeBec': value['timeBec'],
        'fcstChange': value['fcstChange'],
        'probability': value['probability'],
        'wdir': TAFpropertiesFcstsInnerWdirToJSON(value['wdir']),
        'wspd': value['wspd'],
        'wgst': value['wgst'],
        'wshearHgt': value['wshearHgt'],
        'wshearDir': value['wshearDir'],
        'wshearSpd': value['wshearSpd'],
        'visib': TAFpropertiesFcstsInnerVisibToJSON(value['visib']),
        'altim': value['altim'],
        'vertVis': value['vertVis'],
        'wxString': value['wxString'],
        'notDecoded': value['notDecoded'],
        'clouds': ((value['clouds'] as Array<any>).map(CloudInfoInnerToJSON)),
        'icgTurb': ((value['icgTurb'] as Array<any>).map(TAFpropertiesFcstsInnerIcgTurbInnerToJSON)),
        'temp': ((value['temp'] as Array<any>).map(TAFpropertiesFcstsInnerTempInnerToJSON)),
    };
}

