/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Visibility in statute miles, 6+ is greater than 6 sm
 * @export
 * @interface TAFpropertiesFcstsInnerVisib
 */
export interface TAFpropertiesFcstsInnerVisib {
}

/**
 * Check if a given object implements the TAFpropertiesFcstsInnerVisib interface.
 */
export function instanceOfTAFpropertiesFcstsInnerVisib(value: object): value is TAFpropertiesFcstsInnerVisib {
    return true;
}

export function TAFpropertiesFcstsInnerVisibFromJSON(json: any): TAFpropertiesFcstsInnerVisib {
    return TAFpropertiesFcstsInnerVisibFromJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerVisibFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFpropertiesFcstsInnerVisib {
    return json;
}

export function TAFpropertiesFcstsInnerVisibToJSON(json: any): TAFpropertiesFcstsInnerVisib {
    return TAFpropertiesFcstsInnerVisibToJSONTyped(json, false);
}

export function TAFpropertiesFcstsInnerVisibToJSONTyped(value?: TAFpropertiesFcstsInnerVisib | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

