/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TAFproperties } from './ta-fproperties';
import {
    TAFpropertiesFromJSON,
    TAFpropertiesFromJSONTyped,
    TAFpropertiesToJSON,
    TAFpropertiesToJSONTyped,
} from './ta-fproperties';
import type { METARGeoJSONFeaturesInnerGeometry } from './metar-geo-json-features-inner-geometry';
import {
    METARGeoJSONFeaturesInnerGeometryFromJSON,
    METARGeoJSONFeaturesInnerGeometryFromJSONTyped,
    METARGeoJSONFeaturesInnerGeometryToJSON,
    METARGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './metar-geo-json-features-inner-geometry';

/**
 * 
 * @export
 * @interface TAFGeoJSONFeaturesInner
 */
export interface TAFGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof TAFGeoJSONFeaturesInner
     */
    type?: TAFGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TAFGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {TAFproperties}
     * @memberof TAFGeoJSONFeaturesInner
     */
    properties?: TAFproperties;
    /**
     * 
     * @type {METARGeoJSONFeaturesInnerGeometry}
     * @memberof TAFGeoJSONFeaturesInner
     */
    geometry?: METARGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const TAFGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type TAFGeoJSONFeaturesInnerTypeEnum = typeof TAFGeoJSONFeaturesInnerTypeEnum[keyof typeof TAFGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the TAFGeoJSONFeaturesInner interface.
 */
export function instanceOfTAFGeoJSONFeaturesInner(value: object): value is TAFGeoJSONFeaturesInner {
    return true;
}

export function TAFGeoJSONFeaturesInnerFromJSON(json: any): TAFGeoJSONFeaturesInner {
    return TAFGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function TAFGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : TAFpropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : METARGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function TAFGeoJSONFeaturesInnerToJSON(json: any): TAFGeoJSONFeaturesInner {
    return TAFGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function TAFGeoJSONFeaturesInnerToJSONTyped(value?: TAFGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': TAFpropertiesToJSON(value['properties']),
        'geometry': METARGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

