/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TAFGeoJSONFeaturesInner } from './taf-geo-json-features-inner';
import {
    TAFGeoJSONFeaturesInnerFromJSON,
    TAFGeoJSONFeaturesInnerFromJSONTyped,
    TAFGeoJSONFeaturesInnerToJSON,
    TAFGeoJSONFeaturesInnerToJSONTyped,
} from './taf-geo-json-features-inner';

/**
 * 
 * @export
 * @interface TAFGeoJSON
 */
export interface TAFGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof TAFGeoJSON
     */
    type?: TAFGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<TAFGeoJSONFeaturesInner>}
     * @memberof TAFGeoJSON
     */
    features?: Array<TAFGeoJSONFeaturesInner>;
}


/**
 * @export
 */
export const TAFGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type TAFGeoJSONTypeEnum = typeof TAFGeoJSONTypeEnum[keyof typeof TAFGeoJSONTypeEnum];


/**
 * Check if a given object implements the TAFGeoJSON interface.
 */
export function instanceOfTAFGeoJSON(value: object): value is TAFGeoJSON {
    return true;
}

export function TAFGeoJSONFromJSON(json: any): TAFGeoJSON {
    return TAFGeoJSONFromJSONTyped(json, false);
}

export function TAFGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): TAFGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(TAFGeoJSONFeaturesInnerFromJSON)),
    };
}

export function TAFGeoJSONToJSON(json: any): TAFGeoJSON {
    return TAFGeoJSONToJSONTyped(json, false);
}

export function TAFGeoJSONToJSONTyped(value?: TAFGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(TAFGeoJSONFeaturesInnerToJSON)),
    };
}

