/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TcfGeoJSONFeaturesInnerProperties
 */
export interface TcfGeoJSONFeaturesInnerProperties {
    /**
     * 
     * @type {string}
     * @memberof TcfGeoJSONFeaturesInnerProperties
     */
    validTime?: string;
    /**
     * 
     * @type {string}
     * @memberof TcfGeoJSONFeaturesInnerProperties
     */
    issueTime?: string;
    /**
     * Convective coverage
     * @type {string}
     * @memberof TcfGeoJSONFeaturesInnerProperties
     */
    coverage?: TcfGeoJSONFeaturesInnerPropertiesCoverageEnum;
    /**
     * Forecast confidence
     * @type {string}
     * @memberof TcfGeoJSONFeaturesInnerProperties
     */
    confidence?: TcfGeoJSONFeaturesInnerPropertiesConfidenceEnum;
    /**
     * Echo top category
     * @type {number}
     * @memberof TcfGeoJSONFeaturesInnerProperties
     */
    tops?: TcfGeoJSONFeaturesInnerPropertiesTopsEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof TcfGeoJSONFeaturesInnerProperties
     */
    labelpos?: Array<number>;
}


/**
 * @export
 */
export const TcfGeoJSONFeaturesInnerPropertiesCoverageEnum = {
    Sparse: 'sparse',
    Medium: 'medium'
} as const;
export type TcfGeoJSONFeaturesInnerPropertiesCoverageEnum = typeof TcfGeoJSONFeaturesInnerPropertiesCoverageEnum[keyof typeof TcfGeoJSONFeaturesInnerPropertiesCoverageEnum];

/**
 * @export
 */
export const TcfGeoJSONFeaturesInnerPropertiesConfidenceEnum = {
    High: 'high'
} as const;
export type TcfGeoJSONFeaturesInnerPropertiesConfidenceEnum = typeof TcfGeoJSONFeaturesInnerPropertiesConfidenceEnum[keyof typeof TcfGeoJSONFeaturesInnerPropertiesConfidenceEnum];

/**
 * @export
 */
export const TcfGeoJSONFeaturesInnerPropertiesTopsEnum = {
    NUMBER_290: 290,
    NUMBER_340: 340,
    NUMBER_390: 390,
    NUMBER_400: 400
} as const;
export type TcfGeoJSONFeaturesInnerPropertiesTopsEnum = typeof TcfGeoJSONFeaturesInnerPropertiesTopsEnum[keyof typeof TcfGeoJSONFeaturesInnerPropertiesTopsEnum];


/**
 * Check if a given object implements the TcfGeoJSONFeaturesInnerProperties interface.
 */
export function instanceOfTcfGeoJSONFeaturesInnerProperties(value: object): value is TcfGeoJSONFeaturesInnerProperties {
    return true;
}

export function TcfGeoJSONFeaturesInnerPropertiesFromJSON(json: any): TcfGeoJSONFeaturesInnerProperties {
    return TcfGeoJSONFeaturesInnerPropertiesFromJSONTyped(json, false);
}

export function TcfGeoJSONFeaturesInnerPropertiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): TcfGeoJSONFeaturesInnerProperties {
    if (json == null) {
        return json;
    }
    return {
        
        'validTime': json['validTime'] == null ? undefined : json['validTime'],
        'issueTime': json['issueTime'] == null ? undefined : json['issueTime'],
        'coverage': json['coverage'] == null ? undefined : json['coverage'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'tops': json['tops'] == null ? undefined : json['tops'],
        'labelpos': json['labelpos'] == null ? undefined : json['labelpos'],
    };
}

export function TcfGeoJSONFeaturesInnerPropertiesToJSON(json: any): TcfGeoJSONFeaturesInnerProperties {
    return TcfGeoJSONFeaturesInnerPropertiesToJSONTyped(json, false);
}

export function TcfGeoJSONFeaturesInnerPropertiesToJSONTyped(value?: TcfGeoJSONFeaturesInnerProperties | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'validTime': value['validTime'],
        'issueTime': value['issueTime'],
        'coverage': value['coverage'],
        'confidence': value['confidence'],
        'tops': value['tops'],
        'labelpos': value['labelpos'],
    };
}

