/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TcfGeoJSONFeaturesInner } from './tcf-geo-json-features-inner';
import {
    TcfGeoJSONFeaturesInnerFromJSON,
    TcfGeoJSONFeaturesInnerFromJSONTyped,
    TcfGeoJSONFeaturesInnerToJSON,
    TcfGeoJSONFeaturesInnerToJSONTyped,
} from './tcf-geo-json-features-inner';

/**
 * 
 * @export
 * @interface TcfGeoJSON
 */
export interface TcfGeoJSON {
    /**
     * 
     * @type {string}
     * @memberof TcfGeoJSON
     */
    type?: TcfGeoJSONTypeEnum;
    /**
     * 
     * @type {Array<TcfGeoJSONFeaturesInner>}
     * @memberof TcfGeoJSON
     */
    features?: Array<TcfGeoJSONFeaturesInner>;
    /**
     * Issuance date and time
     * @type {string}
     * @memberof TcfGeoJSON
     */
    issueTime?: string;
}


/**
 * @export
 */
export const TcfGeoJSONTypeEnum = {
    FeatureCollection: 'FeatureCollection'
} as const;
export type TcfGeoJSONTypeEnum = typeof TcfGeoJSONTypeEnum[keyof typeof TcfGeoJSONTypeEnum];


/**
 * Check if a given object implements the TcfGeoJSON interface.
 */
export function instanceOfTcfGeoJSON(value: object): value is TcfGeoJSON {
    return true;
}

export function TcfGeoJSONFromJSON(json: any): TcfGeoJSON {
    return TcfGeoJSONFromJSONTyped(json, false);
}

export function TcfGeoJSONFromJSONTyped(json: any, ignoreDiscriminator: boolean): TcfGeoJSON {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(TcfGeoJSONFeaturesInnerFromJSON)),
        'issueTime': json['issueTime'] == null ? undefined : json['issueTime'],
    };
}

export function TcfGeoJSONToJSON(json: any): TcfGeoJSON {
    return TcfGeoJSONToJSONTyped(json, false);
}

export function TcfGeoJSONToJSONTyped(value?: TcfGeoJSON | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(TcfGeoJSONFeaturesInnerToJSON)),
        'issueTime': value['issueTime'],
    };
}

