/* tslint:disable */
/* eslint-disable */
/**
 * AviationWeather.gov API
 * Schema for public data API of AviationWeather.gov.
 *
 * The version of the OpenAPI document: v4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TcfGeoJSONFeaturesInnerProperties } from './tcf-geo-json-features-inner-properties';
import {
    TcfGeoJSONFeaturesInnerPropertiesFromJSON,
    TcfGeoJSONFeaturesInnerPropertiesFromJSONTyped,
    TcfGeoJSONFeaturesInnerPropertiesToJSON,
    TcfGeoJSONFeaturesInnerPropertiesToJSONTyped,
} from './tcf-geo-json-features-inner-properties';
import type { AirSigmetGeoJSONFeaturesInnerGeometry } from './air-sigmet-geo-json-features-inner-geometry';
import {
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryFromJSONTyped,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSON,
    AirSigmetGeoJSONFeaturesInnerGeometryToJSONTyped,
} from './air-sigmet-geo-json-features-inner-geometry';

/**
 * 
 * @export
 * @interface TcfGeoJSONFeaturesInner
 */
export interface TcfGeoJSONFeaturesInner {
    /**
     * 
     * @type {string}
     * @memberof TcfGeoJSONFeaturesInner
     */
    type?: TcfGeoJSONFeaturesInnerTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof TcfGeoJSONFeaturesInner
     */
    id?: number;
    /**
     * 
     * @type {TcfGeoJSONFeaturesInnerProperties}
     * @memberof TcfGeoJSONFeaturesInner
     */
    properties?: TcfGeoJSONFeaturesInnerProperties;
    /**
     * 
     * @type {AirSigmetGeoJSONFeaturesInnerGeometry}
     * @memberof TcfGeoJSONFeaturesInner
     */
    geometry?: AirSigmetGeoJSONFeaturesInnerGeometry;
}


/**
 * @export
 */
export const TcfGeoJSONFeaturesInnerTypeEnum = {
    Feature: 'Feature'
} as const;
export type TcfGeoJSONFeaturesInnerTypeEnum = typeof TcfGeoJSONFeaturesInnerTypeEnum[keyof typeof TcfGeoJSONFeaturesInnerTypeEnum];


/**
 * Check if a given object implements the TcfGeoJSONFeaturesInner interface.
 */
export function instanceOfTcfGeoJSONFeaturesInner(value: object): value is TcfGeoJSONFeaturesInner {
    return true;
}

export function TcfGeoJSONFeaturesInnerFromJSON(json: any): TcfGeoJSONFeaturesInner {
    return TcfGeoJSONFeaturesInnerFromJSONTyped(json, false);
}

export function TcfGeoJSONFeaturesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TcfGeoJSONFeaturesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'id': json['id'] == null ? undefined : json['id'],
        'properties': json['properties'] == null ? undefined : TcfGeoJSONFeaturesInnerPropertiesFromJSON(json['properties']),
        'geometry': json['geometry'] == null ? undefined : AirSigmetGeoJSONFeaturesInnerGeometryFromJSON(json['geometry']),
    };
}

export function TcfGeoJSONFeaturesInnerToJSON(json: any): TcfGeoJSONFeaturesInner {
    return TcfGeoJSONFeaturesInnerToJSONTyped(json, false);
}

export function TcfGeoJSONFeaturesInnerToJSONTyped(value?: TcfGeoJSONFeaturesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'id': value['id'],
        'properties': TcfGeoJSONFeaturesInnerPropertiesToJSON(value['properties']),
        'geometry': AirSigmetGeoJSONFeaturesInnerGeometryToJSON(value['geometry']),
    };
}

